export const TRADE_CATALOG = [
  { label: "General Contractor", popular: true, aliases: ["general contracting", "gc"] },
  { label: "Handyman", popular: true, aliases: ["home repair", "home maintenance"] },
  { label: "Remodeling", popular: true, aliases: ["remodel", "general remodeling"] },
  { label: "Bathroom Remodeling", popular: true, aliases: ["bath remodel", "bathroom remodel"] },
  { label: "Kitchen Remodeling", popular: true, aliases: ["kitchen remodel", "kitchen renovation"] },
  { label: "Flooring", popular: true, aliases: ["floor install", "floor replacement"] },
  { label: "Tile", popular: true, aliases: ["tile install", "tile work"] },
  { label: "Drywall", popular: true, aliases: ["sheetrock", "dry wall"] },
  { label: "Painting", popular: true, aliases: ["paint", "interior painting", "exterior painting"] },
  { label: "Roofing", popular: true, aliases: ["roof", "roof repair", "roof replacement"] },
  { label: "Siding", popular: true, aliases: ["exterior siding"] },
  { label: "Windows & Doors", popular: true, aliases: ["windows", "doors", "window replacement", "door replacement"] },
  { label: "Framing", popular: false, aliases: ["rough framing"] },
  { label: "Carpentry", popular: false, aliases: ["finish carpentry", "wood work"] },
  { label: "Cabinets", popular: false, aliases: ["cabinet install", "cabinetry"] },
  { label: "Countertops", popular: false, aliases: ["countertop install"] },
  { label: "Concrete", popular: false, aliases: ["cement", "slab", "driveway"] },
  { label: "Masonry", popular: false, aliases: ["brick", "stone"] },
  { label: "Fencing", popular: false, aliases: ["fence", "fence install"] },
  { label: "Decks & Patios", popular: false, aliases: ["deck", "patio", "pergola"] },
  { label: "Landscaping", popular: true, aliases: ["landscape", "yard work"] },
  { label: "Lawn Care", popular: true, aliases: ["lawn maintenance", "yard maintenance"] },
  { label: "Irrigation", popular: false, aliases: ["sprinkler", "sprinklers"] },
  { label: "Tree Service", popular: false, aliases: ["tree trimming", "tree removal"] },
  { label: "Pest Control", popular: true, aliases: ["exterminator"] },
  { label: "Pool Service", popular: true, aliases: ["pool maintenance"] },
  { label: "HVAC", popular: true, aliases: ["heating and cooling", "central air", "air conditioner", "ac installation", "hvac installation", "cooling system"] },
  { label: "Electrical", popular: true, aliases: ["electrician", "electrical work"] },
  { label: "Plumbing", popular: true, aliases: ["plumber", "pipe repair"] },
  { label: "Appliance Repair", popular: false, aliases: ["appliance service"] },
  { label: "Garage Doors", popular: false, aliases: ["garage door repair"] },
  { label: "Insulation", popular: false, aliases: ["insulation install"] },
  { label: "Gutters", popular: false, aliases: ["gutter install", "gutter repair"] },
  { label: "Pressure Washing", popular: false, aliases: ["power washing", "pressure wash"] },
  { label: "Junk Removal", popular: false, aliases: ["hauling"] },
  { label: "Moving Help", popular: false, aliases: ["moving", "moving labor"] },
  { label: "Cleaning", popular: false, aliases: ["house cleaning", "cleaning services"] },
  { label: "Home Inspection", popular: false, aliases: ["inspection"] },
  { label: "Foundation Repair", popular: false, aliases: ["foundation", "foundation work"] },
  { label: "Water Damage Restoration", popular: false, aliases: ["water restoration", "water mitigation"] },
  { label: "Mold Remediation", popular: false, aliases: ["mold removal"] },
  { label: "Security Systems", popular: false, aliases: ["alarm systems", "security install"] },
  { label: "Smart Home", popular: false, aliases: ["home automation", "smart home install"] },
  { label: "Solar", popular: false, aliases: ["solar install", "pv install"] },
];

