# Generated by Django 5.2.13 on 2026-09-22 05:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_verified_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='duplicate_phone_risk',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_classification',
            field=models.CharField(choices=[('normal', 'Normal'), ('test', 'Test'), ('suspicious', 'Suspicious'), ('spam_fraud', 'Spam / fraud')], db_index=True, default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_continuation',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_role',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_state',
            field=models.CharField(choices=[('pending_email', 'Pending email'), ('pending_phone', 'Pending phone'), ('verified', 'Verified'), ('legacy_unverified', 'Legacy unverified'), ('suspicious', 'Suspicious'), ('disabled', 'Disabled')], db_index=True, default='legacy_unverified', max_length=24),
        ),
        migrations.CreateModel(
            name='AccountSecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_e164', models.CharField(db_index=True, max_length=32)),
                ('code_hash', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_verification_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
