# Generated by Django 5.2.1 on 2025-05-16 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='total_price',
            new_name='total_cost',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='amount_due',
        ),
        migrations.AddField(
            model_name='agreement',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.agreement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
