# Generated by Django 5.2 on 2025-04-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
