# Generated by Django 5.2 on 2025-04-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_contractor_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='escrow_funded',
            field=models.BooleanField(default=False),
        ),
    ]
