# Generated by Django 5.2.1 on 2025-05-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='agreement',
            name='contractor_signature',
            field=models.FileField(blank=True, help_text='Scanned signature or base64 PNG', null=True, upload_to='signatures/contractor/'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='homeowner_signature',
            field=models.FileField(blank=True, help_text='Scanned signature or base64 PNG', null=True, upload_to='signatures/homeowner/'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='agreements/pdf/'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_at_contractor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_at_homeowner',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_by_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_by_homeowner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='total_time_estimate',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='projects.contractor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='homeowner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='projects.homeowner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.agreement'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(blank=True, help_text='Anticipated completion date', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='homeowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.homeowner'),
        ),
        migrations.AlterUniqueTogether(
            name='milestone',
            unique_together={('agreement', 'order')},
        ),
    ]
