# Generated by Django 5.2 on 2025-05-01 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_agreement_escrow_funded'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='milestone_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='agreement',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='projects.project'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='auto_release_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pending_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(default='Milestone Payment', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.agreement'),
        ),
    ]
