# Generated by Django 5.2.1 on 2025-05-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_agreement_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='due_date',
            new_name='completion_date',
        ),
        migrations.AddField(
            model_name='agreement',
            name='escrow_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(blank=True, help_text='Anticipated start date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='number',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated project code', max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='contractor_signature',
            field=models.FileField(blank=True, help_text='Contractor signature image', null=True, upload_to='signatures/contractor/'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='homeowner_signature',
            field=models.FileField(blank=True, help_text='Homeowner signature image', null=True, upload_to='signatures/homeowner/'),
        ),
    ]
