# Generated by Django 5.2 on 2025-05-03 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_agreement_milestone_count_agreement_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('project_interest', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='milestone_count',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='title',
        ),
        migrations.AddField(
            model_name='agreement',
            name='contractor_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='dispute_resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='homeowner_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='liability_waiver',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='project_uid',
            field=models.CharField(default='temp-uid', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='total_duration_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.agreement')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='milestone',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='projects.milestone'),
        ),
    ]
