# Generated by Django 5.2 on 2025-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_lead_remove_agreement_milestone_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='milestone_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
