# Generated by Django 5.2.1 on 2025-05-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_due_date_milestone_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(editable=False, help_text='Auto-generated project code', max_length=30, unique=True),
        ),
    ]
