# Generated by Django 5.2 on 2025-05-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_agreement_milestone_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='homeowner_email',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='homeowner_name',
        ),
        migrations.AddField(
            model_name='agreement',
            name='homeowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.homeowner'),
        ),
    ]
