# Generated by Django 5.2.1 on 2025-05-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
