# Generated by Django 5.2.1 on 2025-05-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_milestone_days_milestone_hours_milestone_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='onboarding_status',
            field=models.CharField(blank=True, help_text='Stripe onboarding status (e.g. "incomplete", "completed")', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect Account ID', max_length=255, null=True),
        ),
    ]
