# Generated by Django 5.2.1 on 2025-07-18 21:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_contractor_onboarding_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="agreement",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="contractor",
            options={"ordering": ["business_name"]},
        ),
        migrations.AlterModelOptions(
            name="homeowner",
            options={"ordering": ["full_name"]},
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="homeowner",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="amount_due",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="agreement",
            name="homeowner",
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="name",
        ),
        migrations.RemoveField(
            model_name="homeowner",
            name="address",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="milestone",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="days",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="hours",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="minutes",
        ),
        migrations.AddField(
            model_name="agreement",
            name="addendum_file",
            field=models.FileField(
                blank=True, null=True, upload_to="agreements/addenda/"
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="amendment_number",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="agreement",
            name="contractor_signature_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="agreement",
            name="contractor_signed_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="homeowner_access_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="agreement",
            name="homeowner_signature_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="agreement",
            name="homeowner_signed_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="agreement",
            name="milestone_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agreement",
            name="pdf_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agreement",
            name="pdf_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="agreement",
            name="privacy_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="project_subtype",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agreement",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remodel", "Remodel"),
                    ("Repair", "Repair"),
                    ("Installation", "Installation"),
                    ("Painting", "Painting"),
                    ("Outdoor", "Outdoor"),
                    ("Inspection", "Inspection"),
                    ("Custom", "Custom"),
                    ("DIY Help", "DIY Help"),
                ],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agreement",
            name="signature_log",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="standardized_category",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agreement",
            name="terms_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="license_expiration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="license_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="contractor",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="terms_version",
            field=models.CharField(default="v1.0", max_length=20),
        ),
        migrations.AddField(
            model_name="homeowner",
            name="address_line_2",
            field=models.CharField(
                blank=True, help_text="e.g., Apt, Suite, Building", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="homeowner",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeowner",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeowners",
                to="projects.contractor",
            ),
        ),
        migrations.AddField(
            model_name="homeowner",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="homeowner",
            name="state",
            field=models.CharField(default="Unknown", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeowner",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("prospect", "Prospect"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="homeowner",
            name="street_address",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeowner",
            name="zip_code",
            field=models.CharField(default="Unknown", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="dispute_by",
            field=models.CharField(
                blank=True,
                choices=[("contractor", "Contractor"), ("homeowner", "Homeowner")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="dispute_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="disputed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="disputed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="escrow_released",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="escrow_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=32, unique=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="marked_complete_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="stripe_transfer_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="milestone",
            name="duration",
            field=models.DurationField(
                blank=True,
                help_text="Estimated time to complete the milestone.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="project_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="project_state",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="project_street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="project_zip_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="projects.contractor",
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="contractor_signature",
            field=models.FileField(
                blank=True, null=True, upload_to="signatures/contractor/"
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="escrow_payment_intent_id",
            field=models.CharField(blank=True, default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agreement",
            name="homeowner_signature",
            field=models.FileField(
                blank=True, null=True, upload_to="signatures/homeowner/"
            ),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="business_name",
            field=models.CharField(blank=True, default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contractor",
            name="onboarding_status",
            field=models.CharField(blank=True, default="Unknown", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contractor",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="skills",
        ),

        migrations.AlterField(
            model_name="homeowner",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),

        migrations.AlterField(
            model_name="invoice",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("incomplete", "Incomplete"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("disputed", "Disputed"),
                    ("paid", "Paid"),
                ],
                db_index=True,
                default="incomplete",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="milestone",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.contractor",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="homeowner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.homeowner",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="number",
            field=models.CharField(
                db_index=True, editable=False, max_length=30, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("signed", "Signed"),
                    ("funded", "Funded"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("incurred_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("disputed", "Disputed"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misc_expenses",
                        to="projects.agreement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-incurred_date"],
            },
        ),
        migrations.CreateModel(
            name="MilestoneComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.milestone",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MilestoneFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="milestone_uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.milestone",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.AddField(
            model_name="contractor",
            name="skills",
            field=models.ManyToManyField(blank=True, to="projects.skill"),
        ),
    ]
