# Generated by Django 5.2.1 on 2025-05-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_contractor_onboarding_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
