# Generated by Django 5.2.1 on 2025-05-31 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_homeowner_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='e.g. Permit Fee, Shipping, Extra Materials', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incurred_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_expenses', to='projects.agreement')),
                ('created_by', models.ForeignKey(help_text='Who logged this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-incurred_date'],
            },
        ),
    ]
