# Generated by Django 5.2.1 on 2025-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_skill_alter_agreement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="license_file",
            field=models.FileField(blank=True, null=True, upload_to="licenses/"),
        ),
        migrations.AddField(
            model_name="contractor",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
