# Generated by Django 5.2.1 on 2025-08-22 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_contractor_license_file_contractor_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractor",
            name="stripe_account_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contractor",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contractor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="agreement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="projects.agreement",
            ),
        ),
    ]
