# Generated by Django 5.2.1 on 2025-06-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='contractor_signature_name',
            field=models.CharField(blank=True, help_text='If contractor typed their name as signature', max_length=255),
        ),
        migrations.AddField(
            model_name='agreement',
            name='homeowner_signature_name',
            field=models.CharField(blank=True, help_text='If homeowner typed their name as signature', max_length=255),
        ),
    ]
