# Generated by Django 5.2.1 on 2025-09-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_alter_contractor_stripe_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="end",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="homeowner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agreements",
                to="projects.homeowner",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="start",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("signed", "Signed"),
                    ("funded", "Funded"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
