# Generated by Django 5.2.1 on 2025-06-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_agreement_contractor_signature_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='contractor_signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='homeowner_signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='contractor_signature',
            field=models.FileField(blank=True, help_text='Contractor signature image (optional)', null=True, upload_to='signatures/contractor/'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='contractor_signature_name',
            field=models.CharField(blank=True, help_text='The typed‐in name for contractor’s e‐signature', max_length=255),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='homeowner_signature',
            field=models.FileField(blank=True, help_text='Homeowner signature image (optional)', null=True, upload_to='signatures/homeowner/'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='homeowner_signature_name',
            field=models.CharField(blank=True, help_text='The typed‐in name for homeowner’s e‐signature', max_length=255),
        ),
    ]
