# Generated by Django 5.2.1 on 2025-06-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_agreement_contractor_signed_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='project_subtype',
            field=models.CharField(blank=True, help_text='Specific subtype (e.g. Kitchen, Fence, Electrical)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, help_text='Dropdown-selected category such as Permit Fee, Delivery, etc.', max_length=100, null=True),
        ),
    ]
