# Generated by Django 5.2.1 on 2025-06-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_agreement_project_subtype_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Remodel', 'Remodel'), ('Repair', 'Repair'), ('Installation', 'Installation'), ('Painting', 'Painting'), ('Outdoor', 'Outdoor'), ('Inspection', 'Inspection'), ('Custom', 'Custom'), ('DIY Help', 'DIY Help')], help_text='General category of project for milestone suggestions', max_length=100, null=True),
        ),
    ]
