# Generated by Django 5.2.1 on 2025-09-15 20:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_agreementamendment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="reviewed_by",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="warranty_text_snapshot",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="agreement",
            name="warranty_type",
            field=models.CharField(
                choices=[("default", "Default"), ("custom", "Custom")],
                default="default",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initiator",
                    models.CharField(
                        choices=[
                            ("contractor", "Contractor"),
                            ("homeowner", "Homeowner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated (fee not paid)"),
                            ("open", "Open (fee paid; under review)"),
                            ("under_review", "Under Review"),
                            ("resolved_contractor", "Resolved — Contractor"),
                            ("resolved_homeowner", "Resolved — Homeowner"),
                            ("canceled", "Canceled"),
                        ],
                        default="initiated",
                        max_length=30,
                    ),
                ),
                (
                    "fee_amount",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
                ),
                ("fee_paid", models.BooleanField(default=False)),
                ("fee_paid_at", models.DateTimeField(blank=True, null=True)),
                ("escrow_frozen", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="projects.agreement",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes",
                        to="projects.milestone",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("agreement", "Agreement"),
                            ("milestone", "Milestone"),
                            ("photo", "Photo"),
                            ("receipt", "Receipt"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="disputes/%Y/%m/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="projects.dispute",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
