# Generated by Django 5.2.1 on 2025-06-03 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_agreement_project_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='homeowner',
        ),
        migrations.AddField(
            model_name='agreement',
            name='milestone_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of milestones that were created at signing time'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='contractor_signature_name',
            field=models.CharField(blank=True, help_text="Typed contractor e-signature (e.g. 'John Smith')", max_length=255),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='escrow_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID (for escrow)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='homeowner_signature_name',
            field=models.CharField(blank=True, help_text="Typed homeowner e-signature (e.g. 'Jane Doe')", max_length=255),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Auto-generated PDF of this Agreement', null=True, upload_to='agreements/pdf/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text='If this is a bulk invoice not tied to a specific milestone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.agreement'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='If this is an invoice for a single milestone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.milestone'),
        ),
    ]
