# Generated by Django 5.2.1 on 2025-06-04 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_agreement_homeowner_agreement_milestone_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='contractor_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/contractor/'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='contractor_signature_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='escrow_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='homeowner_signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/homeowner/'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='homeowner_signature_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='milestone_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='agreements/pdf/'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='project_subtype',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Remodel', 'Remodel'), ('Repair', 'Repair'), ('Installation', 'Installation'), ('Painting', 'Painting'), ('Outdoor', 'Outdoor'), ('Inspection', 'Inspection'), ('Custom', 'Custom'), ('DIY Help', 'DIY Help')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.agreement'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='projects.milestone'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MilestoneFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='milestone_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.milestone')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
