# Generated by Django 5.2.1 on 2025-10-17 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_agreementattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="charges_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractor",
            name="details_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractor",
            name="payouts_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractor",
            name="requirements_due_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contractor",
            name="stripe_deauthorized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="stripe_status_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
