# Generated by Django 5.2.1 on 2025-10-18 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_contractor_charges_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("contractor", "Contractor"),
                            ("homeowner", "Homeowner"),
                        ],
                        max_length=20,
                    ),
                ),
                ("typed_name", models.CharField(blank=True, max_length=255)),
                ("image_base64", models.TextField(blank=True)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="projects.agreement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["agreement", "role"],
                        name="projects_ag_agreeme_e6d60b_idx",
                    )
                ],
                "unique_together": {("agreement", "role")},
            },
        ),
    ]
