# Generated by Django 5.2.8 on 2025-11-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_contractor_charges_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contractor",
            name="state",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
