# Generated by Django 5.2.1 on 2025-06-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_milestonecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='privacy_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='terms_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='onboarding_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
