# Generated by Django 5.2.8 on 2025-11-17 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_contractor_city_contractor_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorSubAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Name to show on the Employee Dashboard (e.g., 'Alex').",
                        max_length=255,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("employee_readonly", "Read-only employee"),
                            ("employee_milestones", "Milestones employee"),
                        ],
                        default="employee_readonly",
                        help_text="Controls whether employee can only view or also mark milestones complete.",
                        max_length=32,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft on/off switch for this sub-account.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional internal notes about this employee.",
                    ),
                ),
                (
                    "parent_contractor",
                    models.ForeignKey(
                        help_text="The primary Contractor this employee belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subaccounts",
                        to="projects.contractor",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The Django auth user for this employee.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contractor_subaccount",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contractor Sub-Account",
                "verbose_name_plural": "Contractor Sub-Accounts",
                "ordering": ("-created_at",),
            },
        ),
    ]
