# Generated by Django 5.2.1 on 2025-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_agreement_privacy_text_agreement_terms_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
