# Generated by Django 5.2.8 on 2025-11-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_contractorsubaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="project_address_city",
            field=models.CharField(
                blank=True, help_text="Project city.", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="project_address_line1",
            field=models.CharField(
                blank=True,
                help_text="Project street address (e.g., 5202 Texana Drive).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="project_address_line2",
            field=models.CharField(
                blank=True,
                help_text="Project address line 2 (e.g., Apt/Suite).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="project_address_state",
            field=models.CharField(
                blank=True,
                help_text="Project state / region.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="project_postal_code",
            field=models.CharField(
                blank=True,
                help_text="Project ZIP / postal code.",
                max_length=20,
                null=True,
            ),
        ),
    ]
