# Generated by Django 5.2.8 on 2025-11-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_agreement_project_address_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="insurance_file",
            field=models.FileField(blank=True, null=True, upload_to="insurance/"),
        ),
    ]
