# Generated by Django 5.2.8 on 2025-12-02 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_contractor_insurance_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementFundingLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Public token used in the /public-fund/:token URL.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Escrow amount the homeowner is asked to fund.",
                        max_digits=12,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="usd",
                        help_text="Currency code for the escrow funding amount.",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, token is considered invalid even if not expired.",
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe PaymentIntent id once we create it.",
                        max_length=255,
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_links",
                        to="projects.agreement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
