# Generated by Django 5.2.1 on 2025-06-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_contractor_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='project_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
