# Generated by Django 5.2.1 on 2025-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_homeowner_project_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='terms_version',
            field=models.CharField(default='v1.0', max_length=20),
        ),
    ]
