# Generated by Django 5.2.8 on 2025-12-13 01:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_agreementfundinglink"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="escrow_funded_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total amount funded into escrow so far.",
                max_digits=10,
            ),
        ),
    ]
