# Generated by Django 5.2.1 on 2025-06-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_homeowner_terms_accepted_at_homeowner_terms_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
