# Generated by Django 5.2.8 on 2025-12-15 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_agreement_escrow_funded_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreementfundinglink",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="agreementfundinglink",
            name="payment_intent_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="contractorsubaccount",
            name="display_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contractorsubaccount",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="contractorsubaccount",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="contractorsubaccount",
            name="parent_contractor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subaccounts",
                to="projects.contractor",
            ),
        ),
        migrations.AlterField(
            model_name="contractorsubaccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee_readonly", "Read-only employee"),
                    ("employee_milestones", "Milestones employee"),
                ],
                default="employee_readonly",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="contractorsubaccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contractor_subaccount",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_invoiced", False), ("completed", True), _connector="OR"
                ),
                name="milestone_invoiced_requires_completed",
            ),
        ),
    ]
