# Generated by Django 5.2.8 on 2025-12-16 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_alter_agreementfundinglink_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="invoice",
            field=models.OneToOneField(
                blank=True,
                help_text="Invoice created from this milestone (idempotent link).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_milestone",
                to="projects.invoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="milestone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("invoice__isnull", True),
                    models.Q(("completed", True), ("is_invoiced", True)),
                    _connector="OR",
                ),
                name="milestone_invoice_requires_completed_and_flag",
            ),
        ),
    ]
