# Generated by Django 5.2.1 on 2025-06-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_contractor_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='pdf_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='pdf_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signature_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
