# Generated by Django 5.2.8 on 2025-12-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_milestone_invoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_message_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_email_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="invoices/pdf/"),
        ),
    ]
