# Generated by Django 5.2.1 on 2025-06-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_agreement_pdf_archived_agreement_pdf_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
