# Generated by Django 5.2.8 on 2025-12-17 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_invoice_email_message_id_invoice_email_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="milestone_attachments_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="invoice",
            name="milestone_completion_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="milestone_description_snapshot",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="milestone_id_snapshot",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="milestone_title_snapshot",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
