# Generated by Django 5.2.1 on 2025-06-07 06:37
from uuid import uuid4
from django.db import migrations, models

def gen_tokens(apps, schema_editor):
    Agreement = apps.get_model('projects', 'Agreement')
    for ag in Agreement.objects.all():
        ag.homeowner_access_token = uuid4()
        ag.save(update_fields=['homeowner_access_token'])

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_agreement_reviewed'),  # keep your last migration here
    ]

    operations = [
        # 1) add the field without unique constraint
        migrations.AddField(
            model_name='agreement',
            name='homeowner_access_token',
            field=models.UUIDField(default=uuid4, editable=False),
        ),
        # 2) backfill existing rows with distinct values
        migrations.RunPython(gen_tokens, reverse_code=migrations.RunPython.noop),
        # 3) finally enforce unique=True
        migrations.AlterField(
            model_name='agreement',
            name='homeowner_access_token',
            field=models.UUIDField(default=uuid4, editable=False, unique=True),
        ),
    ]
