# Generated by Django 5.2.8 on 2025-12-24 07:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_invoice_milestone_attachments_snapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="public_token",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="Public magic token for homeowner invoice access",
            ),
        ),
    ]
