# Generated by Django 5.2.8 on 2025-12-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_alter_invoice_public_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payout_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invoice",
            name="platform_fee_cents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
