# Generated by Django 5.2.8 on 2026-01-03 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_invoice_payout_cents_invoice_platform_fee_cents"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilestoneAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "milestone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subaccount_assignment",
                        to="projects.milestone",
                    ),
                ),
                (
                    "subaccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_assignments",
                        to="projects.contractorsubaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgreementAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subaccount_assignments",
                        to="projects.agreement",
                    ),
                ),
                (
                    "subaccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_assignments",
                        to="projects.contractorsubaccount",
                    ),
                ),
            ],
            options={
                "unique_together": {("agreement", "subaccount")},
            },
        ),
    ]
