# Generated by Django 5.2.8 on 2026-01-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_milestoneassignment_agreementassignment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractorsubaccount",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee_readonly", "Read-only employee"),
                    ("employee_milestones", "Milestones employee"),
                    ("employee_supervisor", "Supervisor / Foreman"),
                ],
                default="employee_readonly",
                max_length=32,
            ),
        ),
    ]
