# Generated by Django 5.2.8 on 2026-01-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_alter_contractorsubaccount_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeWorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(default="America/Chicago", max_length=64),
                ),
                ("work_sun", models.BooleanField(default=False)),
                ("work_mon", models.BooleanField(default=True)),
                ("work_tue", models.BooleanField(default=True)),
                ("work_wed", models.BooleanField(default=True)),
                ("work_thu", models.BooleanField(default=True)),
                ("work_fri", models.BooleanField(default=True)),
                ("work_sat", models.BooleanField(default=False)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subaccount",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedule",
                        to="projects.contractorsubaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Work Schedule",
                "verbose_name_plural": "Employee Work Schedules",
            },
        ),
        migrations.CreateModel(
            name="EmployeeScheduleException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("is_working", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subaccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to="projects.contractorsubaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Schedule Exception",
                "verbose_name_plural": "Employee Schedule Exceptions",
                "ordering": ("-date",),
                "unique_together": {("subaccount", "date")},
            },
        ),
    ]
