# Generated by Django 5.2.8 on 2026-01-06 03:55

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_employeeworkschedule_employeescheduleexception"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, default="", max_length=80)),
                ("last_name", models.CharField(blank=True, default="", max_length=80)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "home_address_line1",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "home_address_line2",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("home_city", models.CharField(blank=True, default="", max_length=120)),
                ("home_state", models.CharField(blank=True, default="", max_length=60)),
                (
                    "home_postal_code",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "drivers_license_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "drivers_license_state",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("drivers_license_expiration", models.DateField(blank=True, null=True)),
                (
                    "drivers_license_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.employee_profile_upload_to,
                    ),
                ),
                (
                    "professional_license_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "professional_license_number",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "professional_license_expiration",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "professional_license_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.employee_profile_upload_to,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.employee_profile_upload_to,
                    ),
                ),
                ("assigned_work_schedule", models.TextField(blank=True, default="")),
                ("day_off_requests", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subaccount",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to="projects.contractorsubaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
