# Generated by Django 5.2.8 on 2026-01-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_employeeprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="completed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
