# Generated by Django 5.2.8 on 2026-01-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_milestone_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="admin_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dispute",
            name="contractor_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dispute",
            name="homeowner_response",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="dispute",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
