# Generated by Django 5.2.8 on 2026-01-15 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_dispute_admin_notes_dispute_contractor_response_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispute",
            options={},
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="fee_paid_at",
        ),
        migrations.RemoveField(
            model_name="dispute",
            name="responded_at",
        ),
        migrations.AddField(
            model_name="dispute",
            name="proposal",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="proposal_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispute",
            name="public_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="initiator",
            field=models.CharField(
                choices=[
                    ("contractor", "Contractor"),
                    ("homeowner", "Homeowner"),
                    ("admin", "Admin"),
                    ("system", "System"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("open", "Open"),
                    ("under_review", "Under Review"),
                    ("resolved_contractor", "Resolved - Contractor"),
                    ("resolved_homeowner", "Resolved - Homeowner"),
                    ("canceled", "Canceled"),
                ],
                default="initiated",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="dispute",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
