# Generated by Django 5.2.8 on 2026-01-16 05:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0037_dispute_created_by_dispute_deadline_hours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("response_24h", "Response due in 24h"),
                            ("proposal_24h", "Proposal decision due in 24h"),
                            ("response_overdue", "Response overdue"),
                            ("proposal_overdue", "Proposal overdue"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="projects.dispute",
                    ),
                ),
            ],
            options={
                "unique_together": {("dispute", "kind")},
            },
        ),
    ]
