# Generated by Django 5.2.8 on 2026-01-19 05:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0039_disputeworkorder_delete_disputereminderlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        default="response_due",
                        help_text="response_due, proposal_due, escalation, etc.",
                        max_length=32,
                    ),
                ),
                (
                    "sent_to",
                    models.CharField(
                        help_text="homeowner / contractor / admin", max_length=32
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_logs",
                        to="projects.dispute",
                    ),
                ),
            ],
        ),
    ]
