# Generated by Django 5.2.8 on 2026-01-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0040_disputereminderlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="disputeworkorder",
            name="rework_milestone_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
