# Generated by ChatGPT on 2026-01-19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0041_disputeworkorder_rework_milestone_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="rework_origin_milestone_id",
            field=models.IntegerField(
                null=True,
                blank=True,
                db_index=True,
                help_text=(
                    "Original milestone id that this rework milestone corrects "
                    "(the milestone referenced by the dispute)."
                ),
            ),
        ),
    ]
