# Generated by Django 5.2.8 on 2026-01-22 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0042_milestone_rework_origin_milestone_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisputeAIArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("recommendation", "Recommendation"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("input_digest", models.CharField(db_index=True, max_length=64)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid", models.BooleanField(default=False)),
                ("price_cents", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispute_ai_artifacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_artifacts",
                        to="projects.dispute",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["dispute", "artifact_type", "input_digest"],
                        name="projects_di_dispute_a5ea2c_idx",
                    ),
                    models.Index(
                        fields=["dispute", "artifact_type", "version"],
                        name="projects_di_dispute_2684a6_idx",
                    ),
                ],
            },
        ),
    ]
