# Generated by Django 5.2.8 on 2026-01-22 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0043_disputeaiartifact"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorAIEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                        ],
                        db_index=True,
                        default="free",
                        max_length=24,
                    ),
                ),
                (
                    "free_recommendations_remaining",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "monthly_recommendations_included",
                    models.PositiveIntegerField(default=2),
                ),
                (
                    "monthly_recommendations_used",
                    models.PositiveIntegerField(default=0),
                ),
                ("quota_period_start", models.DateTimeField(blank=True, null=True)),
                ("quota_period_end", models.DateTimeField(blank=True, null=True)),
                ("allow_ai_summaries", models.BooleanField(default=True)),
                ("allow_ai_recommendations", models.BooleanField(default=True)),
                ("allow_scope_assistant", models.BooleanField(default=False)),
                ("allow_resolution_agreement", models.BooleanField(default=False)),
                ("allow_business_insights", models.BooleanField(default=False)),
                ("subscription_active", models.BooleanField(default=False)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_entitlement",
                        to="projects.contractor",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
