# Generated by Django 5.2.8 on 2026-01-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0046_agreement_ai_scope"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreementaiscope",
            options={
                "verbose_name": "Agreement AI Scope",
                "verbose_name_plural": "Agreement AI Scopes",
            },
        ),
    ]
