# Generated by Django 5.2.8 on 2026-02-09 18:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0047_alter_agreementaiscope_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("homeowner_name", models.CharField(max_length=255)),
                ("homeowner_email", models.EmailField(db_index=True, max_length=254)),
                ("homeowner_phone", models.CharField(blank=True, max_length=20)),
                ("contractor_email", models.EmailField(blank=True, max_length=254)),
                ("contractor_phone", models.CharField(blank=True, max_length=20)),
                ("message", models.TextField(blank=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="homeowner",
            name="email",
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddConstraint(
            model_name="homeowner",
            constraint=models.UniqueConstraint(
                fields=("created_by", "email"),
                name="uniq_homeowner_email_per_contractor",
            ),
        ),
        migrations.AddField(
            model_name="contractorinvite",
            name="accepted_by_contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_invites",
                to="projects.contractor",
            ),
        ),
    ]
