# Generated by Django 5.2.8 on 2026-02-09 22:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0048_contractorinvite_alter_homeowner_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractorinvite",
            name="last_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractorinvite",
            name="resend_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name="contractorinvite",
            name="send_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
