# Generated by Django 5.2.8 on 2026-02-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0050_fill_resend_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("escrow", "Escrow (Protected)"),
                    ("direct", "Direct Pay (Fast)"),
                ],
                db_index=True,
                default="escrow",
                help_text="ESCROW uses protected funding/release. DIRECT uses pay-now invoices to contractor Stripe.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="direct_pay_checkout_session_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="direct_pay_checkout_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="invoice",
            name="direct_pay_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="direct_pay_payment_intent_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("incomplete", "Incomplete"),
                    ("sent", "Sent (Awaiting Payment)"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("disputed", "Disputed"),
                    ("paid", "Paid"),
                ],
                db_index=True,
                default="incomplete",
                max_length=20,
            ),
        ),
    ]
