# Generated by Django 5.2.8 on 2026-02-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0051_agreement_payment_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeowner",
            name="company_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional company name for subcontractor / GC customers.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homeowner",
            name="address_line_2",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g., Apt, Suite, Building",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="homeowner",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="homeowner",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="homeowner",
            name="state",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="homeowner",
            name="street_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="homeowner",
            name="zip_code",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
