# Generated by Django 5.2.8 on 2026-02-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0053_billing_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="project_subtype",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
