# Generated by Django 5.2.8 on 2026-02-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0054_alter_agreement_project_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Remodel", "Remodel"),
                    ("New Construction", "New Construction"),
                    ("Repair", "Repair"),
                    ("HVAC", "HVAC"),
                    ("Roofing", "Roofing"),
                    ("Electrical", "Electrical"),
                    ("Plumbing", "Plumbing"),
                    ("Landscaping", "Landscaping"),
                    ("Painting", "Painting"),
                    ("Flooring", "Flooring"),
                    ("Installation", "Installation"),
                    ("Outdoor", "Outdoor"),
                    ("Inspection", "Inspection"),
                    ("DIY Help", "DIY Help"),
                    ("Custom", "Custom"),
                ],
                max_length=100,
            ),
        ),
    ]
