# Generated by Django 5.2.8 on 2026-02-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0055_alter_agreement_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="ai_free_agreements_total",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="contractor",
            name="ai_free_agreements_used",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
