# Generated by Django 5.2.8 on 2026-02-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0056_contractor_ai_free_agreements_total_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractoraientitlement",
            name="allow_agreement_writer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contractoraientitlement",
            name="free_agreements_remaining",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="contractoraientitlement",
            name="monthly_agreements_included",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contractoraientitlement",
            name="monthly_agreements_used",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
