# Generated by Django 5.2.8 on 2026-02-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0058_ai_agreement_usage_ledger"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIAgreementUsage",
        ),
    ]
