# Generated by Django 5.2.8 on 2026-02-20 03:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0061_expenserequest_expenserequestattachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenserequest",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
