# Generated by Django 5.2.8 on 2026-02-20 22:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0063_expenserequest_archive_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AmendmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("date_change", "Date Change"),
                            ("amount_change", "Amount Change"),
                            ("scope_product_change", "Product/Scope Change"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=64,
                    ),
                ),
                ("requested_changes", models.JSONField(blank=True, default=dict)),
                ("justification", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("routed_to_amendment", "Routed to Amendment"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=64,
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendment_requests",
                        to="projects.agreement",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. Some amendment requests may be agreement-level.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendment_requests",
                        to="projects.milestone",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
