# Generated by Django 5.2.8 on 2026-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0064_amendmentrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="zip",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
