# Generated by Django 5.2.8 on 2026-02-23 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0065_contractor_zip"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="external_contract_attested",
            field=models.BooleanField(
                default=False,
                help_text="Contractor attests external agreement exists (used with EXTERNAL_SIGNED policy).",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="external_contract_attested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="external_contract_attested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="external_contract_attestations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="external_contract_file",
            field=models.FileField(
                blank=True,
                help_text="Optional: upload external signed agreement/work order.",
                null=True,
                upload_to="agreements/external_contracts/",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="external_contract_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional: external contract / PO / work order reference number.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="signature_policy",
            field=models.CharField(
                choices=[
                    ("both_required", "Both Parties Sign (Recommended)"),
                    ("contractor_only", "Contractor Only (Work Order / Internal)"),
                    (
                        "external_signed",
                        "Signed Outside MyHomeBro (Upload/Reference/Attest)",
                    ),
                ],
                db_index=True,
                default="both_required",
                help_text="Controls signature requirements: both parties, contractor-only, or signed externally.",
                max_length=32,
            ),
        ),
    ]
