# Generated by Django 5.2.8 on 2026-03-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0067_agreement_contractor_ack_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="require_contractor_signature",
            field=models.BooleanField(
                default=True,
                help_text="If False, contractor signature is waived and treated as satisfied.",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="require_customer_signature",
            field=models.BooleanField(
                default=True,
                help_text="If False, customer signature is waived and treated as satisfied.",
            ),
        ),
    ]
