# Generated by Django 5.2.8 on 2026-03-03 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0068_agreement_require_contractor_signature_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementPDFVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("preview", "Preview"),
                            ("final", "Final"),
                            ("executed", "Executed"),
                        ],
                        db_index=True,
                        default="final",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="agreements/pdf_versions/"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("signed_by_contractor", models.BooleanField(default=False)),
                ("signed_by_homeowner", models.BooleanField(default=False)),
                (
                    "contractor_signature_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "homeowner_signature_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("contractor_signed_at", models.DateTimeField(blank=True, null=True)),
                ("homeowner_signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_versions",
                        to="projects.agreement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "unique_together": {("agreement", "version_number")},
            },
        ),
    ]
