# Generated by Django 5.2.8 on 2026-03-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0069_agreementpdfversion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractoraientitlement",
            options={},
        ),
        migrations.RemoveField(
            model_name="contractoraientitlement",
            name="allow_agreement_writer",
        ),
        migrations.RemoveField(
            model_name="contractoraientitlement",
            name="contractor",
        ),
        migrations.RemoveField(
            model_name="contractoraientitlement",
            name="current_period_end",
        ),
        migrations.RemoveField(
            model_name="contractoraientitlement",
            name="free_agreements_remaining",
        ),
        migrations.RemoveField(
            model_name="contractoraientitlement",
            name="monthly_agreements_included",
        ),
        migrations.RemoveField(
            model_name="contractoraientitlement",
            name="monthly_agreements_used",
        ),
        migrations.RemoveField(
            model_name="contractoraientitlement",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="contractoraientitlement",
            name="stripe_subscription_id",
        ),
        migrations.AddField(
            model_name="contractoraientitlement",
            name="contractor_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="contractoraientitlement",
            name="free_scope_credits_remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contractoraientitlement",
            name="monthly_scope_credits_included",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contractoraientitlement",
            name="monthly_scope_credits_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="contractoraientitlement",
            name="scope_quota_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractoraientitlement",
            name="scope_quota_period_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractoraientitlement",
            name="scope_unlimited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contractoraientitlement",
            name="allow_ai_recommendations",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contractoraientitlement",
            name="allow_ai_summaries",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contractoraientitlement",
            name="free_recommendations_remaining",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contractoraientitlement",
            name="monthly_recommendations_included",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contractoraientitlement",
            name="monthly_recommendations_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="contractoraientitlement",
            name="tier",
            field=models.CharField(default="free", max_length=64),
        ),
    ]
