# Generated by Django 5.2.8 on 2026-03-04 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0070_alter_contractoraientitlement_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAgreementUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreement_id", models.PositiveIntegerField(db_index=True)),
                (
                    "feature_key",
                    models.CharField(
                        choices=[("agreement_bundle", "Agreement AI Bundle")],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_agreement_usages",
                        to="projects.contractor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contractor", "agreement_id", "feature_key"),
                        name="uniq_ai_usage_contractor_agreement_feature",
                    )
                ],
            },
        ),
    ]
