# Generated by Django 5.2.8 on 2026-03-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0071_aiagreementusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
