# Generated by Django 5.2.8 on 2026-03-06 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0072_invoice_stripe_payment_intent_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "project_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "project_subtype",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("estimated_days", models.PositiveIntegerField(default=1)),
                ("default_scope", models.TextField(blank=True, default="")),
                ("default_clarifications", models.JSONField(blank=True, default=list)),
                ("is_system", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_templates",
                        to="projects.contractor",
                    ),
                ),
                (
                    "created_from_agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_templates",
                        to="projects.agreement",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_system", "project_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplateMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveIntegerField(default=1)),
                (
                    "recommended_days_from_start",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional relative day offset from agreement start.",
                        null=True,
                    ),
                ),
                (
                    "recommended_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional duration hint for scheduling logic.",
                        null=True,
                    ),
                ),
                (
                    "suggested_amount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional % of agreement total for this milestone.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "suggested_amount_fixed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional fixed amount for this milestone.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("materials_hint", models.TextField(blank=True, default="")),
                ("is_optional", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.projecttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(
                fields=["project_type", "project_subtype"],
                name="projects_pr_project_9b9433_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projecttemplate",
            index=models.Index(
                fields=["is_system", "is_active"], name="projects_pr_is_syst_ebc5d0_idx"
            ),
        ),
    ]
