# Generated by Django 5.2.8 on 2026-03-06 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0073_projecttemplate_projecttemplatemilestone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="selected_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template used to generate the current agreement milestones.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_agreements",
                to="projects.projecttemplate",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="selected_template_name_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Snapshot of template name at time of apply, for audit/history.",
                max_length=255,
            ),
        ),
    ]
