# Generated by Django 5.2.8 on 2026-03-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0074_agreement_selected_template_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "initiated_by",
                    models.CharField(
                        choices=[
                            ("contractor", "Contractor"),
                            ("homeowner", "Homeowner"),
                        ],
                        default="contractor",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("analyzed", "Analyzed"),
                            ("converted", "Converted to Agreement"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "customer_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "customer_address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "customer_address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "customer_city",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "customer_state",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "customer_postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("same_as_customer_address", models.BooleanField(default=True)),
                (
                    "project_address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "project_address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "project_city",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "project_state",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "project_postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("accomplishment_text", models.TextField(blank=True, default="")),
                (
                    "ai_project_title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "ai_project_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "ai_project_subtype",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("ai_description", models.TextField(blank=True, default="")),
                (
                    "ai_recommended_template_id",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "ai_recommendation_confidence",
                    models.CharField(blank=True, default="none", max_length=20),
                ),
                ("ai_recommendation_reason", models.TextField(blank=True, default="")),
                ("ai_milestones", models.JSONField(blank=True, default=list)),
                (
                    "ai_clarification_questions",
                    models.JSONField(blank=True, default=list),
                ),
                ("ai_analysis_payload", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_intakes",
                        to="projects.agreement",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_intakes",
                        to="projects.contractor",
                    ),
                ),
                (
                    "homeowner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_intakes",
                        to="projects.homeowner",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
