# Generated by Django 5.2.8 on 2026-03-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0075_projectintake"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectintake",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project Intake",
                "verbose_name_plural": "Project Intakes",
            },
        ),
    ]
