# Generated by Django 5.2.8 on 2026-03-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0076_alter_projectintake_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectintake",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectintake",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectintake",
            name="sent_to_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="projectintake",
            name="share_token",
            field=models.CharField(blank=True, default="", max_length=64, unique=True),
        ),
    ]
