# Generated by Django 5.2.8 on 2026-03-11 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0077_projectintake_completed_at_projectintake_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="project_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="ProjectSubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=120),
                ),
                ("is_system", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_subtypes",
                        to="projects.contractor",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_project_subtypes",
                        to="projects.projectsubtype",
                    ),
                ),
            ],
            options={
                "ordering": ["project_type__sort_order", "sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="agreement",
            name="project_subtype_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agreements",
                to="projects.projectsubtype",
            ),
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "normalized_name",
                    models.CharField(db_index=True, editable=False, max_length=120),
                ),
                ("is_system", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_types",
                        to="projects.contractor",
                    ),
                ),
                (
                    "merged_into",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="merged_project_types",
                        to="projects.projecttype",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="projectsubtype",
            name="project_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtypes",
                to="projects.projecttype",
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="project_type_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agreements",
                to="projects.projecttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="projecttype",
            constraint=models.UniqueConstraint(
                fields=("contractor", "normalized_name"),
                name="uniq_project_type_per_contractor_normalized_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectsubtype",
            constraint=models.UniqueConstraint(
                fields=("project_type", "contractor", "normalized_name"),
                name="uniq_project_subtype_per_type_per_contractor_normalized_name",
            ),
        ),
    ]
