# Generated by Django 5.2.8 on 2026-03-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0078_alter_agreement_project_type_projectsubtype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketPricingBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_state",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "region_city",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "project_subtype",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "normalized_milestone_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "low_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "median_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "high_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "typical_days_from_start",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "typical_duration_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "typical_total_project_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "source_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "project_type",
                    "project_subtype",
                    "normalized_milestone_type",
                    "region_state",
                    "region_city",
                ],
            },
        ),
        migrations.CreateModel(
            name="PricingObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_state",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "region_city",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "project_subtype",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "normalized_milestone_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "milestone_title_snapshot",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "milestone_description_snapshot",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "agreement_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("estimated_days", models.PositiveIntegerField(default=0)),
                (
                    "milestone_days_from_start",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "milestone_duration_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-paid_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PricingStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("market", "Market"),
                            ("platform", "Platform"),
                            ("contractor", "Contractor"),
                        ],
                        db_index=True,
                        default="market",
                        max_length=32,
                    ),
                ),
                (
                    "region_state",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "region_city",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "project_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "project_subtype",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "normalized_milestone_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                ("sample_size", models.PositiveIntegerField(default=0)),
                (
                    "low_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "median_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "high_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "avg_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "avg_days_from_start",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "avg_duration_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "avg_total_project_days",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "source_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": [
                    "scope",
                    "project_type",
                    "project_subtype",
                    "normalized_milestone_type",
                ],
            },
        ),
        migrations.AddField(
            model_name="projecttemplatemilestone",
            name="normalized_milestone_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Stable normalized category used for pricing analytics.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="projecttemplatemilestone",
            name="pricing_confidence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unknown"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                default="",
                help_text="Confidence level for current pricing guidance.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="projecttemplatemilestone",
            name="pricing_source_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Short note about where the suggested pricing came from.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="projecttemplatemilestone",
            name="suggested_amount_high",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional high-end suggested price range for this milestone.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projecttemplatemilestone",
            name="suggested_amount_low",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional low-end suggested price range for this milestone.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="projecttemplatemilestone",
            index=models.Index(
                fields=["template", "sort_order"], name="projects_pr_templat_d2c129_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projecttemplatemilestone",
            index=models.Index(
                fields=["normalized_milestone_type"],
                name="projects_pr_normali_06e635_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketpricingbaseline",
            index=models.Index(
                fields=["project_type", "project_subtype"],
                name="projects_ma_project_5a7125_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketpricingbaseline",
            index=models.Index(
                fields=["normalized_milestone_type"],
                name="projects_ma_normali_230186_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketpricingbaseline",
            index=models.Index(
                fields=["region_state", "region_city"],
                name="projects_ma_region__a598d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketpricingbaseline",
            index=models.Index(
                fields=["is_active"], name="projects_ma_is_acti_2b5cae_idx"
            ),
        ),
        migrations.AddField(
            model_name="pricingobservation",
            name="agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing_observations",
                to="projects.agreement",
            ),
        ),
        migrations.AddField(
            model_name="pricingobservation",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing_observations",
                to="projects.contractor",
            ),
        ),
        migrations.AddField(
            model_name="pricingobservation",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing_observations",
                to="projects.milestone",
            ),
        ),
        migrations.AddField(
            model_name="pricingstatistic",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pricing_statistics",
                to="projects.contractor",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingobservation",
            index=models.Index(
                fields=["project_type", "project_subtype"],
                name="projects_pr_project_dd1456_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingobservation",
            index=models.Index(
                fields=["normalized_milestone_type"],
                name="projects_pr_normali_1a109f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingobservation",
            index=models.Index(
                fields=["region_state", "region_city"],
                name="projects_pr_region__404b38_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingobservation",
            index=models.Index(
                fields=["contractor"], name="projects_pr_contrac_e8b854_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingobservation",
            index=models.Index(
                fields=["paid_at"], name="projects_pr_paid_at_d46d0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricingstatistic",
            index=models.Index(
                fields=["scope", "project_type", "project_subtype"],
                name="projects_pr_scope_a16a26_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingstatistic",
            index=models.Index(
                fields=["scope", "normalized_milestone_type"],
                name="projects_pr_scope_73c86f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingstatistic",
            index=models.Index(
                fields=["scope", "region_state", "region_city"],
                name="projects_pr_scope_551b8a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pricingstatistic",
            index=models.Index(
                fields=["contractor"], name="projects_pr_contrac_00ceba_idx"
            ),
        ),
    ]
