# Generated by Django 5.2.8 on 2026-03-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0080_milestone_estimate_assist_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["normalized_milestone_type"],
                name="projects_mi_normali_009904_idx",
            ),
        ),
    ]
