# Generated by Django 5.2.8 on 2026-03-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0081_milestone_projects_mi_normali_009904_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttemplate",
            name="project_materials_hint",
            field=models.TextField(blank=True, default=""),
        ),
    ]
