# Generated by Django 5.2.1 on 2026-03-23 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0091_milestone_delegated_reviewer_subaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="subcontractor_payout_amount_cents",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional subcontractor payout amount in cents for this milestone. Defaults to the milestone amount in V1.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="MilestonePayout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount_cents", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_eligible", "Not Eligible"),
                            ("eligible", "Eligible"),
                            ("ready_for_payout", "Ready for Payout"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="not_eligible",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eligible_at", models.DateTimeField(blank=True, null=True)),
                ("ready_for_payout_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("stripe_transfer_id", models.CharField(blank=True, default="", max_length=255)),
                ("failure_reason", models.TextField(blank=True, default="")),
                (
                    "milestone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_record",
                        to="projects.milestone",
                    ),
                ),
                (
                    "subcontractor_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
