# Generated by Django 5.2.1 on 2026-03-25 13:35

import projects.models_subcontractor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_auto_payout_settings_and_execution_mode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractorAIEntitlement',
        ),
        migrations.RenameIndex(
            model_name='subcontractorinvitation',
            new_name='projects_su_agreeme_040b0b_idx',
            old_name='projects_su_agreeme_32a875_idx',
        ),
        migrations.RenameIndex(
            model_name='subcontractorinvitation',
            new_name='projects_su_agreeme_c7abc3_idx',
            old_name='projects_su_agreeme_ec265b_idx',
        ),
        migrations.AlterField(
            model_name='subcontractorinvitation',
            name='expires_at',
            field=models.DateTimeField(default=projects.models_subcontractor._default_subcontractor_invitation_expiry),
        ),
        migrations.AlterField(
            model_name='subcontractorinvitation',
            name='token',
            field=models.CharField(db_index=True, default=projects.models_subcontractor._default_subcontractor_invitation_token, editable=False, max_length=96, unique=True),
        ),
        migrations.DeleteModel(
            name='AIAgreementUsage',
        ),
        migrations.DeleteModel(
            name='ContractorBillingProfile',
        ),
        migrations.DeleteModel(
            name='DisputeAIPurchase',
        ),
    ]
