# Generated by Django 5.2.1 on 2026-03-26 01:14

import django.db.models.deletion
import django.utils.timezone
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_progress_payment_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorPublicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=64, unique=True)),
                ('business_name_public', models.CharField(blank=True, default='', max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=255)),
                ('bio', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=projects.models.contractor_public_asset_upload_to)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=projects.models.contractor_public_asset_upload_to)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=60)),
                ('service_area_text', models.CharField(blank=True, default='', max_length=255)),
                ('years_in_business', models.PositiveIntegerField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, default='')),
                ('phone_public', models.CharField(blank=True, default='', max_length=40)),
                ('email_public', models.EmailField(blank=True, default='', max_length=254)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('work_types', models.JSONField(blank=True, default=list)),
                ('show_license_public', models.BooleanField(default=True)),
                ('show_phone_public', models.BooleanField(default=True)),
                ('show_email_public', models.BooleanField(default=False)),
                ('allow_public_intake', models.BooleanField(default=True)),
                ('allow_public_reviews', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='projects.contractor')),
            ],
            options={
                'ordering': ['contractor_id'],
            },
        ),
        migrations.CreateModel(
            name='ContractorGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('image', models.ImageField(upload_to=projects.models.contractor_public_asset_upload_to)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('project_city', models.CharField(blank=True, default='', max_length=120)),
                ('project_state', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_gallery_items', to='projects.contractor')),
                ('public_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='projects.contractorpublicprofile')),
            ],
            options={
                'ordering': ['-is_featured', 'sort_order', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContractorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('review_text', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_reviews', to='projects.agreement')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_reviews', to='projects.contractor')),
                ('public_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.contractorpublicprofile')),
            ],
            options={
                'ordering': ['-is_verified', '-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicContractorLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('profile', 'Profile'), ('qr', 'QR'), ('direct', 'Direct')], default='profile', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('project_address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=60)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('project_type', models.CharField(blank=True, default='', max_length=120)),
                ('project_description', models.TextField(blank=True, default='')),
                ('preferred_timeline', models.CharField(blank=True, default='', max_length=120)),
                ('budget_text', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('archived', 'Archived')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_leads', to='projects.contractor')),
                ('public_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='projects.contractorpublicprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
