# Generated by Django 5.2.1 on 2026-03-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_unify_public_intake_lead_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectintake',
            name='lead_source',
            field=models.CharField(choices=[('landing_page', 'Landing Page'), ('public_profile', 'Public Profile'), ('qr', 'QR'), ('contractor_sent_form', 'Contractor Sent Form'), ('direct', 'Direct')], default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='publiccontractorlead',
            name='source',
            field=models.CharField(choices=[('landing_page', 'Landing Page'), ('public_profile', 'Public Profile'), ('qr', 'QR'), ('contractor_sent_form', 'Contractor Sent Form'), ('direct', 'Direct')], default='public_profile', max_length=20),
        ),
        migrations.AlterField(
            model_name='publiccontractorlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('pending_customer_response', 'Pending Customer Response'), ('ready_for_review', 'Ready for Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed'), ('archived', 'Archived')], default='new', max_length=32),
        ),
    ]
