# Generated by Django 5.2.1 on 2026-03-26 21:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0102_manual_public_lead_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementOutcomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('project_subtype', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='US', max_length=8)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('normalized_region_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('payment_mode', models.CharField(blank=True, default='', max_length=20)),
                ('signature_policy', models.CharField(blank=True, default='', max_length=32)),
                ('estimated_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_agreed_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('retainage_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('retainage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('agreement_start_date', models.DateField(blank=True, null=True)),
                ('agreement_target_end_date', models.DateField(blank=True, null=True)),
                ('agreement_completed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('estimated_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('milestone_count', models.PositiveIntegerField(default=0)),
                ('milestone_summary', models.JSONField(blank=True, default=dict)),
                ('clarification_summary', models.JSONField(blank=True, default=dict)),
                ('has_amendments', models.BooleanField(default=False)),
                ('amendment_count', models.PositiveIntegerField(default=0)),
                ('has_disputes', models.BooleanField(default=False)),
                ('dispute_count', models.PositiveIntegerField(default=0)),
                ('excluded_from_benchmarks', models.BooleanField(db_index=True, default=False)),
                ('exclusion_reason', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot_version', models.PositiveIntegerField(default=1)),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_snapshot', to='projects.agreement')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_snapshots', to='projects.contractor')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_snapshots', to='projects.projecttemplate')),
            ],
            options={
                'ordering': ['-agreement_completed_date', '-snapshot_updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AgreementOutcomeMilestoneSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('normalized_milestone_type', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('template_suggested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ai_suggested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('estimated_offset_days', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('actual_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcome_snapshots', to='projects.milestone')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.agreementoutcomesnapshot')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBenchmarkAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('regional', 'Regional'), ('template', 'Template'), ('contractor', 'Contractor')], db_index=True, max_length=24)),
                ('project_type', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('project_subtype', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='US', max_length=8)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('normalized_region_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('completed_project_count', models.PositiveIntegerField(default=0)),
                ('average_final_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('median_final_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('min_final_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_final_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_actual_duration_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('median_actual_duration_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_milestone_count', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('average_retainage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_retainage_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('average_estimate_variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_estimate_variance_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('average_duration_variance_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_sample_size', models.PositiveIntegerField(default=0)),
                ('duration_sample_size', models.PositiveIntegerField(default=0)),
                ('estimate_variance_sample_size', models.PositiveIntegerField(default=0)),
                ('duration_variance_sample_size', models.PositiveIntegerField(default=0)),
                ('amount_stddev', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('duration_stddev', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('region_granularity', models.CharField(blank=True, default='none', max_length=32)),
                ('common_milestone_patterns', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_snapshot_completed_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_benchmark_aggregates', to='projects.contractor')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_benchmark_aggregates', to='projects.projecttemplate')),
            ],
            options={
                'ordering': ['scope', 'project_type', 'project_subtype', 'normalized_region_key', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='agreementoutcomesnapshot',
            index=models.Index(fields=['excluded_from_benchmarks', 'agreement_completed_date'], name='projects_ag_exclude_ba4ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementoutcomesnapshot',
            index=models.Index(fields=['project_type', 'project_subtype'], name='projects_ag_project_c199ac_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementoutcomesnapshot',
            index=models.Index(fields=['template'], name='projects_ag_templat_f03d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementoutcomesnapshot',
            index=models.Index(fields=['contractor'], name='projects_ag_contrac_e0aba5_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementoutcomesnapshot',
            index=models.Index(fields=['normalized_region_key'], name='projects_ag_normali_43375d_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementoutcomemilestonesnapshot',
            index=models.Index(fields=['snapshot', 'sort_order'], name='projects_ag_snapsho_f31cf1_idx'),
        ),
        migrations.AddIndex(
            model_name='agreementoutcomemilestonesnapshot',
            index=models.Index(fields=['normalized_milestone_type'], name='projects_ag_normali_5b8f86_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbenchmarkaggregate',
            index=models.Index(fields=['scope', 'project_type', 'project_subtype'], name='projects_pr_scope_041623_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbenchmarkaggregate',
            index=models.Index(fields=['scope', 'normalized_region_key'], name='projects_pr_scope_c6b854_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbenchmarkaggregate',
            index=models.Index(fields=['scope', 'template'], name='projects_pr_scope_695eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbenchmarkaggregate',
            index=models.Index(fields=['scope', 'contractor'], name='projects_pr_scope_86934f_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectbenchmarkaggregate',
            constraint=models.UniqueConstraint(fields=('scope', 'contractor', 'template', 'project_type', 'project_subtype', 'normalized_region_key'), name='uniq_project_benchmark_scope_dimensions'),
        ),
    ]
