# Generated by Django 5.2.1 on 2026-03-27 02:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0104_projecttemplate_benchmark_match_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedbenchmarkprofile',
            name='region_priority_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Future estimator blending weight; current resolver remains deterministic and fallback-based.', max_digits=6),
        ),
    ]
