# Generated by Django 5.2.1 on 2026-03-27 04:40

import django.db.models.deletion
import projects.models_compliance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0105_seedbenchmarkprofile_region_priority_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateTradeLicenseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(db_index=True, max_length=2)),
                ('state_name', models.CharField(blank=True, default='', max_length=64)),
                ('trade_key', models.CharField(db_index=True, max_length=64)),
                ('trade_label', models.CharField(blank=True, default='', max_length=120)),
                ('license_required', models.BooleanField(default=False)),
                ('insurance_required', models.BooleanField(default=False)),
                ('issuing_authority_name', models.CharField(blank=True, default='', max_length=255)),
                ('authority_short_name', models.CharField(blank=True, default='', max_length=120)),
                ('official_lookup_url', models.URLField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('portal', 'Portal'), ('dataset', 'Dataset'), ('api', 'API'), ('unknown', 'Unknown')], default='manual', max_length=16)),
                ('rule_notes', models.TextField(blank=True, default='')),
                ('exemption_threshold', models.CharField(blank=True, default='', max_length=120)),
                ('exemption_notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('last_reviewed_at', models.DateField(blank=True, null=True)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state_code', 'trade_key'],
                'indexes': [models.Index(fields=['state_code', 'trade_key', 'active'], name='projects_st_state_c_be5c06_idx')],
                'constraints': [models.UniqueConstraint(fields=('state_code', 'trade_key'), name='uniq_state_trade_license_requirement')],
            },
        ),
        migrations.CreateModel(
            name='ContractorComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('license', 'License'), ('insurance', 'Insurance')], db_index=True, max_length=16)),
                ('trade_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('trade_label', models.CharField(blank=True, default='', max_length=120)),
                ('state_code', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('identifier', models.CharField(blank=True, default='', max_length=120)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=projects.models_compliance.contractor_compliance_upload_to)),
                ('status', models.CharField(choices=[('on_file', 'On File'), ('expired', 'Expired'), ('pending_review', 'Pending Review'), ('verified', 'Verified')], db_index=True, default='on_file', max_length=20)),
                ('source', models.CharField(choices=[('legacy_profile', 'Legacy Profile'), ('manual_upload', 'Manual Upload')], default='manual_upload', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='projects.contractor')),
            ],
            options={
                'ordering': ['record_type', 'trade_key', '-updated_at', '-id'],
                'indexes': [models.Index(fields=['contractor', 'record_type', 'state_code'], name='projects_co_contrac_411521_idx'), models.Index(fields=['contractor', 'status'], name='projects_co_contrac_053f7e_idx')],
            },
        ),
    ]
