# Generated by Django 5.2.1 on 2026-03-27 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0106_statetradelicenserequirement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='subcontractor_compliance_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='subcontractor_compliance_override_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='milestone',
            name='subcontractor_compliance_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('compliant', 'Compliant'), ('missing_license', 'Missing License'), ('missing_insurance', 'Missing Insurance'), ('pending_license', 'Pending License'), ('overridden', 'Overridden'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Advisory compliance state snapshot for the assigned subcontractor on this milestone.', max_length=32),
        ),
        migrations.AddField(
            model_name='milestone',
            name='subcontractor_compliance_warning_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Structured advisory compliance decision snapshot captured when the assignment changed.'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='subcontractor_insurance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='subcontractor_license_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='subcontractor_license_requested_by',
            field=models.ForeignKey(blank=True, help_text='Contractor user who requested compliance documents before assignment acceptance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcontractor_license_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='subcontractor_license_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='subcontractor_required_state_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='milestone',
            name='subcontractor_required_trade_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
