# Generated by Django 5.2.1 on 2026-03-27 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0107_milestone_subcontractor_compliance_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='allow_discovery',
            field=models.BooleanField(db_index=True, default=False, help_text="Whether this template can appear outside the owner's private library."),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='normalized_region_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Primary region applicability key shared with benchmark and learning systems.', max_length=255),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_project_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('regional', 'Regional'), ('public', 'Public'), ('system', 'System')], db_index=True, default='private', help_text='Discovery visibility for contractor-facing template marketplace flows.', max_length=24),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['visibility', 'allow_discovery'], name='projects_pr_visibil_43fd1e_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['normalized_region_key'], name='projects_pr_normali_0e6df4_idx'),
        ),
    ]
