# Generated by Django 5.2.1 on 2026-03-27 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0108_projecttemplate_allow_discovery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='report_recipient_email',
            field=models.EmailField(blank=True, default='', help_text='Optional owner/investor-facing contact email for project report emails.', max_length=254),
        ),
        migrations.AddField(
            model_name='agreement',
            name='report_recipient_name',
            field=models.CharField(blank=True, default='', help_text='Optional owner/investor-facing contact name for project report emails.', max_length=255),
        ),
        migrations.CreateModel(
            name='ProjectEmailReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('milestone_approval_requested', 'Milestone Approval Requested'), ('payment_released', 'Payment Released'), ('compliance_alert', 'Compliance Alert'), ('weekly_project_summary', 'Weekly Project Summary')], db_index=True, max_length=48)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('dedup_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_report_logs', to='projects.agreement')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_report_logs', to='projects.invoice')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_report_logs', to='projects.milestone')),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
                'indexes': [models.Index(fields=['agreement', 'event_type', 'sent_at'], name='projects_pr_agreeme_1a78da_idx')],
            },
        ),
    ]
