# Generated by Django 5.2.1 on 2026-03-27 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0109_agreement_report_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='agreement_mode',
            field=models.CharField(choices=[('standard', 'Standard'), ('maintenance', 'Maintenance')], db_index=True, default='standard', help_text='Standard keeps one-time project behavior. Maintenance enables recurring-service support.', max_length=24),
        ),
        migrations.AddField(
            model_name='agreement',
            name='auto_generate_next_occurrence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='maintenance_status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=24),
        ),
        migrations.AddField(
            model_name='agreement',
            name='next_occurrence_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='recurrence_end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='agreement',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='agreement',
            name='recurrence_start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='recurring_service_enabled',
            field=models.BooleanField(default=False, help_text='Whether this agreement should generate recurring maintenance milestone occurrences.'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='recurring_summary_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agreement',
            name='service_window_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='milestone',
            name='generated_from_recurring_rule',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='milestone',
            name='is_recurring_rule',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this milestone acts as the recurring-service rule/template for future occurrences.'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='next_occurrence_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='occurrence_sequence_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='milestone',
            name='recurrence_anchor_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='recurrence_end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='recurrence_interval',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='milestone',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='milestone',
            name='recurring_rule_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_occurrences', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='scheduled_service_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='service_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='service_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
