# Generated by Django 5.2.1 on 2026-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0110_agreement_agreement_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="contractor_onboarding_status",
            field=models.CharField(blank=True, default="not_started", max_length=50),
        ),
        migrations.AddField(
            model_name="contractor",
            name="contractor_onboarding_step",
            field=models.CharField(blank=True, default="welcome", max_length=50),
        ),
        migrations.AddField(
            model_name="contractor",
            name="first_project_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="first_agreement_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="stripe_prompt_dismissed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="stripe_connected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
