# Generated by Django 5.2.1 on 2026-03-27 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0111_contractor_activation_onboarding_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="onboarding_last_step_reached",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="contractor",
            name="onboarding_step_durations",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="contractor",
            name="onboarding_step_entered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ContractorActivationEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("step", models.CharField(blank=True, default="", max_length=50)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("seconds_in_step", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "contractor",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activation_events", to="projects.contractor"),
                ),
                (
                    "user",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contractor_activation_events", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
