# Generated by Django 5.2.1 on 2026-03-28 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0112_contractoractivationevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('related_entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('related_label', models.CharField(blank=True, default='', max_length=255)),
                ('icon_hint', models.CharField(blank=True, default='', max_length=48)),
                ('navigation_target', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('surfaced_in_dashboard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_activity_events', to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='projects.agreement')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='projects.contractor')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='projects.milestone')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
