# Generated by Django 5.2.1 on 2026-03-28 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0113_contractoractivityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_e164', models.CharField(db_index=True, max_length=32, unique=True)),
                ('can_send_sms', models.BooleanField(default=False)),
                ('opted_out', models.BooleanField(default=False)),
                ('opted_out_at', models.DateTimeField(blank=True, null=True)),
                ('opted_in_at', models.DateTimeField(blank=True, null=True)),
                ('opted_in_source', models.CharField(blank=True, choices=[('signup', 'Signup'), ('agreement', 'Agreement'), ('inbound_start', 'Inbound START'), ('admin', 'Admin')], default='', max_length=32)),
                ('opted_out_source', models.CharField(blank=True, choices=[('inbound_stop', 'Inbound STOP'), ('api', 'API'), ('admin', 'Admin'), ('twilio_error', 'Twilio Error')], default='', max_length=32)),
                ('last_inbound_keyword', models.CharField(blank=True, default='', max_length=32)),
                ('consent_text_snapshot', models.TextField(blank=True, default='')),
                ('consent_source_page', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_consents', to='projects.contractor')),
                ('homeowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_consents', to='projects.homeowner')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
