# Generated by Django 5.2.1 on 2026-03-28 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0114_smsconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAutomationDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('phone_number_e164', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('should_send', models.BooleanField(default=False)),
                ('channel_decision', models.CharField(choices=[('sms', 'SMS'), ('dashboard_only', 'Dashboard Only'), ('suppressed', 'Suppressed'), ('none', 'None')], db_index=True, default='none', max_length=24)),
                ('reason_code', models.CharField(db_index=True, max_length=64)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='low', max_length=16)),
                ('template_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('intent_key', models.CharField(blank=True, default='', max_length=64)),
                ('intent_summary', models.CharField(blank=True, default='', max_length=255)),
                ('message_preview', models.CharField(blank=True, default='', max_length=255)),
                ('cooldown_applied', models.BooleanField(default=False)),
                ('duplicate_suppressed', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('deferred', models.BooleanField(default=False)),
                ('sms_consent_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('decision_context_json', models.JSONField(blank=True, default=dict)),
                ('twilio_message_sid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_automation_decisions', to='projects.agreement')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_automation_decisions', to='projects.contractor')),
                ('homeowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_automation_decisions', to='projects.homeowner')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_automation_decisions', to='projects.invoice')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_automation_decisions', to='projects.milestone')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeferredSMSAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_e164', models.CharField(db_index=True, max_length=32)),
                ('template_key', models.CharField(db_index=True, max_length=64)),
                ('intent_key', models.CharField(blank=True, default='', max_length=64)),
                ('message_body', models.TextField()),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_sms_automations', to='projects.agreement')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_sms_automations', to='projects.contractor')),
                ('homeowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_sms_automations', to='projects.homeowner')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_sms_automations', to='projects.invoice')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_sms_automations', to='projects.milestone')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deferred_records', to='projects.smsautomationdecision')),
            ],
            options={
                'ordering': ['scheduled_for', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='smsautomationdecision',
            index=models.Index(fields=['phone_number_e164', 'template_key', 'created_at'], name='projects_sm_phone_n_8d66ee_idx'),
        ),
        migrations.AddIndex(
            model_name='smsautomationdecision',
            index=models.Index(fields=['event_type', 'created_at'], name='projects_sm_event_t_cb52a1_idx'),
        ),
        migrations.AddIndex(
            model_name='deferredsmsautomation',
            index=models.Index(fields=['status', 'scheduled_for'], name='projects_de_status_874371_idx'),
        ),
    ]
