# Generated by Django 5.2.1 on 2026-04-14 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0122_draw_request_escrow_release'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agreementoutcomemilestonesnapshot',
            new_name='projects_ag_has_dis_ca6044_idx',
            old_name='projects_ag_has_dis_302823_idx',
        ),
        migrations.RenameIndex(
            model_name='agreementoutcomesnapshot',
            new_name='projects_ag_project_e0a2f8_idx',
            old_name='projects_ag_projec_f272bd_idx',
        ),
        migrations.RenameIndex(
            model_name='milestonebenchmarkaggregate',
            new_name='projects_mi_scope_99ad73_idx',
            old_name='projects_mi_scope_4d52b3_idx',
        ),
        migrations.RenameIndex(
            model_name='milestonebenchmarkaggregate',
            new_name='projects_mi_scope_7020be_idx',
            old_name='projects_mi_scope_22b626_idx',
        ),
        migrations.RenameIndex(
            model_name='milestonebenchmarkaggregate',
            new_name='projects_mi_scope_950570_idx',
            old_name='projects_mi_scope_e56c7d_idx',
        ),
        migrations.RenameIndex(
            model_name='milestonebenchmarkaggregate',
            new_name='projects_mi_scope_6e7eb2_idx',
            old_name='projects_mi_scope_2c5f66_idx',
        ),
        migrations.RenameIndex(
            model_name='projectbenchmarkaggregate',
            new_name='projects_pr_scope_97f183_idx',
            old_name='projects_pr_scope_70f09c_idx',
        ),
        migrations.AlterField(
            model_name='drawrequest',
            name='public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public token for owner draw review and payment flow.', unique=True),
        ),
        migrations.AlterField(
            model_name='drawrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('awaiting_release', 'Awaiting Release'), ('released', 'Released'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('paid', 'Paid')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('subcontractor_comment', 'Subcontractor Comment'), ('subcontractor_file', 'Subcontractor File'), ('subcontractor_review', 'Subcontractor Review Request'), ('draw_approved', 'Draw Approved'), ('draw_changes_requested', 'Draw Changes Requested'), ('draw_paid', 'Draw Paid'), ('draw_released', 'Draw Released')], db_index=True, max_length=64),
        ),
    ]
