# Generated by Django 5.2.1 on 2026-04-16 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0125_agreement_fee_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorinvite',
            name='source_intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_invites', to='projects.projectintake'),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='post_submit_flow',
            field=models.CharField(blank=True, choices=[('', 'Unselected'), ('single_contractor', 'Invite One Contractor'), ('multi_contractor', 'Invite Multiple Contractors')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='post_submit_flow_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='project_class',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20),
        ),
    ]
