# Generated by Django 5.2.1 on 2026-04-16 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0126_contractorinvite_source_intake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='public_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.publiccontractorlead'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('subcontractor_comment', 'Subcontractor Comment'), ('subcontractor_file', 'Subcontractor File'), ('subcontractor_review', 'Subcontractor Review Request'), ('draw_approved', 'Draw Approved'), ('draw_changes_requested', 'Draw Changes Requested'), ('draw_paid', 'Draw Paid'), ('draw_released', 'Draw Released'), ('bid_awarded', 'Bid Awarded'), ('bid_not_selected', 'Bid Not Selected')], db_index=True, max_length=64),
        ),
    ]
