# Generated by Django 5.2.1 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0127_bid_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectintake",
            name="ai_project_budget",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="projectintake",
            name="ai_project_timeline_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
