# Generated by Django 5.2.1 on 2026-04-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0130_publiccontractorlead_follow_up_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementProposalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('draft_created', 'Draft Created'), ('finalized', 'Finalized')], db_index=True, max_length=24)),
                ('is_successful', models.BooleanField(db_index=True, default=False)),
                ('success_reason', models.CharField(blank=True, default='', max_length=255)),
                ('project_title', models.CharField(blank=True, default='', max_length=255)),
                ('project_type', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('project_subtype', models.CharField(blank=True, default='', max_length=120)),
                ('proposal_text', models.TextField(blank=True, default='')),
                ('budget_text', models.CharField(blank=True, default='', max_length=255)),
                ('timeline_text', models.CharField(blank=True, default='', max_length=255)),
                ('measurement_handling', models.CharField(blank=True, default='', max_length=80)),
                ('photo_count', models.PositiveIntegerField(default=0)),
                ('request_path_label', models.CharField(blank=True, default='', max_length=120)),
                ('request_signals', models.JSONField(blank=True, default=list)),
                ('clarification_summary', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agreement_status', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('snapshot_created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_snapshots', to='projects.agreement')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_snapshots', to='projects.contractor')),
                ('source_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_snapshots', to='projects.publiccontractorlead')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_snapshots', to='projects.projecttemplate')),
            ],
            options={
                'ordering': ['-snapshot_created_at', '-id'],
                'indexes': [models.Index(fields=['stage', 'is_successful', 'project_type', 'project_subtype'], name='projects_ag_stage_1f5e4c_idx'), models.Index(fields=['project_type', 'project_subtype', 'is_successful'], name='projects_ag_project_ed1bfc_idx'), models.Index(fields=['contractor', 'stage'], name='projects_ag_contrac_e61b9b_idx'), models.Index(fields=['source_lead'], name='projects_ag_source__d61b01_idx')],
                'constraints': [models.UniqueConstraint(fields=('agreement', 'stage'), name='uniq_agreement_proposal_snapshot_stage')],
            },
        ),
    ]
