# Generated by Django 5.2.1 on 2026-04-20 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0132_contractorpublicprofile_brand_voice_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOutcomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_family_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('project_family_label', models.CharField(blank=True, default='', max_length=255)),
                ('scope_mode', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('template_used', models.CharField(blank=True, default='', max_length=255)),
                ('original_intelligence_payload', models.JSONField(blank=True, default=dict)),
                ('original_suggested_plan', models.JSONField(blank=True, default=dict)),
                ('final_project_state', models.JSONField(blank=True, default=dict)),
                ('final_milestones', models.JSONField(blank=True, default=list)),
                ('total_project_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_value_range', models.JSONField(blank=True, default=dict)),
                ('actual_duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_duration_range', models.JSONField(blank=True, default=dict)),
                ('milestone_count', models.PositiveIntegerField(default=0)),
                ('dispute_flag', models.BooleanField(db_index=True, default=False)),
                ('amendment_count', models.PositiveIntegerField(default=0)),
                ('completion_status', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_outcome_snapshot', to='projects.agreement')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_outcome_snapshots', to='projects.contractor')),
                ('source_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_outcome_snapshots', to='projects.publiccontractorlead')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_outcome_snapshots', to='projects.projecttemplate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project_family_key', 'scope_mode'], name='projects_pr_project_eeedef_idx'), models.Index(fields=['template_used'], name='projects_pr_templat_defd62_idx'), models.Index(fields=['completion_status'], name='projects_pr_complet_4759e9_idx'), models.Index(fields=['contractor'], name='projects_pr_contrac_bb6e37_idx')],
            },
        ),
    ]
