# Generated by Django 5.2.1 on 2026-04-20

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0135_regional_benchmark_aggregate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorWorkspaceContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_project_family_key", models.CharField(blank=True, default="", max_length=100)),
                ("default_project_family_label", models.CharField(blank=True, default="", max_length=255)),
                ("context_updated_at", models.DateTimeField(db_index=True, default=timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contractor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workspace_context",
                        to="projects.contractor",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
    ]
