# Generated by Django 5.2.13 on 2026-04-21 05:59

import django.db.models.deletion
import projects.models_support
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0136_contractorworkspacecontext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='stripe_onboarding_status',
            field=models.CharField(blank=True, db_index=True, default='not_started', max_length=50),
        ),
        migrations.CreateModel(
            name='ContractorOnboardingSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField(blank=True, default='')),
                ('preferred_project_family_keys', models.JSONField(blank=True, default=list)),
                ('preferred_project_family_label', models.CharField(blank=True, default='', max_length=255)),
                ('workflow_style', models.CharField(blank=True, default='', max_length=255)),
                ('milestone_tendencies', models.JSONField(blank=True, default=list)),
                ('pricing_baseline', models.JSONField(blank=True, default=dict)),
                ('agreement_defaults', models.JSONField(blank=True, default=dict)),
                ('clarification_questions', models.JSONField(blank=True, default=list)),
                ('clarification_answers', models.JSONField(blank=True, default=dict)),
                ('generated_setup', models.JSONField(blank=True, default=dict)),
                ('quick_adjustment_notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_setup', to='projects.contractor')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, db_index=True, editable=False, max_length=16, null=True, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('user_role', models.CharField(blank=True, default='', max_length=64)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('account_login', 'Account / Login'), ('agreement_help', 'Agreement Help'), ('payment_escrow', 'Payment / Escrow'), ('invoice_issue', 'Invoice Issue'), ('dispute_review', 'Dispute / Review'), ('contractor_profile', 'Contractor Profile'), ('customer_intake', 'Customer Intake'), ('technical_problem', 'Technical Problem'), ('general_question', 'General Question')], db_index=True, default='general_question', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=16)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In Review'), ('waiting_on_user', 'Waiting on User'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=24)),
                ('related_object_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('related_object_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=projects.models_support.support_ticket_attachment_upload_to)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
