# Generated by Django 5.2.13 on 2026-04-22 15:38

import django.db.models.deletion
from django.db import migrations, models


def _backfill_contractor_review_stats(apps, schema_editor):
    Contractor = apps.get_model("projects", "Contractor")
    ContractorReview = apps.get_model("projects", "ContractorReview")
    for contractor in Contractor.objects.all().iterator():
        reviews = ContractorReview.objects.filter(
            contractor_id=contractor.id,
            is_verified=True,
            is_public=True,
        )
        count = reviews.count()
        average = reviews.aggregate(avg=models.Avg("rating")).get("avg") if count else None
        Contractor.objects.filter(pk=contractor.id).update(
            review_count=count,
            average_rating=float(average or 0),
        )


def _reverse_backfill_contractor_review_stats(apps, schema_editor):
    Contractor = apps.get_model("projects", "Contractor")
    Contractor.objects.update(review_count=0, average_rating=0)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0138_expense_request_stripe_trace_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='contractor',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractorreview',
            name='linked_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contractor_reviews', to='projects.invoice'),
        ),
        migrations.AddField(
            model_name='contractorreview',
            name='linked_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contractor_reviews', to='projects.milestone'),
        ),
        migrations.RunPython(_backfill_contractor_review_stats, _reverse_backfill_contractor_review_stats),
    ]
