# Generated by Django 5.2.13 on 2026-04-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0139_contractor_average_rating_contractor_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectintake',
            name='budget_range_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='contact_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='desired_timing_text',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='preferred_contact_method',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='property_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='projectintake',
            name='lead_source',
            field=models.CharField(choices=[('landing_page', 'Landing Page'), ('public_profile', 'Public Profile'), ('quote_request', 'Quote Request'), ('manual', 'Manual'), ('qr', 'QR'), ('contractor_sent_form', 'Contractor Sent Form'), ('direct', 'Direct')], default='direct', max_length=20),
        ),
        migrations.AlterField(
            model_name='publiccontractorlead',
            name='source',
            field=models.CharField(choices=[('landing_page', 'Landing Page'), ('public_profile', 'Public Profile'), ('quote_request', 'Quote Request'), ('manual', 'Manual'), ('qr', 'QR'), ('contractor_sent_form', 'Contractor Sent Form'), ('direct', 'Direct')], default='public_profile', max_length=20),
        ),
    ]
