# Generated by Django 5.2.13 on 2026-04-23 00:00

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0141_notification_category_notification_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorpublicprofile',
            name='brand_accent_color',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='contractorpublicprofile',
            name='brand_font_theme',
            field=models.CharField(blank=True, choices=[('clean_sans', 'Clean Sans'), ('modern_sans', 'Modern Sans'), ('editorial_serif', 'Editorial Serif'), ('warm_serif', 'Warm Serif'), ('compact_sans', 'Compact Sans')], default='clean_sans', max_length=32),
        ),
        migrations.AddField(
            model_name='contractorpublicprofile',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.contractor_public_asset_upload_to),
        ),
        migrations.AddField(
            model_name='contractorpublicprofile',
            name='profile_theme',
            field=models.CharField(blank=True, choices=[('modern', 'Modern'), ('professional', 'Professional'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('warm', 'Warm')], default='modern', max_length=32),
        ),
        migrations.AddField(
            model_name='contractorpublicprofile',
            name='show_gallery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractorpublicprofile',
            name='show_quote_cta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contractorpublicprofile',
            name='show_reviews',
            field=models.BooleanField(default=True),
        ),
    ]
