# Generated by Django 5.2.13 on 2026-04-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0143_projecttemplate_is_system_template_and_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='step_status',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Lightweight wizard progress marker for resuming the agreement flow.', max_length=32),
        ),
    ]
