# Generated by Django 5.2.13 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0144_agreement_step_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="pdf_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
