# Generated by Django 5.2.13 on 2026-05-01 02:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0145_agreement_pdf_viewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorMilestoneAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_pay', models.DecimalField(decimal_places=2, help_text='Contractor/subcontractor-facing pay for this milestone.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_release_mode', models.CharField(choices=[('manual_release', 'Manual Release'), ('auto_after_customer_approval', 'Auto-Release After Customer Approval')], db_index=True, default='manual_release', max_length=40)),
                ('agreement_acceptance_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='not_sent', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('agreement_version', models.PositiveIntegerField(db_index=True, default=1)),
                ('terms_snapshot', models.JSONField(blank=True, default=dict)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_subcontractor_milestone_agreements', to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_milestone_agreements', to='projects.agreement')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_milestone_agreements', to='projects.contractor')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_milestone_agreements', to='projects.milestone')),
                ('subcontractor_invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_agreements', to='projects.subcontractorinvitation')),
            ],
            options={
                'ordering': ['-agreement_version', '-id'],
                'indexes': [models.Index(fields=['milestone', 'agreement_acceptance_status'], name='projects_su_milesto_c8b00c_idx'), models.Index(fields=['agreement', 'agreement_acceptance_status'], name='projects_su_agreeme_c65285_idx'), models.Index(fields=['subcontractor_invitation', 'agreement_version'], name='projects_su_subcont_c93196_idx')],
                'constraints': [models.UniqueConstraint(fields=('milestone', 'subcontractor_invitation', 'agreement_version'), name='unique_subcontractor_milestone_agreement_version'), models.CheckConstraint(condition=models.Q(('agreed_pay__gt', 0)), name='subcontractor_milestone_agreement_pay_positive')],
            },
        ),
    ]
