# Generated by Django 5.2.1 on 2026-05-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0148_subcontractorquoterequest"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subcontractorquoterequest",
            new_name="projects_su_agreeme_78f72b_idx",
            old_name="projects_sqr_agreem_6f6d3f_idx",
        ),
        migrations.RenameIndex(
            model_name="subcontractorquoterequest",
            new_name="projects_su_subcont_f83969_idx",
            old_name="projects_sqr_subcon_1d00b4_idx",
        ),
        migrations.RenameIndex(
            model_name="subcontractorquoterequest",
            new_name="projects_su_contrac_e642e5_idx",
            old_name="projects_sqr_contra_0c2f5a_idx",
        ),
    ]
