# Generated by Django 5.2.1 on 2026-05-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0149_projecttemplatemilestone_structure_fields"),
        (
            "projects",
            "0149_rename_projects_sqr_agreem_6f6d3f_idx_projects_su_agreeme_78f72b_idx_and_more",
        ),
    ]

    operations = []
