# Generated by Django 5.2.1 on 2026-05-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0150_merge_20260503_0257"),
        ("projects", "0151_supportmessage_sync_fields"),
    ]

    operations = []
