# Generated by Django 5.2.1 on 2026-05-04 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0152_merge_20260504_1326"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SupportMessage",
            new_name="SupportTicketMessage",
        ),
        migrations.AddConstraint(
            model_name="supportticketmessage",
            constraint=models.UniqueConstraint(
                fields=("gmail_message_id",),
                name="uniq_support_message_gmail_message_id",
            ),
        ),
    ]
