# Generated by Django 5.2.13 on 2026-05-04 22:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0153_supportticketmessage_delete_supportmessage_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name='supportticketmessage',
                    old_name='message_text',
                    new_name='message',
                ),
                migrations.RenameField(
                    model_name='supportticketmessage',
                    old_name='sender_role',
                    new_name='sender_type',
                ),
                migrations.AlterField(
                    model_name='supportticketmessage',
                    name='message',
                    field=models.TextField(db_column='message_text'),
                ),
                migrations.AlterField(
                    model_name='supportticketmessage',
                    name='sender_type',
                    field=models.CharField(
                        choices=[
                            ('user', 'User'),
                            ('support', 'Support'),
                            ('system', 'System'),
                        ],
                        db_column='sender_role',
                        db_index=True,
                        default='user',
                        max_length=16,
                    ),
                ),
                migrations.AlterModelTable(
                    name='supportticketmessage',
                    table='projects_supportticketmessage',
                ),
                migrations.RemoveConstraint(
                    model_name='supportticketmessage',
                    name='uniq_support_message_gmail_message_id',
                ),
                migrations.RemoveConstraint(
                    model_name='supportticketmessage',
                    name='uniq_support_message_gmail_message_id',
                ),
                migrations.AddConstraint(
                    model_name='supportticketmessage',
                    constraint=models.UniqueConstraint(
                        fields=('gmail_message_id',),
                        name='uniq_support_message_gmail_message_id',
                    ),
                ),
            ],
        ),
    ]
