# Generated by Django 5.2.13 on 2026-05-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0153_supportticketmessage_delete_supportmessage_and_more'),
    ]

    operations = [
    ]
