# Generated by Django 5.2.13 on 2026-05-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0154_fix_supportticketmessage_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
