# Generated by Django 5.2.13 on 2026-05-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0158_garage_doors_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='contractor_responsibilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreement',
            name='excluded_work',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreement',
            name='homeowner_participation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreement',
            name='homeowner_responsibilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreement',
            name='project_mode',
            field=models.CharField(choices=[('full_service', 'Full Service'), ('assisted_diy', 'DIY Assistance'), ('consultation', 'Consultation / Guidance'), ('inspection_only', 'Inspection Only')], db_index=True, default='full_service', help_text='Defines whether the project is full-service, DIY assistance, consultation, or inspection-only.', max_length=24),
        ),
        migrations.AddField(
            model_name='contractor',
            name='accepts_consultation_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractor',
            name='accepts_diy_assistance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractor',
            name='accepts_homeowner_participation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractor',
            name='accepts_hourly_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractor',
            name='accepts_inspection_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='homeowner_assistance_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='homeowner_participation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='homeowner_started_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='homeowner_task_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='project_mode',
            field=models.CharField(choices=[('full_service', 'Full Service'), ('assisted_diy', 'DIY Assistance'), ('consultation', 'Consultation / Guidance'), ('inspection_only', 'Inspection Only')], default='full_service', max_length=24),
        ),
    ]
