# Generated by Django 5.2.13 on 2026-05-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0159_agreement_contractor_responsibilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='milestone_role',
            field=models.CharField(blank=True, choices=[('homeowner_task', 'Homeowner Task'), ('contractor_task', 'Contractor Task'), ('shared_task', 'Shared Task'), ('inspection_checkpoint', 'Inspection Checkpoint')], db_index=True, default='', help_text='Human-readable milestone role used for homeowner/contractor/shared/inspection workflow visibility.', max_length=32),
        ),
    ]
