# Generated by Django 5.2.13 on 2026-05-11 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0160_milestone_milestone_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='collaboration_summary_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='milestone',
            name='completion_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='milestone',
            name='inspection_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='milestone',
            name='inspection_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='inspection_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='inspection_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_reviewed_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='inspection_status',
            field=models.CharField(blank=True, choices=[('not_requested', 'Not Requested'), ('inspection_requested', 'Inspection Requested'), ('inspection_passed', 'Inspection Passed'), ('inspection_revision_required', 'Inspection Revision Required')], db_index=True, default='not_requested', max_length=40),
        ),
    ]
