# Generated by Django 5.2.13 on 2026-05-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0161_agreement_collaboration_summary_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectintake',
            name='payment_preference',
            field=models.CharField(choices=[('escrow', 'Escrow milestone payments'), ('direct', 'Direct payment to contractor'), ('discuss', 'Discuss payment options')], default='escrow', max_length=20),
        ),
    ]
