# Generated by Django 5.2.13 on 2026-05-12 04:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0162_projectintake_payment_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorDirectoryListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('google_places', 'Google Places'), ('cached_directory', 'Cached Directory'), ('myhomebro_verified', 'MyHomeBro Verified'), ('manual', 'Manual')], db_index=True, default='google_places', max_length=32)),
                ('google_place_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('normalized_business_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website_url', models.URLField(blank=True, default='')),
                ('google_maps_url', models.URLField(blank=True, default='')),
                ('formatted_address', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('primary_trade', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('trade_categories', models.JSONField(blank=True, default=list)),
                ('google_rating', models.FloatField(blank=True, null=True)),
                ('google_review_count', models.PositiveIntegerField(default=0)),
                ('business_status', models.CharField(blank=True, default='', max_length=80)),
                ('claimed_profile', models.BooleanField(db_index=True, default=False)),
                ('sms_opt_out', models.BooleanField(default=False)),
                ('email_opt_out', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_listings', to='projects.contractor')),
            ],
            options={
                'ordering': ['-claimed_profile', '-google_review_count', '-google_rating', 'business_name'],
            },
        ),
        migrations.CreateModel(
            name='ContractorDiscoveryInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In App'), ('manual', 'Manual'), ('contact_form', 'Contact Form')], db_index=True, default='sms', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('clicked', 'Clicked'), ('claimed', 'Claimed'), ('responded', 'Responded'), ('declined', 'Declined'), ('expired', 'Expired'), ('opted_out', 'Opted Out')], db_index=True, default='pending', max_length=24)),
                ('destination_phone', models.CharField(blank=True, default='', max_length=40)),
                ('destination_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_invites', to='projects.agreement')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_invites', to='projects.contractor')),
                ('directory_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_invites', to='projects.contractordirectorylisting')),
                ('public_intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovery_invites', to='projects.projectintake')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='contractordirectorylisting',
            index=models.Index(fields=['google_place_id'], name='projects_co_google__2754fa_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordirectorylisting',
            index=models.Index(fields=['normalized_business_name', 'city'], name='projects_co_normali_2d28a1_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordirectorylisting',
            index=models.Index(fields=['phone_number'], name='projects_co_phone_n_e8b22c_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordirectorylisting',
            index=models.Index(fields=['source', 'claimed_profile'], name='projects_co_source_b2c141_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordiscoveryinvite',
            index=models.Index(fields=['invite_token'], name='projects_co_invite__ebe371_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordiscoveryinvite',
            index=models.Index(fields=['status', 'channel'], name='projects_co_status_455e44_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordiscoveryinvite',
            index=models.Index(fields=['contractor', 'status'], name='projects_co_contrac_cdfe13_idx'),
        ),
    ]
