# Generated by Django 5.2.13 on 2026-05-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0163_contractordirectorylisting_contractordiscoveryinvite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractordirectorylisting',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractordirectorylisting',
            name='assisted_diy_friendly',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contractordirectorylisting',
            name='collaboration_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractordirectorylisting',
            name='compatibility_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contractordirectorylisting',
            name='escrow_friendly',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contractordirectorylisting',
            name='inspection_capable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contractordirectorylisting',
            name='manually_enriched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contractordirectorylisting',
            name='manually_reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contractordirectorylisting',
            name='rescue_project_friendly',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contractordiscoveryinvite',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
