# Generated by Django 5.2.13 on 2026-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0164_contractordirectorylisting_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='workflow_profile',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible assisted-DIY workflow metadata such as assistance format, scheduling mode, and participation structure.'),
        ),
    ]
