# Generated by Django 5.2.13 on 2026-05-17 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0166_projectintake_tentative_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorDirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('website_domain', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('public_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('zip_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('google_place_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('services', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('google_places', 'Google Places'), ('admin_search', 'Admin Search'), ('public_intake', 'Public Intake'), ('manual', 'Manual')], db_index=True, default='google_places', max_length=32)),
                ('claimed', models.BooleanField(db_index=True, default=False)),
                ('profile_status', models.CharField(choices=[('basic', 'Basic')], db_index=True, default='basic', max_length=32)),
                ('enrichment_status', models.CharField(choices=[('not_started', 'Not Started')], db_index=True, default='not_started', max_length=32)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('claimed_by_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_entries', to='projects.contractor')),
            ],
            options={
                'ordering': ['business_name', 'city', 'state'],
            },
        ),
        migrations.CreateModel(
            name='ContractorDirectoryDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('public_intake', 'Public Intake'), ('admin_search', 'Admin Search'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('search_term', models.CharField(blank=True, max_length=255, null=True)),
                ('project_type', models.CharField(blank=True, max_length=120, null=True)),
                ('project_subtype', models.CharField(blank=True, max_length=120, null=True)),
                ('search_city', models.CharField(blank=True, max_length=120, null=True)),
                ('search_state', models.CharField(blank=True, max_length=60, null=True)),
                ('search_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('radius_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_by_homeowner', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_directory_discoveries', to=settings.AUTH_USER_MODEL)),
                ('intake_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_discoveries', to='projects.projectintake')),
                ('directory_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='projects.contractordirectoryentry')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='contractordirectoryentry',
            index=models.Index(fields=['website_domain'], name='projects_co_website_f5bc68_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordirectoryentry',
            index=models.Index(fields=['normalized_phone'], name='projects_co_normali_388298_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordirectoryentry',
            index=models.Index(fields=['normalized_name', 'zip_code'], name='projects_co_normali_22b99d_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordirectoryentry',
            index=models.Index(fields=['normalized_name', 'city', 'state'], name='projects_co_normali_ee3ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordirectorydiscovery',
            index=models.Index(fields=['source_type', 'created_at'], name='projects_co_source__880eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='contractordirectorydiscovery',
            index=models.Index(fields=['search_city', 'search_state', 'search_zip'], name='projects_co_search__073e43_idx'),
        ),
    ]
