# Generated by Codex on 2026-05-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0168_contractordirectoryentry_enrichment_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorOpportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("homeowner_name", models.CharField(blank=True, max_length=255, null=True)),
                ("homeowner_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("homeowner_phone", models.CharField(blank=True, max_length=50, null=True)),
                ("project_address", models.CharField(blank=True, max_length=255, null=True)),
                ("project_city", models.CharField(blank=True, max_length=120, null=True)),
                ("project_state", models.CharField(blank=True, max_length=60, null=True)),
                ("project_zip", models.CharField(blank=True, max_length=20, null=True)),
                ("project_type", models.CharField(blank=True, max_length=120, null=True)),
                ("project_subtype", models.CharField(blank=True, max_length=120, null=True)),
                ("project_title", models.CharField(blank=True, max_length=255, null=True)),
                ("project_description", models.TextField(blank=True, null=True)),
                ("refined_description", models.TextField(blank=True, null=True)),
                ("budget_min", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("budget_max", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("timeline", models.CharField(blank=True, max_length=120, null=True)),
                ("measurements", models.JSONField(blank=True, default=list)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("accepted", "Accepted"), ("declined", "Declined"), ("expired", "Expired"), ("converted", "Converted")], db_index=True, default="pending", max_length=20)),
                ("selected_by_homeowner", models.BooleanField(db_index=True, default=True)),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("conversion_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_by_contractor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="accepted_opportunities", to="projects.contractor")),
                ("converted_agreement", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contractor_opportunities", to="projects.agreement")),
                ("converted_customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contractor_opportunities", to="projects.homeowner")),
                ("directory_entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="opportunities", to="projects.contractordirectoryentry")),
                ("intake_request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contractor_opportunities", to="projects.projectintake")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="contractor_opportunities", to="projects.project")),
            ],
            options={
                "ordering": ["-selected_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="contractoropportunity",
            index=models.Index(fields=["directory_entry", "status"], name="projects_co_directo_6c6181_idx"),
        ),
        migrations.AddIndex(
            model_name="contractoropportunity",
            index=models.Index(fields=["intake_request", "status"], name="projects_co_intake__6af8e5_idx"),
        ),
        migrations.AddIndex(
            model_name="contractoropportunity",
            index=models.Index(fields=["project", "status"], name="projects_co_project_c3ba09_idx"),
        ),
        migrations.AddIndex(
            model_name="contractoropportunity",
            index=models.Index(fields=["status", "created_at"], name="projects_co_status_05f037_idx"),
        ),
        migrations.AddConstraint(
            model_name="contractoropportunity",
            constraint=models.UniqueConstraint(condition=models.Q(intake_request__isnull=False), fields=("directory_entry", "intake_request"), name="uniq_opportunity_directory_entry_intake"),
        ),
    ]
