# Generated by Codex on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0169_contractoropportunity"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="activation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("traditional_signup", "Traditional Signup"),
                    ("prefilled_directory", "Prefilled Directory"),
                    ("homeowner_selected", "Homeowner Selected"),
                ],
                db_index=True,
                max_length=40,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="has_completed_guided_activation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractor",
            name="has_seen_draft_agreement_intro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractor",
            name="has_seen_prefilled_profile_intro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractor",
            name="has_seen_public_leads_intro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contractor",
            name="first_draft_agreement_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="first_opportunity_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
