# Generated by Django 5.2.1 on 2026-05-17 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0170_contractor_activation_state"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contractoropportunity",
            new_name="projects_co_directo_803c8d_idx",
            old_name="projects_co_directo_6c6181_idx",
        ),
        migrations.RenameIndex(
            model_name="contractoropportunity",
            new_name="projects_co_intake__22ff47_idx",
            old_name="projects_co_intake__6af8e5_idx",
        ),
        migrations.RenameIndex(
            model_name="contractoropportunity",
            new_name="projects_co_project_126922_idx",
            old_name="projects_co_project_c3ba09_idx",
        ),
        migrations.RenameIndex(
            model_name="contractoropportunity",
            new_name="projects_co_status_6921cd_idx",
            old_name="projects_co_status_05f037_idx",
        ),
    ]
