# Generated by Django 5.2.1 on 2026-05-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0171_rename_projects_co_directo_6c6181_idx_projects_co_directo_803c8d_idx_and_more",
        ),
        ("projects", "0172_contractor_directory_service_normalization"),
    ]

    operations = []
