# Generated by Django 5.2.1 on 2026-05-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0173_contractordirectoryentry_archive"),
        (
            "projects",
            "0174_rename_projects_co_directo_803c8d_idx_projects_co_directo_6c6181_idx_and_more",
        ),
    ]

    operations = []
