# Generated by Django 5.2.1 on 2026-05-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0174_contractor_directory_contactability"),
        ("projects", "0175_merge_20260519_2349"),
    ]

    operations = []
