# Generated by Django 5.2.1 on 2026-05-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0176_merge_20260520_1300"),
        (
            "projects",
            "0176_notificationrule_smartnotification_notificationlog_and_more",
        ),
    ]

    operations = []
