# Generated by Django 5.2.1 on 2026-05-31 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0177_merge_20260524_0021"),
        ("projects", "0177_seed_core_trade_taxonomy"),
    ]

    operations = []
