# Generated by Django 5.2.13 on 2026-06-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0181_signed_agreement_snapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agreementdraftintelligencesnapshot',
            new_name='projects_ag_contrac_d0ce86_idx',
            old_name='projects_ag_contrac_5de7e1_idx',
        ),
        migrations.RenameIndex(
            model_name='agreementdraftintelligencesnapshot',
            new_name='projects_ag_templat_742c9e_idx',
            old_name='projects_ag_templat_2c1270_idx',
        ),
        migrations.RenameIndex(
            model_name='agreementdraftintelligencesnapshot',
            new_name='projects_ag_created_020f7a_idx',
            old_name='projects_ag_created_81e52c_idx',
        ),
        migrations.RenameIndex(
            model_name='contractoreditevent',
            new_name='projects_co_agreeme_a794ce_idx',
            old_name='projects_co_agreeme_1d735d_idx',
        ),
        migrations.RenameIndex(
            model_name='contractoreditevent',
            new_name='projects_co_contrac_2e132f_idx',
            old_name='projects_co_contrac_b480de_idx',
        ),
        migrations.RenameIndex(
            model_name='contractoreditevent',
            new_name='projects_co_source_ae9338_idx',
            old_name='projects_co_source_09ee32_idx',
        ),
        migrations.RenameIndex(
            model_name='contractoreditevent',
            new_name='projects_co_created_3f11e1_idx',
            old_name='projects_co_created_c1facd_idx',
        ),
        migrations.RenameIndex(
            model_name='milestoneperformancesnapshot',
            new_name='projects_mi_agreeme_a1d9c6_idx',
            old_name='projects_mi_agreeme_516d01_idx',
        ),
        migrations.RenameIndex(
            model_name='milestoneperformancesnapshot',
            new_name='projects_mi_contrac_311c09_idx',
            old_name='projects_mi_contrac_3112df_idx',
        ),
        migrations.RenameIndex(
            model_name='milestoneperformancesnapshot',
            new_name='projects_mi_normali_aca3d7_idx',
            old_name='projects_mi_normali_1f8046_idx',
        ),
        migrations.RenameIndex(
            model_name='milestoneperformancesnapshot',
            new_name='projects_mi_source__fd0788_idx',
            old_name='projects_mi_source__fbf6e5_idx',
        ),
        migrations.RenameIndex(
            model_name='milestoneperformancesnapshot',
            new_name='projects_mi_created_ab3404_idx',
            old_name='projects_mi_created_92c059_idx',
        ),
        migrations.RenameIndex(
            model_name='signedagreementsnapshot',
            new_name='projects_si_contrac_5215b8_idx',
            old_name='projects_si_contrac_c0d2d2_idx',
        ),
        migrations.RenameIndex(
            model_name='signedagreementsnapshot',
            new_name='projects_si_selecte_96de31_idx',
            old_name='projects_si_selecte_4cf537_idx',
        ),
        migrations.RenameIndex(
            model_name='signedagreementsnapshot',
            new_name='projects_si_draft_s_cbc3ed_idx',
            old_name='projects_si_draft__d07eb2_idx',
        ),
        migrations.RenameIndex(
            model_name='signedagreementsnapshot',
            new_name='projects_si_fully_s_945406_idx',
            old_name='projects_si_fully__7dce91_idx',
        ),
        migrations.RenameIndex(
            model_name='signedagreementsnapshot',
            new_name='projects_si_created_0899e9_idx',
            old_name='projects_si_created_9625b9_idx',
        ),
    ]
