# Generated by Django 5.2.1 on 2026-06-04 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0178_merge_20260530_2344"),
        ("projects", "0181_signed_agreement_snapshot"),
    ]

    operations = []
