# Generated by Django 5.2.1 on 2026-06-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0182_merge_20260604_0118"),
        (
            "projects",
            "0182_rename_projects_ag_contrac_5de7e1_idx_projects_ag_contrac_d0ce86_idx_and_more",
        ),
    ]

    operations = []
