# Generated by Django 5.2.1 on 2026-06-07 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0183_merge_20260604_0751"),
        ("projects", "0184_propertyprofile_is_primary"),
    ]

    operations = []
