# Generated by Django 5.2.13 on 2026-06-07 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0184_propertyprofile_is_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('state', models.CharField(db_index=True, max_length=60)),
                ('is_enabled', models.BooleanField(db_index=True, default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('min_claimed_contractors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_verified_contractors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_stripe_ready_contractors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('min_trade_categories', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_bids_per_request', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_location_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['state', 'city'],
                'indexes': [models.Index(fields=['state', 'city'], name='projects_ma_state_c_0f4c3d_idx'), models.Index(fields=['is_enabled', 'state'], name='projects_ma_enabled_74726d_idx')],
                'constraints': [models.UniqueConstraint(fields=('city', 'state'), name='uniq_marketplace_location_city_state')],
            },
        ),
    ]
