# Generated by Django 5.2.13 on 2026-06-07 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0185_marketplacelocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='available_escrow_at_approval',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='category',
            field=models.CharField(choices=[('materials', 'Materials'), ('permit', 'Permit'), ('rental', 'Rental'), ('delivery', 'Delivery'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='denial_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='denied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='escrow_source_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_requests', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='release_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='request_kind',
            field=models.CharField(choices=[('direct_expense', 'Direct Expense'), ('escrow_reimbursement', 'Escrow Reimbursement')], db_index=True, default='direct_expense', max_length=32),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_expense_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('contractor_signed', 'Contractor Signed'), ('sent_to_homeowner', 'Sent to Customer'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('pending_release', 'Pending Release'), ('released', 'Released'), ('homeowner_accepted', 'Customer Accepted'), ('homeowner_rejected', 'Customer Rejected'), ('paid', 'Paid')], db_index=True, default='draft', max_length=32),
        ),
    ]
