# Generated by Django 5.2.1 on 2026-06-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0185_marketplacelocation"),
        ("projects", "0185_merge_20260607_1101"),
    ]

    operations = []
