# Generated by Django 5.2.13 on 2026-06-08 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0186_expenserequest_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='held_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='held_expense_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='hold_cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='hold_cleared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_expense_request_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='hold_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('contractor_signed', 'Contractor Signed'), ('sent_to_homeowner', 'Sent to Customer'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('held', 'Held'), ('pending_release', 'Pending Release'), ('released', 'Released'), ('homeowner_accepted', 'Customer Accepted'), ('homeowner_rejected', 'Customer Rejected'), ('paid', 'Paid')], db_index=True, default='draft', max_length=32),
        ),
    ]
