# Generated by Django 5.2.13 on 2026-06-08 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0187_expenserequest_held_at_expenserequest_held_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='marketplace_preferred',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketplace_preferred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketplace_preferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_preferred_contractors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketplace_preferred_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketplace_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketplace_suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_suspended_contractors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketplace_verification_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketplace_verification_rejected_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketplace_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending_review', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='unverified', max_length=32),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketplace_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketplace_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_verified_contractors', to=settings.AUTH_USER_MODEL),
        ),
    ]
