# Generated by Django 5.2.13 on 2026-06-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0188_contractor_marketplace_preferred_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('subcontractor_comment', 'Subcontractor Comment'), ('subcontractor_file', 'Subcontractor File'), ('subcontractor_review', 'Subcontractor Review Request'), ('draw_approved', 'Draw Approved'), ('draw_changes_requested', 'Draw Changes Requested'), ('draw_paid', 'Draw Paid'), ('draw_released', 'Draw Released'), ('bid_awarded', 'Bid Awarded'), ('bid_not_selected', 'Bid Not Selected'), ('contractor_opportunity_received', 'Contractor Opportunity Received'), ('marketplace_verification_approved', 'Marketplace Verification Approved'), ('marketplace_verification_rejected', 'Marketplace Verification Rejected'), ('marketplace_verification_suspended', 'Marketplace Verification Suspended'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('quote_request_received', 'Quote Request Received'), ('agreement_signed', 'Agreement Signed'), ('escrow_funded', 'Escrow Funded'), ('invoice_approved', 'Invoice Approved'), ('milestone_pending_approval', 'Milestone Pending Approval'), ('payment_released', 'Payment Released')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('request_marketplace_ready', 'Request Marketplace Ready')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('request_marketplace_ready', 'Request Marketplace Ready')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='smartnotification',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('request_marketplace_ready', 'Request Marketplace Ready')], db_index=True, max_length=64),
        ),
    ]
