# Generated by Django 5.2.13 on 2026-06-08 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0190_alter_notification_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='disputed_remainder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='financial_disposition',
            field=models.CharField(blank=True, choices=[('eligible_for_release', 'Eligible for Release'), ('eligible_for_refund', 'Eligible for Refund'), ('partial_manual_review', 'Partial Manual Review'), ('manual_review_required', 'Manual Review Required'), ('no_financial_action', 'No Financial Action')], db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dispute',
            name='linked_rework_milestone_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('contractor_prevails', 'Contractor Prevails'), ('customer_prevails', 'Customer Prevails'), ('partial_resolution', 'Partial Resolution'), ('rework_required', 'Rework Required'), ('administrative_closure', 'Administrative Closure')], db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('open', 'Open'), ('under_review', 'Under Review'), ('resolved_contractor', 'Resolved - Contractor'), ('resolved_homeowner', 'Resolved - Homeowner'), ('resolved_partial', 'Resolved - Partial'), ('canceled', 'Canceled')], default='initiated', max_length=30),
        ),
    ]
