# Generated by Django 5.2.1 on 2026-06-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0186_merge_20260607_1247"),
        ("projects", "0190_alter_notification_event_type_and_more"),
    ]

    operations = []
