# Generated by Django 5.2.13 on 2026-06-08 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0191_dispute_approved_amount_dispute_disputed_remainder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorreview',
            name='customer_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contractorreview',
            name='homeowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_reviews', to='projects.homeowner'),
        ),
        migrations.AddField(
            model_name='contractorreview',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorreview',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_contractor_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorreview',
            name='moderation_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractorreview',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved / Published'), ('hidden', 'Hidden'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='contractorreview',
            name='project_subtype',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='contractorreview',
            name='project_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='contractorreview',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='contractorreview',
            constraint=models.UniqueConstraint(condition=models.Q(('agreement__isnull', False), models.Q(('customer_email', ''), _negated=True)), fields=('agreement', 'customer_email'), name='uniq_contractor_review_agreement_customer_email'),
        ),
    ]
