# Generated by Django 5.2.13 on 2026-06-09 01:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0193_backfill_contractor_review_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyIntelligenceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('health_status', models.CharField(blank=True, default='', max_length=32)),
                ('health_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.CharField(blank=True, default='', max_length=24)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('learning_summary', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('snapshot_version', models.PositiveSmallIntegerField(default=1)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('property_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_snapshots', to='projects.propertyprofile')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
                'indexes': [models.Index(fields=['customer_email', 'generated_at'], name='projects_pr_custome_bccff6_idx'), models.Index(fields=['health_status', 'generated_at'], name='projects_pr_health__a4861e_idx')],
                'unique_together': {('property_profile', 'content_hash')},
            },
        ),
    ]
