# Generated by Django 5.2.1 on 2026-06-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0191_merge_20260608_1059"),
        ("projects", "0194_propertyintelligencesnapshot"),
    ]

    operations = []
