# Generated by Django 5.2.13 on 2026-06-09 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0195_merge_20260609_0035'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorMarketplaceJoinInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('invited_business_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('partial', 'Partially Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('claimed', 'Claimed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=24)),
                ('delivery_channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email + SMS'), ('manual', 'Manual')], db_index=True, default='email', max_length=24)),
                ('email_status', models.CharField(blank=True, default='', max_length=40)),
                ('email_error', models.TextField(blank=True, default='')),
                ('sms_status', models.CharField(blank=True, default='', max_length=40)),
                ('sms_error', models.TextField(blank=True, default='')),
                ('sms_opted_out', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_join_invites', to='projects.contractordirectoryclaimtoken')),
                ('directory_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_join_invites', to='projects.contractordirectoryentry')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_marketplace_join_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['directory_entry', 'status'], name='projects_cm_join_d_4f9f1d_idx'), models.Index(fields=['status', 'sent_at'], name='projects_cm_join_s_2c1844_idx'), models.Index(fields=['email'], name='projects_cm_join_e_43ef21_idx'), models.Index(fields=['phone'], name='projects_cm_join_p_58df0a_idx')],
            },
        ),
    ]
