# Generated by Django 5.2.13 on 2026-06-10 17:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0198_customerrequest_project_type_subtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence_note', models.TextField(blank=True, default='')),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('refund_requested', 'Refund Requested'), ('contractor_response_needed', 'Contractor Response Needed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('denied', 'Denied'), ('refunded', 'Refunded')], db_index=True, default='refund_requested', max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_refund_requests', to='projects.agreement')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['agreement', 'status'], name='projects_cu_agreeme_3f3cf5_idx'), models.Index(fields=['created_at'], name='projects_cu_created_e0fb8f_idx')],
            },
        ),
    ]
