# Generated by Django 5.2.13 on 2026-06-10 17:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0199_customer_refund_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendmentrequest',
            name='escrow_funded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='estimated_refundable_escrow_surplus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='original_project_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='refund_eligibility_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('estimate_only', 'Estimate Only'), ('eligible_after_signed', 'Eligible After Signed Amendment'), ('eligible', 'Refund Eligible')], default='not_applicable', help_text='De-scope requests start as estimates. Eligibility is only created after the amendment/addendum is approved and signed.', max_length=64),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='refund_eligible_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='revised_project_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='amendmentrequest',
            name='change_type',
            field=models.CharField(choices=[('date_change', 'Date Change'), ('amount_change', 'Amount Change'), ('scope_product_change', 'Product/Scope Change'), ('descope_remove_work', 'De-scope / Remove Work'), ('other', 'Other')], default='other', max_length=64),
        ),
    ]
