# Generated by Django 5.2.13 on 2026-06-10 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0200_descope_amendment_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amendmentrequest',
            name='affected_milestones',
            field=models.ManyToManyField(blank=True, help_text='Milestones directly affected by this amendment request.', related_name='affected_amendment_requests', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='counter_proposal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='initiated_by_role',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_amendment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='response_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='amendmentrequest',
            name='response_state',
            field=models.CharField(choices=[('pending', 'Pending Response'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='milestone',
            name='amendment_review_request',
            field=models.ForeignKey(blank=True, help_text='Open amendment request currently blocking this milestone.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_milestones', to='projects.amendmentrequest'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='amendment_review_status',
            field=models.CharField(blank=True, db_index=True, default='', help_text='When set to pending, milestone completion/invoicing is blocked by an open amendment review.', max_length=32),
        ),
        migrations.CreateModel(
            name='ProjectActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_role', models.CharField(blank=True, default='', max_length=32)),
                ('recipient_role', models.CharField(blank=True, default='', max_length=32)),
                ('object_type', models.CharField(db_index=True, max_length=64)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('amendment_created', 'Amendment Created'), ('amendment_delivered', 'Amendment Delivered'), ('amendment_viewed', 'Amendment Viewed'), ('amendment_responded', 'Amendment Responded'), ('amendment_resolved', 'Amendment Resolved'), ('dispute_created', 'Dispute Created'), ('dispute_delivered', 'Dispute Delivered'), ('dispute_viewed', 'Dispute Viewed'), ('dispute_responded', 'Dispute Responded'), ('dispute_resolved', 'Dispute Resolved'), ('refund_eligible', 'Refund Eligible'), ('milestone_blocked', 'Milestone Blocked')], db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activity_events_created', to=settings.AUTH_USER_MODEL)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_activity_events', to='projects.agreement')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activity_events', to='projects.milestone')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activity_events_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['object_type', 'object_id', 'event_type'], name='projects_pr_object__dfa320_idx'), models.Index(fields=['agreement', 'created_at'], name='projects_pr_agreeme_a1eb9e_idx')],
            },
        ),
    ]
