# Generated by Django 5.2.13 on 2026-06-11 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0202_amendmentrequestattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyHomeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('hvac', 'HVAC'), ('roof', 'Roof'), ('water_heater', 'Water Heater'), ('electrical', 'Electrical Panel'), ('plumbing', 'Plumbing'), ('appliance', 'Appliances'), ('windows_doors', 'Windows/Doors'), ('foundation', 'Foundation/Basement'), ('exterior_siding', 'Exterior/Siding'), ('septic_sewer', 'Septic/Sewer'), ('solar', 'Solar'), ('pool_spa', 'Pool/Spa'), ('other', 'Other')], default='other', max_length=32)),
                ('custom_name', models.CharField(blank=True, default='', max_length=200)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200)),
                ('model_number', models.CharField(blank=True, default='', max_length=200)),
                ('serial_number', models.CharField(blank=True, default='', max_length=200)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_expiration_date', models.DateField(blank=True, null=True)),
                ('expected_lifespan_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('unknown', 'Unknown'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('needs_service', 'Needs Service'), ('replace_soon', 'Replace Soon')], default='unknown', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('service_provider', models.CharField(blank=True, default='', max_length=200)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['is_archived', 'system_type', 'custom_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='linked_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_home_systems', to='projects.agreement'),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='linked_customer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_home_systems', to='projects.customerrequest'),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='linked_documents',
            field=models.ManyToManyField(blank=True, related_name='home_systems', to='projects.propertydocument'),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='property_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_systems', to='projects.propertyprofile'),
        ),
        migrations.AddIndex(
            model_name='propertyhomesystem',
            index=models.Index(fields=['property_profile', 'is_archived', 'system_type'], name='projects_pr_propert_2f4188_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyhomesystem',
            index=models.Index(fields=['warranty_expiration_date'], name='projects_pr_warrant_bbbb70_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyhomesystem',
            index=models.Index(fields=['last_service_date'], name='projects_pr_last_se_799206_idx'),
        ),
    ]
