# Generated by Django 5.2.13 on 2026-06-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0203_property_home_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='amendmentrequestattachment',
            new_name='projects_am_agreeme_f49788_idx',
            old_name='projects_am_agreem_586219_idx',
        ),
        migrations.RenameIndex(
            model_name='amendmentrequestattachment',
            new_name='projects_am_amendme_8c7825_idx',
            old_name='projects_am_amendm_5ff3c4_idx',
        ),
    ]
