# Generated by Django 5.2.13 on 2026-06-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0204_normalize_amendment_attachment_index_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyhomesystem',
            name='dismissed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='email_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='next_notification_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='reminder_channel',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='reminder_delivery_status',
            field=models.CharField(blank=True, choices=[('', 'Not sent'), ('pending', 'Pending'), ('sent', 'Sent'), ('skipped', 'Skipped'), ('resolved', 'Resolved')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='reminder_frequency',
            field=models.CharField(choices=[('once', 'Once'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='once', max_length=16),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='reminder_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='reminder_lead_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='reminders_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyhomesystem',
            name='sms_reminders_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='smartnotification',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready')], db_index=True, max_length=64),
        ),
    ]
