# Generated by Django 5.2.13 on 2026-06-11 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0205_home_system_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='source_intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_customer_requests', to='projects.projectintake'),
        ),
    ]
