# Generated by Django 5.2.13 on 2026-06-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0210_home_system_recommendation_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartnotification',
            name='archive_reason',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='smartnotification',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='smartnotification',
            name='auto_archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='smartnotification',
            index=models.Index(fields=['recipient_email', 'archived_at'], name='projects_sm_recipie_1cc61f_idx'),
        ),
    ]
