# Generated by Django 5.2.13 on 2026-06-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0211_smart_notification_archive_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotificationCleanupPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('auto_archive_enabled', models.BooleanField(default=True)),
                ('auto_archive_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=16)),
                ('auto_archive_read_after_days', models.PositiveIntegerField(default=30)),
                ('auto_archive_maintenance_after_days', models.PositiveIntegerField(default=60)),
                ('auto_archive_completed_work_after_days', models.PositiveIntegerField(default=90)),
                ('last_auto_archive_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_auto_archive_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_cleanup_preferences', to='projects.homeowner')),
            ],
            options={
                'ordering': ['customer_email'],
                'indexes': [models.Index(fields=['auto_archive_enabled', 'next_auto_archive_run_at'], name='projects_cu_auto_ar_235eee_idx')],
            },
        ),
    ]
