# Generated by Django 5.2.13 on 2026-06-15 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0212_customer_notification_cleanup_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='upload_source',
            field=models.CharField(blank=True, choices=[('portal_desktop', 'Portal Desktop'), ('qr_mobile_web', 'QR Mobile Web'), ('mobile_app', 'Mobile App')], default='', max_length=32),
        ),
        migrations.CreateModel(
            name='CustomerPortalUploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=96, unique=True)),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('purpose', models.CharField(choices=[('home_system_document_scan', 'Home System Document Scan')], default='home_system_document_scan', max_length=48)),
                ('document_type', models.CharField(blank=True, default='', max_length=64)),
                ('upload_source', models.CharField(choices=[('portal_desktop', 'Portal Desktop'), ('qr_mobile_web', 'QR Mobile Web'), ('mobile_app', 'Mobile App')], default='qr_mobile_web', max_length=32)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='projects.propertyhomesystem')),
                ('property_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='projects.propertyprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['customer_email', 'expires_at'], name='projects_cu_custome_04dfe8_idx'), models.Index(fields=['property_profile', 'home_system'], name='projects_cu_propert_0cc8c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocumentExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('document_classification', models.CharField(blank=True, default='', max_length=80)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('suggested_fields', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('home_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_extractions', to='projects.propertyhomesystem')),
                ('property_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='projects.propertydocument')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['home_system', 'extraction_status'], name='projects_pr_home_sy_2265cf_idx'), models.Index(fields=['extraction_status', 'created_at'], name='projects_pr_extract_b0c282_idx')],
            },
        ),
    ]
