# Generated by Django 5.2.13 on 2026-06-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0213_home_system_document_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual / Homeowner'), ('property_management_company', 'Property Management Company')], db_index=True, default='individual', max_length=40),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='company_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='company_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='company_license_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='company_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='company_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='company_state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='company_street',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='company_unit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='company_website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homeowner',
            name='company_zip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
