# Generated by Django 5.2.13 on 2026-06-16 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0214_homeowner_account_type_homeowner_company_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyManagementStaffMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('maintenance_coordinator', 'Maintenance Coordinator'), ('accounting', 'Accounting'), ('viewer', 'Viewer')], db_index=True, default='viewer', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('disabled', 'Disabled')], db_index=True, default='invited', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company', 'name', 'email'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwnerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('mailing_address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(choices=[('sole_owner', 'Sole Owner'), ('co_owner', 'Co-Owner'), ('entity', 'Entity'), ('trust', 'Trust'), ('other', 'Other')], default='sole_owner', max_length=32)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['property_profile', '-is_primary', 'owner_contact__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_label', models.CharField(max_length=120)),
                ('unit_type', models.CharField(choices=[('whole_property', 'Whole Property'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('suite', 'Suite'), ('room', 'Room'), ('other', 'Other')], default='whole_property', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('vacant', 'Vacant'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=24)),
                ('access_notes', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['property_profile', 'unit_label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyManagementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('license_number', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeowner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property_management_company', to='projects.homeowner')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='propertyprofile',
            name='managed_by_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to='projects.propertymanagementcompany'),
        ),
        migrations.AddIndex(
            model_name='propertyprofile',
            index=models.Index(fields=['managed_by_company', 'updated_at'], name='projects_pr_managed_098224_idx'),
        ),
        migrations.AddField(
            model_name='propertymanagementstaffmembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_memberships', to='projects.propertymanagementcompany'),
        ),
        migrations.AddField(
            model_name='propertymanagementstaffmembership',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_management_staff_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyownercontact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_contacts', to='projects.propertymanagementcompany'),
        ),
        migrations.AddField(
            model_name='propertyownercontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_owner_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='owner_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_ownerships', to='projects.propertyownercontact'),
        ),
        migrations.AddField(
            model_name='propertyownership',
            name='property_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='projects.propertyprofile'),
        ),
        migrations.AddField(
            model_name='propertyunit',
            name='property_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.propertyprofile'),
        ),
        migrations.AddIndex(
            model_name='propertymanagementcompany',
            index=models.Index(fields=['name'], name='projects_pr_name_809c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymanagementcompany',
            index=models.Index(fields=['email'], name='projects_pr_email_ad8889_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymanagementcompany',
            index=models.Index(fields=['is_active', 'updated_at'], name='projects_pr_is_acti_409e04_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymanagementstaffmembership',
            index=models.Index(fields=['company', 'status'], name='projects_pr_company_20dee7_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymanagementstaffmembership',
            index=models.Index(fields=['company', 'role'], name='projects_pr_company_4fa1f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertymanagementstaffmembership',
            constraint=models.UniqueConstraint(fields=('company', 'email'), name='uniq_pm_staff_email_per_company'),
        ),
        migrations.AddIndex(
            model_name='propertyownercontact',
            index=models.Index(fields=['company', 'name'], name='projects_pr_company_29b15e_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyownercontact',
            index=models.Index(fields=['email'], name='projects_pr_email_b5212f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyownership',
            index=models.Index(fields=['property_profile', 'is_primary'], name='projects_pr_propert_fe6cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyownership',
            index=models.Index(fields=['owner_contact', 'ownership_type'], name='projects_pr_owner_c_99c148_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyownership',
            constraint=models.UniqueConstraint(fields=('property_profile', 'owner_contact'), name='uniq_property_owner_contact'),
        ),
        migrations.AddIndex(
            model_name='propertyunit',
            index=models.Index(fields=['property_profile', 'status'], name='projects_pr_propert_0c7633_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyunit',
            index=models.Index(fields=['unit_type', 'status'], name='projects_pr_unit_ty_7b57b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyunit',
            constraint=models.UniqueConstraint(fields=('property_profile', 'unit_label'), name='uniq_property_unit_label'),
        ),
    ]
