# Generated by Django 5.2.13 on 2026-06-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0215_propertymanagementstaffmembership_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('former', 'Former')], db_index=True, default='pending', max_length=24)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('maintenance_access_enabled', models.BooleanField(default=False)),
                ('portal_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='projects.propertymanagementcompany')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'email', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tenancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('former', 'Former')], db_index=True, default='pending', max_length=24)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='projects.propertyprofile')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenancies', to='projects.propertyunit')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancies', to='projects.tenant')),
            ],
            options={
                'ordering': ['property_profile', 'unit__unit_label', 'tenant__last_name', 'tenant__first_name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['company', 'status'], name='projects_te_company_fb7650_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['company', 'email'], name='projects_te_company_a7798c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['property_profile', 'status'], name='projects_te_propert_be47e5_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['unit', 'status'], name='projects_te_unit_id_00be9b_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['tenant', 'status'], name='projects_te_tenant__bb3ab8_idx'),
        ),
    ]
