# Generated by Django 5.2.13 on 2026-06-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0216_tenant_tenancy_tenant_projects_te_company_fb7650_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('submitted_by_phone', models.CharField(blank=True, default='', max_length=40)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('appliance', 'Appliance'), ('pest', 'Pest'), ('access_lock', 'Access / Lock'), ('safety', 'Safety'), ('general_repair', 'General Repair'), ('other', 'Other')], default='general_repair', max_length=32)),
                ('urgency', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('permission_to_enter', models.BooleanField(default=False)),
                ('pets_present', models.BooleanField(default=False)),
                ('preferred_access_times', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_info_requested', 'More Info Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=32)),
                ('manager_notes', models.TextField(blank=True, default='')),
                ('reviewed_by', models.EmailField(blank=True, default='', max_length=254)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_maintenance_requests', to='projects.propertyprofile')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='projects.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_maintenance_requests', to='projects.propertyunit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['property_profile', 'status'], name='projects_te_propert_e1ddd6_idx'), models.Index(fields=['unit', 'status'], name='projects_te_unit_id_e0e41a_idx'), models.Index(fields=['tenant', 'status'], name='projects_te_tenant__4d3ba6_idx'), models.Index(fields=['submitted_by_email', 'created_at'], name='projects_te_submitt_3fa7cf_idx')],
            },
        ),
    ]
