# Generated by Django 5.2.13 on 2026-06-16 21:00

import django.db.models.deletion
import projects.models_customer_portal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0217_tenantmaintenancerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMaintenanceRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models_customer_portal.tenant_maintenance_request_attachment_upload_path)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_by_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.tenantmaintenancerequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['tenant_request', 'created_at'], name='projects_te_tenant__b7b3a4_idx')],
            },
        ),
    ]
