# Generated by Django 5.2.13 on 2026-06-17 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0218_tenantmaintenancerequestattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(blank=True, default='', max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('appliance', 'Appliance'), ('pest', 'Pest'), ('access_lock', 'Access / Lock'), ('safety', 'Safety'), ('general_repair', 'General Repair'), ('other', 'Other')], default='general_repair', max_length=32)),
                ('priority', models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=24)),
                ('status', models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=24)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('created_by', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_property_work_orders', to='projects.propertymanagementstaffmembership')),
                ('property_management_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_work_orders', to='projects.propertymanagementcompany')),
                ('property_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_work_orders', to='projects.propertyprofile')),
                ('source_tenant_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_work_orders', to='projects.tenantmaintenancerequest')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_work_orders', to='projects.tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_work_orders', to='projects.propertyunit')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['property_management_company', 'status'], name='projects_pr_propert_461f95_idx'), models.Index(fields=['property_profile', 'status'], name='projects_pr_propert_fca5dd_idx'), models.Index(fields=['unit', 'status'], name='projects_pr_unit_id_d63079_idx'), models.Index(fields=['tenant', 'status'], name='projects_pr_tenant__be9683_idx'), models.Index(fields=['source_tenant_request', 'status'], name='projects_pr_source__aa126b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_tenant_request__isnull', False), ('status__in', ['open', 'scheduled', 'in_progress', 'waiting', 'completed'])), fields=('source_tenant_request',), name='unique_active_property_work_order_per_tenant_request')],
            },
        ),
    ]
