# Generated by Django 5.2.13 on 2026-06-17 05:35

import django.db.models.deletion
import projects.models_customer_portal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0219_propertyworkorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyWorkOrderActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('scheduled', 'Scheduled'), ('started', 'Started'), ('completed', 'Completed'), ('closed', 'Closed'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('attachment_added', 'Attachment Added')], db_index=True, max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('actor', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.propertyworkorder')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['work_order', 'created_at'], name='projects_pr_work_or_b1dae1_idx'), models.Index(fields=['activity_type', 'created_at'], name='projects_pr_activit_d0e18d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PropertyWorkOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models_customer_portal.property_work_order_attachment_upload_path)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.EmailField(blank=True, default='', max_length=254)),
                ('attachment_type', models.CharField(choices=[('general', 'General'), ('completion_photo', 'Completion Photo'), ('completion_document', 'Completion Document')], default='general', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.propertyworkorder')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['work_order', 'created_at'], name='projects_pr_work_or_391f8d_idx'), models.Index(fields=['attachment_type', 'created_at'], name='projects_pr_attachm_0d3c75_idx')],
            },
        ),
    ]
