# Generated by Django 5.2.13 on 2026-06-17 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0220_propertyworkorderactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyworkorder',
            name='assigned_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_property_work_orders', to='projects.contractor'),
        ),
        migrations.AddField(
            model_name='propertyworkorder',
            name='assignment_type',
            field=models.CharField(choices=[('internal_staff', 'Internal Staff'), ('vendor', 'Vendor'), ('marketplace_contractor', 'Marketplace Contractor')], db_index=True, default='internal_staff', max_length=32),
        ),
        migrations.CreateModel(
            name='PropertyVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trade_category', models.CharField(blank=True, default='', max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_management_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='projects.propertymanagementcompany')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='propertyworkorder',
            name='assigned_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_property_work_orders', to='projects.propertyvendor'),
        ),
        migrations.AddIndex(
            model_name='propertyworkorder',
            index=models.Index(fields=['assignment_type', 'status'], name='projects_pr_assignm_d9c5f6_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyworkorder',
            index=models.Index(fields=['assigned_vendor', 'status'], name='projects_pr_assigne_e338ba_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyworkorder',
            index=models.Index(fields=['assigned_contractor', 'status'], name='projects_pr_assigne_ab92ec_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvendor',
            index=models.Index(fields=['property_management_company', 'status'], name='projects_pr_propert_4b3376_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyvendor',
            index=models.Index(fields=['trade_category', 'status'], name='projects_pr_trade_c_12ee52_idx'),
        ),
    ]
