# Generated by Django 5.2.13 on 2026-06-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0221_propertyworkorder_assigned_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoropportunity',
            name='property_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_opportunities', to='projects.propertyworkorder'),
        ),
        migrations.AddField(
            model_name='propertyworkorder',
            name='marketplace_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyworkorder',
            name='marketplace_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyworkorder',
            name='marketplace_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='not_sent', max_length=24),
        ),
        migrations.AlterField(
            model_name='propertyworkorderactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('scheduled', 'Scheduled'), ('started', 'Started'), ('completed', 'Completed'), ('closed', 'Closed'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('attachment_added', 'Attachment Added'), ('marketplace_sent', 'Marketplace Sent'), ('marketplace_accepted', 'Marketplace Accepted'), ('marketplace_declined', 'Marketplace Declined'), ('marketplace_withdrawn', 'Marketplace Withdrawn')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='contractoropportunity',
            index=models.Index(fields=['property_work_order', 'status'], name='projects_co_propwo__8d3a91_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyworkorder',
            index=models.Index(fields=['marketplace_status', 'created_at'], name='projects_pr_marketp_135ed0_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractoropportunity',
            constraint=models.UniqueConstraint(condition=models.Q(('property_work_order__isnull', False)), fields=('directory_entry', 'property_work_order'), name='uniq_opportunity_directory_entry_property_work_order'),
        ),
    ]
