# Generated by Django 5.2.13 on 2026-06-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0222_contractoropportunity_property_work_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyworkorder',
            name='linked_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_property_work_orders', to='projects.agreement'),
        ),
        migrations.AddField(
            model_name='propertyworkorder',
            name='linked_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_property_work_orders', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='propertyworkorderactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('scheduled', 'Scheduled'), ('started', 'Started'), ('completed', 'Completed'), ('closed', 'Closed'), ('status_changed', 'Status Changed'), ('note_added', 'Note Added'), ('attachment_added', 'Attachment Added'), ('marketplace_sent', 'Marketplace Sent'), ('marketplace_accepted', 'Marketplace Accepted'), ('marketplace_declined', 'Marketplace Declined'), ('marketplace_withdrawn', 'Marketplace Withdrawn'), ('agreement_draft_created', 'Agreement Draft Created')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='propertyworkorder',
            index=models.Index(fields=['linked_agreement', 'status'], name='projects_pr_linked__12a939_idx'),
        ),
    ]
