# Generated by Django 5.2.13 on 2026-06-18 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0223_propertyworkorder_linked_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvendor',
            name='linked_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_vendor_links', to='projects.contractor'),
        ),
        migrations.AddField(
            model_name='propertyvendor',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertyvendor',
            name='vendor_source',
            field=models.CharField(choices=[('myhomebro_contractor', 'MyHomeBro Contractor'), ('local_business', 'Local Business'), ('manual', 'Manual Vendor')], db_index=True, default='manual', max_length=32),
        ),
        migrations.AddIndex(
            model_name='propertyvendor',
            index=models.Index(fields=['property_management_company', 'vendor_source'], name='projects_pr_propert_3f882c_idx'),
        ),
    ]
