# Generated by Django 5.2.13 on 2026-06-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0224_propertyvendor_linked_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyprofile',
            name='is_rental_property',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
