# Generated by Django 5.2.13 on 2026-06-22 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0225_propertyprofile_is_rental_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyWorkOrderRecipientInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_type', models.CharField(choices=[('myhomebro_contractor', 'MyHomeBro Contractor'), ('preferred_vendor', 'Preferred Vendor'), ('local_business', 'Local Business')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('no_contact', 'No Contact Info')], db_index=True, default='pending', max_length=24)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('trade_category', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('email_status', models.CharField(blank=True, default='', max_length=40)),
                ('sms_status', models.CharField(blank=True, default='', max_length=40)),
                ('delivery_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_work_order_recipient_invitations', to='projects.contractor')),
                ('directory_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_work_order_recipient_invitations', to='projects.contractordirectoryentry')),
                ('linked_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_recipient_invitations', to='projects.propertyvendor')),
                ('property_management_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_recipient_invitations', to='projects.propertymanagementcompany')),
                ('property_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_recipient_invitations', to='projects.propertyprofile')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_invitations', to='projects.propertyworkorder')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['work_order', 'status'], name='projects_pr_work_or_31ed95_idx'), models.Index(fields=['property_management_company', 'status'], name='projects_pr_propert_c68dfd_idx'), models.Index(fields=['recipient_type', 'status'], name='projects_pr_recipie_bf625e_idx')],
            },
        ),
    ]
