# Generated by Django 5.2.13 on 2026-06-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0226_propertyworkorderrecipientinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyworkorderrecipientinvitation',
            name='recipient_type',
            field=models.CharField(choices=[('myhomebro_contractor', 'MyHomeBro Contractor'), ('preferred_vendor', 'Preferred Vendor'), ('local_business', 'Local Business'), ('manual_vendor', 'Manual Vendor')], db_index=True, max_length=32),
        ),
    ]
