# Generated by Django 5.2.13 on 2026-06-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0227_alter_propertyworkorderrecipientinvitation_recipient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymanagementcompany',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='propertymanagementcompany',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='propertymanagementcompany',
            name='subscription_plan',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='propertymanagementcompany',
            name='subscription_status',
            field=models.CharField(choices=[('none', 'None'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('incomplete', 'Incomplete'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], db_index=True, default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='propertymanagementcompany',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertymanagementcompany',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='propertymanagementcompany',
            index=models.Index(fields=['subscription_status', 'updated_at'], name='projects_pr_subscri_ef7ce3_idx'),
        ),
    ]
