# Generated by Django 5.2.13 on 2026-06-23 02:49

import uuid
from django.db import migrations, models


def backfill_tenant_maintenance_status_tokens(apps, schema_editor):
    TenantMaintenanceRequest = apps.get_model('projects', 'TenantMaintenanceRequest')
    for row in TenantMaintenanceRequest.objects.filter(status_token__isnull=True).only('id', 'status_token').iterator():
        row.status_token = uuid.uuid4()
        row.save(update_fields=['status_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0228_propertymanagementcompany_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmaintenancerequest',
            name='status_token',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.RunPython(backfill_tenant_maintenance_status_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tenantmaintenancerequest',
            name='status_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready'), ('tenant_maintenance_request_submitted', 'Tenant Maintenance Request Submitted')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready'), ('tenant_maintenance_request_submitted', 'Tenant Maintenance Request Submitted')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='smartnotification',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready'), ('tenant_maintenance_request_submitted', 'Tenant Maintenance Request Submitted')], db_index=True, max_length=64),
        ),
    ]
