# Generated by Django 5.2.13 on 2026-06-23 06:09

import django.db.models.deletion
import projects.models_customer_portal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0229_tenantmaintenancerequest_status_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('sms', 'SMS'), ('email_stub', 'Email Stub'), ('sms_stub', 'SMS Stub')], db_index=True, default='in_app', max_length=24),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('sms', 'SMS'), ('email_stub', 'Email Stub'), ('sms_stub', 'SMS Stub')], db_index=True, default='in_app', max_length=24),
        ),
        migrations.AlterField(
            model_name='smartnotification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('sms', 'SMS'), ('email_stub', 'Email Stub'), ('sms_stub', 'SMS Stub')], db_index=True, default='in_app', max_length=24),
        ),
        migrations.CreateModel(
            name='CustomerNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('category_preferences', models.JSONField(blank=True, default=projects.models_customer_portal.default_customer_notification_categories)),
                ('channel_preferences', models.JSONField(blank=True, default=projects.models_customer_portal.default_customer_notification_channels)),
                ('frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('weekly_digest', 'Weekly Digest'), ('monthly_digest', 'Monthly Digest'), ('off', 'Off')], default='immediate', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_preferences', to='projects.homeowner')),
            ],
            options={
                'ordering': ['customer_email'],
            },
        ),
    ]
