# Generated by Django 5.2.13 on 2026-06-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0230_alter_notificationlog_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('paused', 'Paused')], db_index=True, default='draft', max_length=20)),
                ('template_key', models.CharField(choices=[('starter', 'Starter'), ('modern_trade', 'Modern Trade'), ('premium_home', 'Premium Home'), ('commercial', 'Commercial')], default='starter', max_length=32)),
                ('homepage_layout', models.JSONField(blank=True, default=dict)),
                ('published_snapshot', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='projects.contractor')),
                ('public_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='projects.contractorpublicprofile')),
            ],
            options={
                'ordering': ['contractor_id'],
            },
        ),
        migrations.CreateModel(
            name='ContractorWebsitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('services', 'Services'), ('gallery', 'Gallery'), ('reviews', 'Reviews'), ('contact', 'Contact')], db_index=True, max_length=32)),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_title', models.CharField(blank=True, default='', max_length=255)),
                ('seo_description', models.TextField(blank=True, default='')),
                ('content_blocks', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='projects.contractorwebsite')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('website', 'page_type'), name='uniq_website_page_type'), models.UniqueConstraint(fields=('website', 'slug'), name='uniq_website_page_slug')],
            },
        ),
    ]
