# Generated by Django 5.2.13 on 2026-07-03 04:04

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


TRADE_SKILLS = [
    "General Labor",
    "Carpentry",
    "Finish Carpentry",
    "Drywall",
    "Painting",
    "Flooring",
    "Roofing",
    "Plumbing",
    "Electrical",
    "HVAC",
    "Concrete",
    "Masonry",
    "Tile",
    "Cabinet Installation",
    "Landscaping",
    "Irrigation",
    "Tree Work",
    "Pressure Washing",
    "Demphasis",
    "Fencing",
    "Windows & Doors",
    "Gutters",
    "Demolition",
    "Cleanup",
    "Appliance Installation",
    "Smart Home",
    "Pool Service",
]


def seed_trade_skills(apps, schema_editor):
    Skill = apps.get_model("projects", "Skill")
    for name in TRADE_SKILLS:
        slug = slugify(name).replace("-", "_")
        if Skill.objects.filter(name__iexact=name).exists() or Skill.objects.filter(slug=slug).exists():
            continue
        Skill.objects.create(name=name, slug=slug)


def unseed_trade_skills(apps, schema_editor):
    # Keep catalog rows on rollback; they may already be used by contractors or employees.
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0234_customercommunicationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(choices=[('beginner', 'Beginner'), ('working', 'Working'), ('skilled', 'Skilled'), ('lead', 'Lead'), ('expert', 'Expert')], db_index=True, default='working', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_capabilities', to='projects.skill')),
                ('subaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='projects.contractorsubaccount')),
            ],
            options={
                'ordering': ['skill__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('subaccount', 'skill'), name='unique_employee_capability_per_skill')],
            },
        ),
        migrations.RunPython(seed_trade_skills, reverse_code=unseed_trade_skills),
    ]
