# Generated by Django 5.2.13 on 2026-07-03 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0235_employeecapability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewAssignmentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('opportunity', 'Opportunity'), ('agreement', 'Agreement')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft')], db_index=True, default='draft', max_length=24)),
                ('preview_snapshot', models.JSONField(blank=True, default=dict)),
                ('assignment_plan', models.JSONField(blank=True, default=dict)),
                ('apply_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignment_drafts', to='projects.contractor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crew_assignment_drafts', to=settings.AUTH_USER_MODEL)),
                ('source_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_assignment_drafts', to='projects.agreement')),
                ('source_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_assignment_drafts', to='projects.contractoropportunity')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['contractor', 'source_type', 'status'], name='projects_cr_contrac_e0c186_idx'), models.Index(fields=['contractor', 'created_at'], name='projects_cr_contrac_4766ba_idx')],
            },
        ),
    ]
