# Generated by Django 5.2.13 on 2026-07-03 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0236_crewassignmentdraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crewassignmentdraft',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewassignmentdraft',
            name='applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_crew_assignment_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crewassignmentdraft',
            name='apply_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='crewassignmentdraft',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied')], db_index=True, default='draft', max_length=24),
        ),
    ]
