# Generated by Django 5.2.13 on 2026-07-04 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0237_crewassignmentdraft_applied_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityEstimateAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('lead', 'Public Lead'), ('intake', 'Project Intake'), ('opportunity', 'Contractor Opportunity')], db_index=True, max_length=24)),
                ('opportunity_title', models.CharField(blank=True, default='', max_length=255)),
                ('opportunity_reference', models.CharField(blank=True, default='', max_length=80)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('service_location', models.CharField(blank=True, default='', max_length=500)),
                ('appointment_type', models.CharField(choices=[('phone_call', 'Phone Call'), ('video_call', 'Video Call'), ('in_person', 'In-Person Estimate')], max_length=24)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_estimate_appointments', to='projects.contractor')),
                ('contractor_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate_appointments', to='projects.contractoropportunity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_estimate_appointments', to=settings.AUTH_USER_MODEL)),
                ('project_intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate_appointments', to='projects.projectintake')),
                ('public_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate_appointments', to='projects.publiccontractorlead')),
            ],
            options={
                'ordering': ['-scheduled_start', '-id'],
                'indexes': [models.Index(fields=['contractor', 'scheduled_start'], name='projects_op_est_con_8f2d7d_idx'), models.Index(fields=['source_type', 'scheduled_start'], name='projects_op_est_sou_c7d6e4_idx')],
            },
        ),
    ]
