# Generated by Django 5.2.13 on 2026-07-04 19:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0238_opportunityestimateappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='incidentals_reserve_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional escrow incidentals reserve configured separately from milestone totals.', max_digits=10),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='funding_source',
            field=models.CharField(choices=[('reimbursement', 'Reimbursement'), ('incidentals_reserve', 'Incidentals Reserve')], db_index=True, default='reimbursement', help_text='How this expense is funded. Incidentals reserve is escrow-backed; reimbursement uses the existing direct-pay/customer approval workflow.', max_length=32),
        ),
    ]
