# Generated by Django 5.2.13 on 2026-07-04 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0239_agreement_incidentals_reserve_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='incurred_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
