# Generated by Django 5.2.13 on 2026-07-05 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0240_alter_expenserequest_incurred_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorEstimateAvailabilityWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='America/Chicago', max_length=64)),
                ('appointment_type', models.CharField(choices=[('phone_call', 'Phone Call'), ('video_call', 'Video Call'), ('in_person', 'In-Person Estimate')], default='in_person', max_length=24)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['contractor_id', 'weekday', 'start_time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='opportunityestimateappointment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunityestimateappointment',
            name='customer_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opportunityestimateappointment',
            name='decline_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opportunityestimateappointment',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunityestimateappointment',
            name='proposed_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunityestimateappointment',
            name='requested_by',
            field=models.CharField(choices=[('contractor', 'Contractor'), ('customer', 'Customer')], db_index=True, default='contractor', max_length=24),
        ),
        migrations.AddField(
            model_name='opportunityestimateappointment',
            name='timezone',
            field=models.CharField(blank=True, default='America/Chicago', max_length=64),
        ),
        migrations.AlterField(
            model_name='opportunityestimateappointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('proposed', 'Proposed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=24),
        ),
        migrations.AddIndex(
            model_name='opportunityestimateappointment',
            index=models.Index(fields=['contractor', 'status', 'scheduled_start'], name='projects_op_est_sta_705f8c_idx'),
        ),
        migrations.AddField(
            model_name='contractorestimateavailabilitywindow',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_availability_windows', to='projects.contractor'),
        ),
        migrations.AddIndex(
            model_name='contractorestimateavailabilitywindow',
            index=models.Index(fields=['contractor', 'is_active', 'weekday'], name='projects_est_avail_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractorestimateavailabilitywindow',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='projects_est_av_end_gt_start'),
        ),
    ]
