# Generated by Django 5.2.13 on 2026-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0241_contractorestimateavailabilitywindow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoropportunity',
            name='estimate_preference',
            field=models.CharField(blank=True, choices=[('', 'No Estimate Preference'), ('slot', 'Preferred Slot Requested'), ('flexible', 'Customer Flexible'), ('contact_later', 'Contact Later')], db_index=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='contractoropportunity',
            name='estimate_preference_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
