# Generated by Django 5.2.13 on 2026-07-05 16:40

import django.db.models.deletion
import projects.models_proposals
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0242_contractoropportunity_estimate_preference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('lead', 'Lead'), ('intake', 'Intake'), ('opportunity', 'Opportunity'), ('property_work_order', 'Property Work Order')], db_index=True, max_length=32)),
                ('source_id', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('site_visit', 'Site Visit'), ('in_progress', 'Proposal In Progress'), ('ready', 'Proposal Ready'), ('sent', 'Proposal Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revision_requested', 'Revision Requested'), ('expired', 'Expired'), ('converted', 'Converted')], db_index=True, default='draft', max_length=32)),
                ('project_title', models.CharField(blank=True, default='', max_length=255)),
                ('project_summary', models.TextField(blank=True, default='')),
                ('project_type', models.CharField(blank=True, default='', max_length=120)),
                ('project_subtype', models.CharField(blank=True, default='', max_length=120)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('customer_preferred_contact', models.CharField(blank=True, default='', max_length=40)),
                ('service_location', models.CharField(blank=True, default='', max_length=500)),
                ('site_visit_notes', models.TextField(blank=True, default='')),
                ('access_notes', models.TextField(blank=True, default='')),
                ('risk_notes', models.TextField(blank=True, default='')),
                ('customer_requests', models.TextField(blank=True, default='')),
                ('site_conditions', models.TextField(blank=True, default='')),
                ('quick_checklist', models.JSONField(blank=True, default=list)),
                ('included_work', models.TextField(blank=True, default='')),
                ('excluded_work', models.TextField(blank=True, default='')),
                ('assumptions', models.TextField(blank=True, default='')),
                ('allowances', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.contractor')),
                ('contractor_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='projects.contractoropportunity')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL)),
                ('estimate_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='projects.opportunityestimateappointment')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProposalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Proposal Created'), ('appointment_linked', 'Appointment Linked'), ('status_updated', 'Status Updated'), ('site_visit_updated', 'Site Visit Updated'), ('measurement_added', 'Measurement Added'), ('measurement_updated', 'Measurement Updated'), ('measurement_removed', 'Measurement Removed'), ('attachment_uploaded', 'Attachment Uploaded'), ('attachment_updated', 'Attachment Updated'), ('attachment_removed', 'Attachment Removed'), ('scope_edited', 'Scope Edited'), ('notes_edited', 'Notes Edited')], db_index=True, max_length=40)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_activity_events', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='projects.proposal')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProposalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document')], db_index=True, default='document', max_length=24)),
                ('category', models.CharField(choices=[('before', 'Before Photo'), ('reference', 'Reference Photo'), ('plan', 'Plan'), ('hoa', 'HOA Document'), ('customer_file', 'Customer File'), ('vendor_quote', 'Vendor Quote'), ('inspection', 'Inspection Document'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('file', models.FileField(upload_to=projects.models_proposals.proposal_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.proposal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_proposal_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProposalMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('location', models.CharField(blank=True, default='', max_length=160)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='projects.proposal')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['contractor', 'status'], name='projects_prop_con_status_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['source_type', 'source_id'], name='projects_prop_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('contractor', 'source_type', 'source_id'), name='uniq_proposal_contractor_source'),
        ),
    ]
