# Generated by Django 5.2.13 on 2026-07-06 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0243_proposal_proposalactivity_proposalattachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalactivity',
            name='event_type',
            field=models.CharField(choices=[('created', 'Proposal Created'), ('appointment_linked', 'Appointment Linked'), ('status_updated', 'Status Updated'), ('site_visit_updated', 'Site Visit Updated'), ('measurement_added', 'Measurement Added'), ('measurement_updated', 'Measurement Updated'), ('measurement_removed', 'Measurement Removed'), ('attachment_uploaded', 'Attachment Uploaded'), ('attachment_updated', 'Attachment Updated'), ('attachment_removed', 'Attachment Removed'), ('scope_edited', 'Scope Edited'), ('notes_edited', 'Notes Edited'), ('line_item_added', 'Line Item Added'), ('line_item_updated', 'Line Item Updated'), ('line_item_removed', 'Line Item Removed')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ProposalLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('labor', 'Labor'), ('materials', 'Materials'), ('equipment', 'Equipment'), ('subcontractor', 'Subcontractor'), ('incidentals_reserve', 'Incidentals Reserve'), ('tax', 'Tax'), ('discount', 'Discount'), ('allowance', 'Allowance'), ('other', 'Other')], db_index=True, default='labor', max_length=32)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(blank=True, default='', max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='projects.proposal')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['proposal', 'category'], name='projects_prop_line_cat_idx')],
            },
        ),
    ]
