# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0244_alter_proposalactivity_event_type_proposallineitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("lead", "Lead"),
                    ("intake", "Intake"),
                    ("opportunity", "Opportunity"),
                    ("property_work_order", "Property Work Order"),
                    ("dashboard", "Dashboard Estimate"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
