# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0245_alter_proposal_source_type_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="project_start_type",
            field=models.CharField(
                choices=[
                    ("asap", "ASAP"),
                    ("specific_date", "Specific Date"),
                    ("flexible", "Flexible"),
                ],
                db_index=True,
                default="flexible",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="project_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="project_completion_type",
            field=models.CharField(
                choices=[
                    ("no_deadline", "No Deadline"),
                    ("specific_date", "Specific Date"),
                    ("flexible", "Flexible"),
                ],
                db_index=True,
                default="no_deadline",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="project_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="scheduling_priority",
            field=models.CharField(
                choices=[
                    ("flexible", "Flexible"),
                    ("preferred", "Preferred"),
                    ("required", "Required"),
                ],
                db_index=True,
                default="flexible",
                max_length=24,
            ),
        ),
    ]
