# Generated by Django 5.2.13 on 2026-07-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0246_proposal_structured_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorsubaccount',
            name='annual_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contractorsubaccount',
            name='cost_basis',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('salary', 'Salary')], default='hourly', max_length=16),
        ),
        migrations.AddField(
            model_name='contractorsubaccount',
            name='hourly_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contractorsubaccount',
            name='labor_cost_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractorsubaccount',
            name='overtime_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='contractorsubaccount',
            name='standard_hours_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
