# Generated by Django 5.2.13 on 2026-07-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0247_contractorsubaccount_annual_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='planning_assumptions',
            field=models.JSONField(blank=True, default=dict, help_text='Advisory milestone planning snapshot captured from the Agreement Wizard. No assignments or schedules are created from this field.'),
        ),
    ]
