# Generated by Django 5.2.13 on 2026-07-06 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0248_agreement_planning_assumptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='planning_validation_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='planning_validation_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_agreement_planning_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agreement',
            name='planning_validation_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='planning_validation_status',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Internal advisory timeline validation status. Customer-facing portals must not expose this field.', max_length=24),
        ),
        migrations.AddField(
            model_name='agreement',
            name='planning_validation_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
