# Generated by Django 5.2.13 on 2026-07-08 00:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_resolution_case_source(apps, schema_editor):
    Dispute = apps.get_model('projects', 'Dispute')
    Agreement = apps.get_model('projects', 'Agreement')
    agreement_project_ids = dict(Agreement.objects.values_list('id', 'project_id'))
    for dispute in Dispute.objects.all().only('id', 'agreement_id', 'milestone_id', 'project_id', 'source_type', 'source_object_id'):
        updates = {}
        if not dispute.project_id:
            project_id = agreement_project_ids.get(dispute.agreement_id)
            if project_id:
                updates['project_id'] = project_id
        if dispute.milestone_id:
            updates['source_type'] = 'milestone'
            updates['source_object_id'] = dispute.milestone_id
        else:
            updates['source_type'] = dispute.source_type or 'agreement'
            updates['source_object_id'] = dispute.source_object_id or dispute.agreement_id
        if updates:
            Dispute.objects.filter(id=dispute.id).update(**updates)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0249_agreement_planning_validation_acknowledged_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='amendment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_cases', to='projects.agreementamendment'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='draw_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_cases', to='projects.drawrequest'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_cases', to='projects.expense'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='payment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_cases', to='projects.invoice'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_cases', to='projects.project'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='source_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='source_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='source_type',
            field=models.CharField(choices=[('agreement', 'Agreement'), ('milestone', 'Milestone'), ('payment_request', 'Payment Request'), ('expense', 'Expense'), ('amendment', 'Amendment'), ('warranty_request', 'Warranty Request'), ('general_project_issue', 'General Project Issue')], db_index=True, default='agreement', max_length=40),
        ),
        migrations.AddField(
            model_name='dispute',
            name='warranty_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_cases', to='projects.agreementwarranty'),
        ),
        migrations.RunPython(backfill_resolution_case_source, noop_reverse),
        migrations.CreateModel(
            name='ResolutionAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, default='', max_length=40)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('problem_statement', models.TextField(blank=True, default='')),
                ('disputed_facts', models.JSONField(blank=True, default=list)),
                ('undisputed_facts', models.JSONField(blank=True, default=list)),
                ('agreed_solution', models.TextField()),
                ('required_actions', models.JSONField(blank=True, default=list)),
                ('deadlines', models.JSONField(blank=True, default=list)),
                ('payment_changes', models.JSONField(blank=True, default=dict)),
                ('warranty_impact', models.TextField(blank=True, default='')),
                ('future_obligations', models.TextField(blank=True, default='')),
                ('evidence_reviewed', models.JSONField(blank=True, default=list)),
                ('human_decision_summary', models.TextField(blank=True, default='')),
                ('audit_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_signature', 'Ready for Signature'), ('partially_signed', 'Partially Signed'), ('signed', 'Signed'), ('void', 'Void')], db_index=True, default='draft', max_length=32)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_agreements', to='projects.agreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resolution_agreements', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_agreements', to='projects.dispute')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_agreements', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pdf_package', 'PDF Package'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='resolution_cases/%Y/%m/')),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_documents', to='projects.dispute')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_resolution_documents', to=settings.AUTH_USER_MODEL)),
                ('resolution_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.resolutionagreement')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField(blank=True, default='')),
                ('proposed_solution', models.TextField()),
                ('required_actions', models.JSONField(blank=True, default=list)),
                ('deadlines', models.JSONField(blank=True, default=list)),
                ('payment_impact', models.JSONField(blank=True, default=dict)),
                ('warranty_impact', models.TextField(blank=True, default='')),
                ('evidence_relied_upon', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('accepted_by_customer', 'Accepted by Customer'), ('accepted_by_contractor', 'Accepted by Contractor'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('ready_for_signature', 'Ready for Signature'), ('signed', 'Signed'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=40)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_proposals', to='projects.dispute')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='resolutionagreement',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_agreements', to='projects.resolutionproposal'),
        ),
        migrations.CreateModel(
            name='ResolutionAgreementSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_role', models.CharField(choices=[('customer', 'Customer'), ('contractor', 'Contractor'), ('admin', 'Admin')], db_index=True, max_length=24)),
                ('signer_name', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('signature_text', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolution_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='projects.resolutionagreement')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_agreement_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signed_at', 'id'],
                'unique_together': {('resolution_agreement', 'signer_role')},
            },
        ),
        migrations.CreateModel(
            name='ResolutionCaseAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_audit_events', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='projects.dispute')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['dispute', 'action'], name='projects_re_dispute_6879fe_idx'), models.Index(fields=['dispute', 'occurred_at'], name='projects_re_dispute_ffed0c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResolutionCaseTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('case_created', 'Case Created'), ('evidence_uploaded', 'Evidence Uploaded'), ('statement_submitted', 'Statement Submitted'), ('resolution_proposed', 'Resolution Proposed'), ('evidence_requested', 'Evidence Requested'), ('payment_hold_applied', 'Payment Hold Applied'), ('payment_hold_released', 'Payment Hold Released'), ('human_decision_recorded', 'Human Decision Recorded'), ('agreement_signed', 'Agreement Signed'), ('pdf_generated', 'PDF Generated'), ('case_closed', 'Case Closed'), ('case_reopened', 'Case Reopened'), ('ai_analysis_updated', 'AI Analysis Updated'), ('manual', 'Manual Entry')], db_index=True, max_length=48)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=80)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('all_parties', 'All Parties'), ('admin_only', 'Admin Only')], db_index=True, default='all_parties', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='projects.dispute')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['dispute', 'event_type'], name='projects_re_dispute_b05b96_idx'), models.Index(fields=['dispute', 'occurred_at'], name='projects_re_dispute_830eea_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResolutionEvidenceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('receipt', 'Receipt'), ('invoice', 'Invoice'), ('message', 'Message'), ('agreement', 'Agreement'), ('amendment', 'Amendment'), ('inspection_report', 'Inspection Report'), ('warranty_document', 'Warranty Document'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('related_party', models.CharField(blank=True, db_index=True, default='', max_length=24)),
                ('related_source_type', models.CharField(blank=True, default='', max_length=80)),
                ('related_source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('all_parties', 'All Parties'), ('admin_only', 'Admin Only')], db_index=True, default='all_parties', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('attachment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_record', to='projects.disputeattachment')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_index', to='projects.dispute')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
                'indexes': [models.Index(fields=['dispute', 'category'], name='projects_re_dispute_9c037e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResolutionPartyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_type', models.CharField(choices=[('customer_statement', 'Customer Statement'), ('contractor_statement', 'Contractor Statement'), ('admin_internal_note', 'Admin Internal Note')], db_index=True, max_length=32)),
                ('party_role', models.CharField(choices=[('customer', 'Customer'), ('contractor', 'Contractor'), ('admin', 'Admin')], db_index=True, max_length=24)),
                ('text', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('visibility', models.CharField(choices=[('all_parties', 'All Parties'), ('admin_only', 'Admin Only')], db_index=True, default='all_parties', max_length=24)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_statements', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_statements', to='projects.dispute')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='projects.resolutionpartystatement')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['dispute', 'party_role', 'is_current'], name='projects_re_dispute_8b753b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='resolutionproposal',
            index=models.Index(fields=['dispute', 'status'], name='projects_re_dispute_f04d04_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionagreement',
            index=models.Index(fields=['dispute', 'status'], name='projects_re_dispute_21c878_idx'),
        ),
    ]
