# Generated by Django 5.2.13 on 2026-07-08 01:48

import django.db.models.deletion
import django.utils.timezone
import projects.models_warranty
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0250_dispute_amendment_dispute_draw_request_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementwarranty',
            name='completion_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='contractor_responsibilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='covered_work',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='customer_responsibilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='excluded_work',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='generated_from_agreement_completion',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='labor_duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='manufacturer_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='materials_duration_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='response_time_expectations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='workmanship_duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.CreateModel(
            name='WarrantyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_noticed', models.DateField(blank=True, null=True)),
                ('area_affected', models.CharField(blank=True, default='', max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='normal', max_length=20)),
                ('urgency', models.CharField(blank=True, default='', max_length=40)),
                ('other_contractor_worked', models.BooleanField(default=False)),
                ('preferred_scheduling', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_requested', 'More Information Requested'), ('inspection_scheduled', 'Inspection Scheduled'), ('inspection_complete', 'Inspection Complete'), ('covered', 'Covered'), ('partially_covered', 'Partially Covered'), ('not_covered', 'Not Covered'), ('repair_scheduled', 'Repair Scheduled'), ('repair_in_progress', 'Repair In Progress'), ('waiting_on_customer', 'Waiting On Customer'), ('waiting_on_materials', 'Waiting On Materials'), ('completed', 'Completed'), ('denied', 'Denied'), ('escalated_to_resolution', 'Escalated To Resolution'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=40)),
                ('coverage_decision', models.CharField(blank=True, default='', max_length=40)),
                ('contractor_response', models.TextField(blank=True, default='')),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('ai_review', models.JSONField(blank=True, default=dict)),
                ('submitted_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_dispute_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('source_context', models.JSONField(blank=True, default=dict)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_requests', to='projects.agreement')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_requests', to='projects.contractor')),
                ('homeowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_requests', to='projects.homeowner')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_requests', to='projects.project')),
                ('property_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_requests', to='projects.propertyprofile')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_warranty_requests', to=settings.AUTH_USER_MODEL)),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='projects.agreementwarranty')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='dispute',
            name='warranty_service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_cases', to='projects.warrantyrequest'),
        ),
        migrations.CreateModel(
            name='WarrantyRequestEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=projects.models_warranty.warranty_evidence_upload_path)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], db_index=True, default='other', max_length=24)),
                ('description', models.TextField(blank=True, default='')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_evidence', to=settings.AUTH_USER_MODEL)),
                ('warranty_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.warrantyrequest')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyRequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=40)),
                ('to_status', models.CharField(db_index=True, max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('actor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_status_events', to=settings.AUTH_USER_MODEL)),
                ('warranty_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='projects.warrantyrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('scope', models.TextField()),
                ('assigned_team_notes', models.TextField(blank=True, default='')),
                ('materials', models.TextField(blank=True, default='')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('labor_estimate_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('customer_notes', models.TextField(blank=True, default='')),
                ('completion_checklist', models.JSONField(blank=True, default=list)),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('repair_outcome', models.TextField(blank=True, default='')),
                ('customer_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=24)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_work_orders', to='projects.agreement')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_warranty_work_orders', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_work_orders', to='projects.contractor')),
                ('linked_property_work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_work_orders', to='projects.propertyworkorder')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_work_orders', to='projects.project')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='projects.agreementwarranty')),
                ('warranty_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='projects.warrantyrequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='warrantyrequest',
            index=models.Index(fields=['contractor', 'status'], name='projects_wa_contrac_b63f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyrequest',
            index=models.Index(fields=['agreement', 'status'], name='projects_wa_agreeme_81a983_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyrequest',
            index=models.Index(fields=['warranty', 'status'], name='projects_wa_warrant_2b8eb7_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyrequest',
            index=models.Index(fields=['property_profile', 'status'], name='projects_wa_propert_2fb7c4_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyworkorder',
            index=models.Index(fields=['contractor', 'status'], name='projects_wa_contrac_990e56_idx'),
        ),
        migrations.AddIndex(
            model_name='warrantyworkorder',
            index=models.Index(fields=['scheduled_for', 'status'], name='projects_wa_schedul_885c94_idx'),
        ),
    ]
