# Generated by Django 5.2.13 on 2026-07-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0251_agreementwarranty_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyrequest',
            name='customer_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantyrequest',
            name='customer_acknowledgment_response',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='warrantyrequest',
            name='next_expected_action',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='warrantyrequest',
            name='response_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='warrantyrequest',
            name='unresolved_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='warrantyworkorder',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('warranty_request_received', 'Warranty Request Received'), ('warranty_information_requested', 'Warranty Information Requested'), ('warranty_inspection_scheduled', 'Warranty Inspection Scheduled'), ('warranty_coverage_decision', 'Warranty Coverage Decision'), ('warranty_repair_scheduled', 'Warranty Repair Scheduled'), ('warranty_repair_completed', 'Warranty Repair Completed'), ('warranty_acknowledgment_requested', 'Warranty Acknowledgment Requested'), ('warranty_closed', 'Warranty Closed'), ('warranty_escalated', 'Warranty Escalated'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready'), ('tenant_maintenance_request_submitted', 'Tenant Maintenance Request Submitted')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('warranty_request_received', 'Warranty Request Received'), ('warranty_information_requested', 'Warranty Information Requested'), ('warranty_inspection_scheduled', 'Warranty Inspection Scheduled'), ('warranty_coverage_decision', 'Warranty Coverage Decision'), ('warranty_repair_scheduled', 'Warranty Repair Scheduled'), ('warranty_repair_completed', 'Warranty Repair Completed'), ('warranty_acknowledgment_requested', 'Warranty Acknowledgment Requested'), ('warranty_closed', 'Warranty Closed'), ('warranty_escalated', 'Warranty Escalated'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready'), ('tenant_maintenance_request_submitted', 'Tenant Maintenance Request Submitted')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='smartnotification',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('warranty_request_received', 'Warranty Request Received'), ('warranty_information_requested', 'Warranty Information Requested'), ('warranty_inspection_scheduled', 'Warranty Inspection Scheduled'), ('warranty_coverage_decision', 'Warranty Coverage Decision'), ('warranty_repair_scheduled', 'Warranty Repair Scheduled'), ('warranty_repair_completed', 'Warranty Repair Completed'), ('warranty_acknowledgment_requested', 'Warranty Acknowledgment Requested'), ('warranty_closed', 'Warranty Closed'), ('warranty_escalated', 'Warranty Escalated'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready'), ('tenant_maintenance_request_submitted', 'Tenant Maintenance Request Submitted')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='warrantyrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('more_information_requested', 'More Information Requested'), ('inspection_scheduled', 'Inspection Scheduled'), ('inspection_complete', 'Inspection Complete'), ('covered', 'Covered'), ('partially_covered', 'Partially Covered'), ('not_covered', 'Not Covered'), ('repair_scheduled', 'Repair Scheduled'), ('repair_in_progress', 'Repair In Progress'), ('waiting_on_customer', 'Waiting On Customer'), ('waiting_on_materials', 'Waiting On Materials'), ('acknowledgment_requested', 'Acknowledgment Requested'), ('follow_up_needed', 'Follow-Up Needed'), ('completed', 'Completed'), ('denied', 'Denied'), ('escalated_to_resolution', 'Escalated To Resolution'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=40),
        ),
    ]
