# Generated by Django 5.2.13 on 2026-07-09 23:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0252_warrantyrequest_customer_acknowledged_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssistantCaptureSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=24)),
                ('intent', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('source_text', models.TextField(blank=True, default='')),
                ('conversation_payload', models.JSONField(blank=True, default=dict)),
                ('prepared_payload', models.JSONField(blank=True, default=dict)),
                ('audit_metadata', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assistant_capture_sessions', to='projects.contractor')),
                ('created_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assistant_capture_sessions', to='projects.homeowner')),
                ('created_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assistant_capture_sessions', to='projects.customercommunicationlog')),
                ('created_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assistant_capture_sessions', to='projects.contractoropportunity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assistant_capture_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['contractor', 'status', '-updated_at'], name='projects_pr_contrac_5e44f8_idx'), models.Index(fields=['contractor', 'intent', '-updated_at'], name='projects_pr_contrac_397074_idx')],
            },
        ),
    ]
