# Generated by Django 5.2.13 on 2026-07-10 06:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0253_projectassistantcapturesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssistantPreparedAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('schedule_estimate', 'Schedule Estimate'), ('send_email', 'Send Email'), ('send_sms', 'Send SMS'), ('create_reminder', 'Create Reminder'), ('navigate', 'Navigate'), ('save_draft', 'Save Draft')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('drafted', 'Drafted'), ('ready_to_review', 'Ready To Review'), ('requires_approval', 'Requires Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='drafted', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('prepared_payload', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('source_records', models.JSONField(blank=True, default=list)),
                ('requires_approval', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_result', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('audit_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_assistant_prepared_actions', to=settings.AUTH_USER_MODEL)),
                ('capture_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_actions', to='projects.projectassistantcapturesession')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assistant_prepared_actions', to='projects.contractor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assistant_prepared_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['contractor', 'status', '-updated_at'], name='pa_action_status_idx'), models.Index(fields=['capture_session', 'action_type'], name='pa_action_session_type_idx')],
            },
        ),
    ]
