# Generated by Django 5.2.13 on 2026-07-10 06:59

import django.db.models.deletion
import projects.models_smart_capture
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0254_project_assistant_prepared_actions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('contractor_equipment', 'Contractor Equipment'), ('project_material', 'Project Material / Installed Product'), ('customer_property_record', 'Customer Property Record'), ('draft_only', 'Draft Only')], db_index=True, default='contractor_equipment', max_length=40)),
                ('asset_type', models.CharField(blank=True, default='', max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200)),
                ('model_number', models.CharField(blank=True, default='', max_length=200)),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('sku', models.CharField(blank=True, default='', max_length=120)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('current_location', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], db_index=True, default='active', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_assets', to='projects.agreement')),
                ('assigned_team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='projects.contractorsubaccount')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.contractor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contractor_assets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_assets', to='projects.homeowner')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_assets', to='projects.milestone')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_assets', to='projects.project')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_assets', to='projects.propertyprofile')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssistantSmartCaptureSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capture_type', models.CharField(choices=[('receipt', 'Receipt'), ('equipment_label', 'Equipment Label'), ('product_label', 'Product Label')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('review_ready', 'Review Ready'), ('needs_information', 'Needs Information'), ('approved', 'Approved'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='uploaded', max_length=32)),
                ('original_file', models.FileField(upload_to=projects.models_smart_capture.smart_capture_upload_path)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('raw_extracted_text', models.TextField(blank=True, default='')),
                ('structured_payload', models.JSONField(blank=True, default=dict)),
                ('field_confidence', models.JSONField(blank=True, default=dict)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('possible_matches', models.JSONField(blank=True, default=list)),
                ('approved_payload', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('audit_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_capture_sessions', to='projects.contractor')),
                ('created_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_capture_sessions', to='projects.contractorasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_assistant_smart_capture_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_capture_sessions', to='projects.expenserequest')),
                ('created_property_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_capture_sessions', to='projects.propertyhomesystem')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contractorasset',
            name='source_capture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_records', to='projects.projectassistantsmartcapturesession'),
        ),
        migrations.AddIndex(
            model_name='projectassistantsmartcapturesession',
            index=models.Index(fields=['contractor', 'capture_type', 'status'], name='pa_smart_capture_idx'),
        ),
        migrations.AddIndex(
            model_name='projectassistantsmartcapturesession',
            index=models.Index(fields=['contractor', 'file_sha256'], name='pa_smart_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorasset',
            index=models.Index(fields=['contractor', 'owner_type', 'status'], name='contractor_asset_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorasset',
            index=models.Index(fields=['contractor', 'serial_number'], name='contractor_asset_serial_idx'),
        ),
    ]
