# Generated by Django 5.2.13 on 2026-07-12 03:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0255_project_assistant_smart_capture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('smart_capture_receipt', 'Smart Capture Receipt'), ('smart_capture_equipment', 'Smart Capture Equipment'), ('smart_capture_product_label', 'Smart Capture Product Label')], db_index=True, max_length=80)),
                ('provider', models.CharField(db_index=True, max_length=40)),
                ('model', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('source_type', models.CharField(blank=True, default='', max_length=80)),
                ('source_id', models.CharField(blank=True, default='', max_length=120)),
                ('input_units', models.PositiveIntegerField(default=0)),
                ('output_units', models.PositiveIntegerField(default=0)),
                ('internal_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('billable_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('billing_status', models.CharField(choices=[('unbilled', 'Unbilled'), ('not_billable', 'Not Billable')], db_index=True, default='not_billable', max_length=32)),
                ('provider_request_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('failure_code', models.CharField(blank=True, default='', max_length=80)),
                ('cache_hit', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='projectassistantsmartcapturesession',
            name='extraction_cache_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectassistantsmartcapturesession',
            name='extraction_model',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='projectassistantsmartcapturesession',
            name='extraction_prompt_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='projectassistantsmartcapturesession',
            name='extraction_provider',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddIndex(
            model_name='projectassistantsmartcapturesession',
            index=models.Index(fields=['contractor', 'extraction_cache_key'], name='pa_smart_cache_idx'),
        ),
        migrations.AddField(
            model_name='aiusageledger',
            name='capture_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_ledger_entries', to='projects.projectassistantsmartcapturesession'),
        ),
        migrations.AddField(
            model_name='aiusageledger',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_ledger_entries', to='projects.contractor'),
        ),
        migrations.AddField(
            model_name='aiusageledger',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiusageledger',
            index=models.Index(fields=['contractor', 'feature', '-created_at'], name='ai_usage_feature_idx'),
        ),
        migrations.AddIndex(
            model_name='aiusageledger',
            index=models.Index(fields=['provider', 'model', 'success'], name='ai_usage_provider_idx'),
        ),
    ]
