# Generated by Django 5.2.13 on 2026-07-13 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0256_smart_capture_openai_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusageledger',
            name='customer_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='aiusageledger',
            name='property_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_ledger_entries', to='projects.propertyprofile'),
        ),
        migrations.AddField(
            model_name='projectassistantsmartcapturesession',
            name='customer_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='projectassistantsmartcapturesession',
            name='property_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_capture_sessions', to='projects.propertyprofile'),
        ),
        migrations.AlterField(
            model_name='aiusageledger',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_ledger_entries', to='projects.contractor'),
        ),
        migrations.AlterField(
            model_name='aiusageledger',
            name='feature',
            field=models.CharField(choices=[('smart_capture_receipt', 'Smart Capture Receipt'), ('smart_capture_equipment', 'Smart Capture Equipment'), ('smart_capture_product_label', 'Smart Capture Product Label'), ('smart_capture_home_system', 'Smart Capture Home System'), ('smart_capture_appliance', 'Smart Capture Appliance'), ('smart_capture_property_receipt', 'Smart Capture Property Receipt'), ('smart_capture_warranty', 'Smart Capture Warranty'), ('smart_capture_manual', 'Smart Capture Manual'), ('smart_capture_paint_finish', 'Smart Capture Paint Finish'), ('smart_capture_flooring_material', 'Smart Capture Flooring Material'), ('smart_capture_property_photo', 'Smart Capture Property Photo')], db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='projectassistantsmartcapturesession',
            name='capture_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('equipment_label', 'Equipment Label'), ('product_label', 'Product Label'), ('home_system_label', 'Home System Label'), ('appliance_label', 'Appliance Label'), ('installed_product_label', 'Installed Product Label'), ('property_receipt', 'Property Receipt'), ('warranty_document', 'Warranty Document'), ('manual_document', 'Manual Document'), ('paint_or_finish_label', 'Paint or Finish Label'), ('flooring_or_material_label', 'Flooring or Material Label'), ('property_photo', 'Property Photo')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='projectassistantsmartcapturesession',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_capture_sessions', to='projects.contractor'),
        ),
        migrations.CreateModel(
            name='PropertyIntelligenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('source_type', models.CharField(blank=True, default='smart_capture', max_length=80)),
                ('record_type', models.CharField(choices=[('home_system', 'Home System'), ('appliance', 'Appliance'), ('installed_product', 'Installed Product'), ('paint_finish', 'Paint or Finish'), ('flooring_material', 'Flooring or Material'), ('receipt', 'Receipt'), ('warranty', 'Warranty'), ('manual', 'Manual'), ('photo', 'Photo'), ('maintenance_record', 'Maintenance Record')], db_index=True, max_length=40)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200)),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('model_number', models.CharField(blank=True, default='', max_length=200)),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('sku', models.CharField(blank=True, default='', max_length=120)),
                ('barcode', models.CharField(blank=True, default='', max_length=120)),
                ('room_or_location', models.CharField(blank=True, default='', max_length=200)),
                ('system_type', models.CharField(blank=True, default='', max_length=80)),
                ('product_type', models.CharField(blank=True, default='', max_length=80)),
                ('color_name', models.CharField(blank=True, default='', max_length=120)),
                ('color_code', models.CharField(blank=True, default='', max_length=120)),
                ('finish', models.CharField(blank=True, default='', max_length=120)),
                ('material', models.CharField(blank=True, default='', max_length=120)),
                ('lot_or_batch_number', models.CharField(blank=True, default='', max_length=120)),
                ('capacity', models.CharField(blank=True, default='', max_length=120)),
                ('voltage', models.CharField(blank=True, default='', max_length=120)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('expected_service_interval', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('structured_payload', models.JSONField(blank=True, default=dict)),
                ('visible_to_associated_contractors', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_property_intelligence_records', to=settings.AUTH_USER_MODEL)),
                ('installed_by_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_property_intelligence_records', to='projects.contractor')),
                ('property_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence_records', to='projects.propertyprofile')),
                ('related_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_intelligence_records', to='projects.agreement')),
                ('related_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_intelligence_records', to='projects.milestone')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_intelligence_records', to='projects.project')),
                ('source_capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_intelligence_records', to='projects.projectassistantsmartcapturesession')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_records', to='projects.propertydocument')),
                ('source_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intelligence_records', to='projects.propertyphoto')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='projectassistantsmartcapturesession',
            name='created_property_intelligence_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smart_capture_sessions', to='projects.propertyintelligencerecord'),
        ),
        migrations.AddIndex(
            model_name='projectassistantsmartcapturesession',
            index=models.Index(fields=['property_profile', 'capture_type', 'status'], name='pa_smart_property_idx'),
        ),
        migrations.AddIndex(
            model_name='projectassistantsmartcapturesession',
            index=models.Index(fields=['customer_email', 'updated_at'], name='pa_smart_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyintelligencerecord',
            index=models.Index(fields=['property_profile', 'record_type', 'status'], name='prop_intel_type_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyintelligencerecord',
            index=models.Index(fields=['customer_email', 'record_type', '-updated_at'], name='prop_intel_email_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyintelligencerecord',
            index=models.Index(fields=['property_profile', 'serial_number'], name='prop_intel_serial_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyintelligencerecord',
            index=models.Index(fields=['property_profile', 'model_number'], name='prop_intel_model_idx'),
        ),
    ]
