# Generated by Django 5.2.13 on 2026-07-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0257_aiusageledger_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorsubaccount',
            name='setup_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorsubaccount',
            name='setup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
