# Generated by Django 5.2.13 on 2026-07-20 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0258_contractorsubaccount_setup_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorInsightsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('monthly_revenue', 'Monthly Revenue'), ('annual_revenue', 'Annual Revenue'), ('projects_completed', 'Projects Completed'), ('average_project_value', 'Average Project Value'), ('estimate_acceptance_rate', 'Estimate Acceptance Rate')], db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=160)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_goals', to='projects.contractor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insights_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'deadline', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorInsightsPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_widget_ids', models.JSONField(blank=True, default=list)),
                ('default_reporting_period', models.CharField(blank=True, default='30', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_preferences', to='projects.contractor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insights_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
