# Generated by Django 5.2.13 on 2026-07-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0259_contractorinsightsgoal_contractorinsightspreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorinsightspreference',
            name='view_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
