# Generated by Django 5.2.13 on 2026-07-25 04:56

import django.db.models.deletion
import django.utils.timezone
import projects.models_capture
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0260_contractorinsightspreference_view_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capture_type', models.CharField(choices=[('quick_lead', 'Quick Lead'), ('quick_note', 'Quick Note'), ('photo', 'Photo'), ('receipt', 'Receipt'), ('opportunity', 'Opportunity')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('processing', 'Processing'), ('ready_for_review', 'Ready for Review'), ('needs_information', 'Needs Information'), ('possible_duplicate', 'Possible Duplicate'), ('approved', 'Approved'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed'), ('apply_failed', 'Apply Failed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('processing_engine', models.CharField(blank=True, default='', max_length=80)),
                ('original_captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_category', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('source_detail', models.CharField(blank=True, default='', max_length=80)),
                ('capture_method', models.CharField(choices=[('typed', 'Typed'), ('voice_transcript', 'Voice Transcript'), ('camera', 'Camera'), ('file_upload', 'File Upload'), ('public_form', 'Public Form')], default='typed', max_length=32)),
                ('proposed_destination', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('raw_text_payload', models.JSONField(blank=True, default=dict)),
                ('structured_draft', models.JSONField(blank=True, default=dict)),
                ('confidence', models.JSONField(blank=True, default=dict)),
                ('duplicate_candidates', models.JSONField(blank=True, default=list)),
                ('failure_details', models.JSONField(blank=True, default=dict)),
                ('attribution_metadata', models.JSONField(blank=True, default=dict)),
                ('audit_metadata', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='projects.agreement')),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='projects.contractor')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='projects.homeowner')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='projects.milestone')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='projects.project')),
            ],
            options={
                'ordering': ['-original_captured_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptureApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adapter', models.CharField(db_index=True, max_length=80)),
                ('adapter_version', models.CharField(default='1', max_length=32)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('capture_version', models.PositiveIntegerField()),
                ('request_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_records', models.JSONField(blank=True, default=list)),
                ('receipt_payload', models.JSONField(blank=True, default=dict)),
                ('failure_code', models.CharField(blank=True, default='', max_length=80)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_applications', to=settings.AUTH_USER_MODEL)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.capture')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaptureArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('audio', 'Audio'), ('photo', 'Photo'), ('document', 'Document'), ('other', 'Other')], max_length=24)),
                ('file', models.FileField(upload_to=projects.models_capture.capture_artifact_upload_path)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retention_state', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], db_index=True, default='active', max_length=20)),
                ('sanitization_metadata', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='projects.capture')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaptureEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('from_status', models.CharField(blank=True, default='', max_length=32)),
                ('to_status', models.CharField(blank=True, default='', max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_events', to=settings.AUTH_USER_MODEL)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.capture')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['contractor', 'status', '-original_captured_at'], name='capture_inbox_status_idx'),
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['contractor', 'capture_type', '-created_at'], name='capture_inbox_type_idx'),
        ),
        migrations.AddIndex(
            model_name='capture',
            index=models.Index(fields=['contractor', 'captured_by', '-created_at'], name='capture_actor_idx'),
        ),
        migrations.AddConstraint(
            model_name='captureapplication',
            constraint=models.UniqueConstraint(fields=('capture', 'idempotency_key'), name='uniq_capture_application_key'),
        ),
        migrations.AddIndex(
            model_name='captureartifact',
            index=models.Index(fields=['capture', 'retention_state'], name='capture_artifact_state_idx'),
        ),
        migrations.AddIndex(
            model_name='captureevent',
            index=models.Index(fields=['capture', 'created_at'], name='capture_event_time_idx'),
        ),
    ]
