# Generated by Django 5.2.13 on 2026-07-26 07:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0263_capture_application_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publiccontractorlead',
            name='origin_capture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compatibility_public_lead', to='projects.capture'),
        ),
        migrations.CreateModel(
            name='CaptureQrAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('asset_type', models.CharField(choices=[('business_card', 'Business Card'), ('truck', 'Truck'), ('trailer', 'Trailer'), ('yard_sign', 'Yard Sign'), ('flyer', 'Flyer'), ('door_hanger', 'Door Hanger'), ('home_show', 'Home Show'), ('referral_partner', 'Referral Partner'), ('social_media', 'Social Media'), ('website', 'Website'), ('custom', 'Custom')], default='business_card', max_length=32)),
                ('campaign_key', models.SlugField(blank=True, default='', max_length=80)),
                ('source_detail', models.CharField(blank=True, default='business_card', max_length=80)),
                ('token_key', models.CharField(editable=False, max_length=96)),
                ('token_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_qr_assets', to='projects.contractor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_capture_qr_assets', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_qr_assets', to='projects.contractorpublicprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='capture',
            name='qr_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='projects.captureqrasset'),
        ),
        migrations.AddField(
            model_name='publiccontractorlead',
            name='qr_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_leads', to='projects.captureqrasset'),
        ),
        migrations.CreateModel(
            name='CaptureQrEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.captureqrasset')),
                ('capture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_events', to='projects.capture')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CaptureQrSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_token_hash', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.captureqrasset')),
                ('capture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qr_submission', to='projects.capture')),
                ('public_lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='qr_submission', to='projects.publiccontractorlead')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'form_token_hash'), name='uniq_capture_qr_form_token')],
            },
        ),
    ]
