# Generated by Django 5.2.13 on 2026-07-26 15:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0264_capture_qr_business_card'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercommunicationlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='capture_type',
            field=models.CharField(choices=[('quick_lead', 'Quick Lead'), ('quick_note', 'Quick Note'), ('photo', 'Photo'), ('receipt', 'Receipt'), ('opportunity', 'Opportunity'), ('project_update', 'Project Update'), ('progress_photo', 'Progress Photo'), ('issue', 'Issue'), ('communication', 'Communication'), ('document', 'Document')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ProjectCaptureActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('project_update', 'Project update'), ('progress_photo', 'Progress photo'), ('issue', 'Issue'), ('communication', 'Communication'), ('document', 'Document')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('customer_visible', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_capture_activities', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_activities', to='projects.milestone')),
                ('origin_capture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_activity', to='projects.capture')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_activities', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='projects_pr_project_4d208c_idx'), models.Index(fields=['project', 'customer_visible', '-created_at'], name='projects_pr_project_a75f0e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectCaptureAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('customer_visible', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project_attachment', to='projects.captureartifact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_capture_attachments', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_attachments', to='projects.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_attachments', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='projects_pr_project_117c3c_idx'), models.Index(fields=['project', 'customer_visible', '-created_at'], name='projects_pr_project_dd0531_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectCaptureIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('project_issue', 'Project issue'), ('punch_item', 'Punch item'), ('customer_concern', 'Customer concern'), ('potential_warranty', 'Potential warranty'), ('potential_change_request', 'Potential change request'), ('internal_note', 'Internal note')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_capture_issues', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_issues', to='projects.milestone')),
                ('origin_capture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_issue', to='projects.capture')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_issues', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', 'status', '-created_at'], name='projects_pr_project_cd257f_idx'), models.Index(fields=['project', 'classification'], name='projects_pr_project_18c289_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectCaptureNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_capture_notes', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_notes', to='projects.milestone')),
                ('origin_capture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_note', to='projects.capture')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_notes', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['project', '-created_at'], name='projects_pr_project_3914f3_idx')],
            },
        ),
    ]
