# Generated by Django 5.2.13 on 2026-07-26 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0265_project_capture_phase_d1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementwarranty',
            name='customer_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreementwarranty',
            name='origin_capture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_record', to='projects.capture'),
        ),
        migrations.AddField(
            model_name='contractorasset',
            name='customer_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contractorasset',
            name='maintenance_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contractorasset',
            name='origin_capture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_record', to='projects.capture'),
        ),
        migrations.AddField(
            model_name='warrantyrequest',
            name='origin_capture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_request', to='projects.capture'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='capture_type',
            field=models.CharField(choices=[('quick_lead', 'Quick Lead'), ('quick_note', 'Quick Note'), ('photo', 'Photo'), ('receipt', 'Receipt'), ('opportunity', 'Opportunity'), ('project_update', 'Project Update'), ('progress_photo', 'Progress Photo'), ('issue', 'Issue'), ('communication', 'Communication'), ('document', 'Document'), ('equipment', 'Equipment'), ('warranty_document', 'Warranty Document'), ('warranty_concern', 'Warranty Concern')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='EquipmentCaptureAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_attachment', to='projects.captureartifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_capture_attachments', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_attachments', to='projects.contractorasset')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyCaptureChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_values', models.JSONField(default=dict)),
                ('approved_values', models.JSONField(default=dict)),
                ('action', models.CharField(default='create', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_capture_changes', to=settings.AUTH_USER_MODEL)),
                ('origin_capture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_changes', to='projects.capture')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_changes', to='projects.agreementwarranty')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyCaptureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_visible', models.BooleanField(default=False)),
                ('approved_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_document', to='projects.captureartifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warranty_capture_documents', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_documents', to='projects.contractorasset')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capture_documents', to='projects.agreementwarranty')),
            ],
        ),
    ]
