# Generated by Django 5.2.13 on 2026-07-26 20:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0266_capture_warranty_equipment_phase_d2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='capture_type',
            field=models.CharField(choices=[('quick_lead', 'Quick Lead'), ('quick_note', 'Quick Note'), ('photo', 'Photo'), ('receipt', 'Receipt'), ('opportunity', 'Opportunity'), ('project_update', 'Project Update'), ('progress_photo', 'Progress Photo'), ('issue', 'Issue'), ('communication', 'Communication'), ('document', 'Document'), ('equipment', 'Equipment'), ('warranty_document', 'Warranty Document'), ('warranty_concern', 'Warranty Concern'), ('measurement', 'Measurement')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='MeasurementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(default='room_overview', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_attachment', to='projects.captureartifact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('line', models.JSONField(default=dict)),
                ('entry_client_key', models.CharField(blank=True, default='', max_length=80)),
                ('known_reference_value', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('verification_status', models.CharField(default='estimated', max_length=24)),
                ('warning', models.CharField(default='Perspective may affect accuracy. Verify before contractual use.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='projects.measurementattachment')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=160)),
                ('room_type', models.CharField(default='general_room', max_length=80)),
                ('purpose', models.CharField(choices=[('flooring', 'Flooring'), ('wall_finish', 'Wall Finish'), ('painting', 'Painting'), ('ceiling', 'Ceiling'), ('door', 'Door'), ('window', 'Window'), ('cabinetry', 'Cabinetry'), ('countertop', 'Countertop'), ('fencing', 'Fencing'), ('roofing', 'Roofing'), ('general_room', 'General Room'), ('custom', 'Custom')], default='general_room', max_length=40)),
                ('guided_profile', models.CharField(blank=True, default='', max_length=40)),
                ('default_unit_system', models.CharField(default='us_customary', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('measuring', 'Measuring'), ('needs_review', 'Needs Review'), ('verified', 'Verified'), ('confirmed', 'Confirmed'), ('archived', 'Archived')], db_index=True, default='needs_review', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.PositiveIntegerField(default=1)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_measurement_sessions', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_measurement_sessions', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_sessions', to='projects.contractor')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_sessions', to='projects.homeowner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_sessions', to='projects.project')),
                ('property_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_sessions', to='projects.propertyprofile')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_sessions', to='projects.proposal')),
                ('source_capture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_session', to='projects.capture')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('session_version', models.PositiveIntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.measurementsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementCalculatedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('gross_area', 'Gross Area'), ('net_area', 'Net Area'), ('excluded_area', 'Excluded Area'), ('perimeter', 'Perimeter'), ('total_linear_length', 'Total Linear Length'), ('volume', 'Volume'), ('opening_area', 'Opening Area'), ('custom_calculated', 'Custom Calculated')], max_length=32)),
                ('label', models.CharField(max_length=160)),
                ('normalized_value', models.DecimalField(decimal_places=10, max_digits=24)),
                ('normalized_unit', models.CharField(max_length=32)),
                ('display_value', models.CharField(max_length=80)),
                ('display_unit', models.CharField(max_length=32)),
                ('formula_key', models.CharField(max_length=80)),
                ('calculation_version', models.CharField(default='1', max_length=24)),
                ('source_entry_keys', models.JSONField(default=list)),
                ('adjustment_keys', models.JSONField(default=list)),
                ('verification_status', models.CharField(default='needs_verification', max_length=24)),
                ('lineage', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_results', to='projects.measurementsession')),
            ],
        ),
        migrations.AddField(
            model_name='measurementattachment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.measurementsession'),
        ),
        migrations.CreateModel(
            name='MeasurementAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('adjustment_type', models.CharField(choices=[('addition', 'Addition'), ('exclusion', 'Exclusion'), ('unmeasured', 'Unmeasured')], max_length=24)),
                ('source_entry_keys', models.JSONField(default=list)),
                ('calculated_value', models.DecimalField(decimal_places=10, max_digits=24)),
                ('normalized_unit', models.CharField(default='square_inches', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='projects.measurementsession')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=80)),
                ('reading_group', models.CharField(blank=True, default='', max_length=80)),
                ('label', models.CharField(max_length=160)),
                ('dimension_type', models.CharField(choices=[('length', 'Length'), ('width', 'Width'), ('height', 'Height'), ('depth', 'Depth'), ('thickness', 'Thickness'), ('perimeter_segment', 'Perimeter Segment'), ('diagonal', 'Diagonal'), ('radius', 'Radius'), ('diameter', 'Diameter'), ('slope', 'Slope'), ('angle', 'Angle'), ('area_manual', 'Area Manual'), ('volume_manual', 'Volume Manual'), ('opening_width', 'Opening Width'), ('opening_height', 'Opening Height'), ('other', 'Other')], max_length=32)),
                ('normalized_value', models.DecimalField(decimal_places=10, max_digits=24)),
                ('display_unit', models.CharField(max_length=32)),
                ('raw_value', models.CharField(max_length=160)),
                ('source_method', models.CharField(choices=[('tape_measure', 'Tape Measure'), ('manual_entry', 'Manual Entry'), ('voice_transcript', 'Voice Transcript'), ('laser_manual_entry', 'Laser Manual Entry'), ('photo_reference', 'Photo Reference'), ('existing_plan', 'Existing Plan'), ('other', 'Other')], max_length=32)),
                ('verification_status', models.CharField(choices=[('estimated', 'Estimated'), ('needs_verification', 'Needs Verification'), ('verified', 'Verified'), ('confirmed', 'Confirmed')], default='needs_verification', max_length=24)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('tool_description', models.CharField(blank=True, default='', max_length=255)),
                ('selected_for_calculation', models.BooleanField(default=True)),
                ('selection_method', models.CharField(blank=True, default='', max_length=24)),
                ('direction', models.CharField(blank=True, choices=[('north', 'North'), ('east', 'East'), ('south', 'South'), ('west', 'West')], default='', max_length=8)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_entries', to=settings.AUTH_USER_MODEL)),
                ('reference_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_entries', to='projects.measuremententry')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_measurement_entries', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='projects.measurementsession')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('session', 'client_key'), name='uniq_measurement_session_client_key')],
            },
        ),
    ]
