# Generated by Django 5.2.13 on 2026-07-26 20:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0267_measurement_foundation_phase_d3_1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('trade_profile', models.CharField(max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_assemblies', to='projects.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=80)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=120)),
                ('supplier', models.CharField(blank=True, default='', max_length=160)),
                ('supplier_sku', models.CharField(blank=True, default='', max_length=120)),
                ('product_url', models.URLField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_basis', models.CharField(choices=[('per_selling_unit', 'Per Selling Unit'), ('per_square_foot', 'Per Square Foot'), ('per_linear_foot', 'Per Linear Foot'), ('per_cubic_foot', 'Per Cubic Foot'), ('per_cubic_yard', 'Per Cubic Yard'), ('per_gallon', 'Per Gallon'), ('per_each', 'Per Each'), ('custom', 'Custom')], max_length=32)),
                ('selling_unit', models.CharField(choices=[('each', 'Each'), ('box', 'Box'), ('case', 'Case'), ('bundle', 'Bundle'), ('sheet', 'Sheet'), ('panel', 'Panel'), ('roll', 'Roll'), ('bag', 'Bag'), ('gallon', 'Gallon'), ('quart', 'Quart'), ('linear_foot', 'Linear Foot'), ('square_foot', 'Square Foot'), ('cubic_foot', 'Cubic Foot'), ('cubic_yard', 'Cubic Yard'), ('pound', 'Pound'), ('ton', 'Ton'), ('custom', 'Custom')], max_length=32)),
                ('package_quantity', models.DecimalField(decimal_places=6, default=1, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('coverage_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('coverage_unit', models.CharField(blank=True, default='', max_length=32)),
                ('package_dimensions', models.JSONField(blank=True, default=dict)),
                ('waste_default', models.DecimalField(decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_category', models.CharField(blank=True, default='', max_length=80)),
                ('markup_default', models.DecimalField(decimal_places=3, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('price_source', models.CharField(max_length=160)),
                ('price_effective_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_library', to='projects.contractor')),
                ('price_entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_prices_entered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-is_preferred', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAssemblyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=80)),
                ('waste_override', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('assumptions', models.JSONField(blank=True, default=dict)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.materialassembly')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assembly_memberships', to='projects.materiallibraryitem')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TakeoffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_profile', models.CharField(choices=[('flooring', 'Flooring'), ('paint', 'Paint'), ('tile', 'Tile'), ('drywall', 'Drywall'), ('linear_material', 'Linear Material'), ('concrete', 'Concrete')], max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculating', 'Calculating'), ('needs_information', 'Needs Information'), ('ready_for_review', 'Ready For Review'), ('confirmed', 'Confirmed'), ('handed_off', 'Handed Off'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('provisional', models.BooleanField(default=False)),
                ('provisional_acknowledged', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('tax', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('markup', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('version', models.PositiveIntegerField(default=1)),
                ('handoff_previewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeoff_sessions', to='projects.contractor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeoffs_created', to=settings.AUTH_USER_MODEL)),
                ('measurement_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='takeoff_sessions', to='projects.measurementsession')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeoff_sessions', to='projects.project')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeoff_sessions', to='projects.proposal')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeoffs_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TakeoffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_component', models.CharField(default='primary_material', max_length=80)),
                ('product_snapshot', models.JSONField(default=dict)),
                ('theoretical_quantity', models.DecimalField(decimal_places=10, max_digits=24)),
                ('waste_percentage', models.DecimalField(decimal_places=3, max_digits=7)),
                ('waste_source', models.CharField(max_length=40)),
                ('waste_quantity', models.DecimalField(decimal_places=10, max_digits=24)),
                ('required_quantity', models.DecimalField(decimal_places=10, max_digits=24)),
                ('purchase_quantity', models.DecimalField(decimal_places=10, max_digits=24)),
                ('purchased_coverage', models.DecimalField(decimal_places=10, max_digits=24)),
                ('excess_quantity', models.DecimalField(decimal_places=10, max_digits=24)),
                ('selling_unit', models.CharField(max_length=32)),
                ('package_coverage', models.DecimalField(decimal_places=10, max_digits=24)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=4, max_digits=16)),
                ('subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('tax', models.DecimalField(decimal_places=4, max_digits=18)),
                ('markup', models.DecimalField(decimal_places=4, max_digits=18)),
                ('final_estimated_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('calculation_version', models.CharField(default='1', max_length=24)),
                ('rounding_policy', models.CharField(default='ceil_to_package', max_length=32)),
                ('assumptions', models.JSONField(default=dict)),
                ('warnings', models.JSONField(default=list)),
                ('lineage', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='takeoff_items', to='projects.materiallibraryitem')),
                ('measurement_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='takeoff_items', to='projects.measurementcalculatedresult')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.takeoffsession')),
            ],
        ),
        migrations.CreateModel(
            name='TakeoffEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=48)),
                ('session_version', models.PositiveIntegerField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.takeoffsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='materiallibraryitem',
            constraint=models.UniqueConstraint(fields=('contractor', 'name', 'supplier_sku'), name='uniq_material_library_name_sku'),
        ),
    ]
