# Generated by Django 5.2.13 on 2026-07-27 01:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0268_intelligent_takeoff_phase_d3_2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measuremententry',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='measuremententry',
            name='source_method',
            field=models.CharField(choices=[('tape_measure', 'Tape Measure'), ('manual_entry', 'Manual Entry'), ('voice_transcript', 'Voice Transcript'), ('laser_manual_entry', 'Laser Manual Entry'), ('photo_reference', 'Photo Reference'), ('existing_plan', 'Existing Plan'), ('pdf_plan', 'Pdf Plan'), ('other', 'Other')], max_length=32),
        ),
        migrations.CreateModel(
            name='PlanMeasurementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('page_count', models.PositiveIntegerField()),
                ('file_size', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=16)),
                ('source', models.CharField(default='capture_artifact', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='plan_measurement_document', to='projects.captureartifact')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_measurement_documents', to='projects.contractor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_documents_created', to=settings.AUTH_USER_MODEL)),
                ('measurement_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_documents', to='projects.measurementsession')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_measurement_documents', to='projects.project')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_measurement_documents', to='projects.proposal')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanMeasurementCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('calibration_type', models.CharField(choices=[('page', 'Page'), ('region', 'Region')], default='page', max_length=16)),
                ('reference_geometry', models.JSONField()),
                ('region_geometry', models.JSONField(blank=True, default=dict)),
                ('known_length', models.DecimalField(decimal_places=10, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('unit', models.CharField(max_length=24)),
                ('canonical_distance', models.DecimalField(decimal_places=10, max_digits=24)),
                ('scale_per_point', models.DecimalField(decimal_places=10, max_digits=24)),
                ('page_rotation', models.PositiveSmallIntegerField(default=0)),
                ('page_box', models.JSONField(default=dict)),
                ('source_dimension_label', models.CharField(blank=True, default='', max_length=160)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high_estimate', 'High estimate'), ('verified', 'Verified')], default='high_estimate', max_length=24)),
                ('warnings', models.JSONField(default=list)),
                ('document_checksum', models.CharField(max_length=64)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_calibrations_created', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='projects.planmeasurementcalibration')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='projects.planmeasurementdocument')),
            ],
            options={
                'ordering': ['page_number', '-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanMeasurementAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('annotation_type', models.CharField(choices=[('line', 'Line'), ('polyline', 'Polyline'), ('polygon', 'Polygon'), ('count', 'Count marker')], max_length=16)),
                ('geometry', models.JSONField()),
                ('label', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('normalized_value', models.DecimalField(decimal_places=10, max_digits=24)),
                ('normalized_unit', models.CharField(max_length=32)),
                ('perimeter_value', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high_estimate', 'High estimate'), ('verified', 'Verified')], default='high_estimate', max_length=24)),
                ('confidence_reasons', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('source_version', models.CharField(default='pdf_plan.v1', max_length=24)),
                ('calculation_version', models.CharField(default='pdf_geometry.v1', max_length=24)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_annotations_created', to=settings.AUTH_USER_MODEL)),
                ('measurement_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_annotations', to='projects.measuremententry')),
                ('measurement_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_annotations', to='projects.measurementcalculatedresult')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='projects.planmeasurementannotation')),
                ('calibration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='projects.planmeasurementcalibration')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='projects.planmeasurementdocument')),
            ],
            options={
                'ordering': ['page_number', 'created_at', 'id'],
            },
        ),
    ]
