# Generated by Django 5.2.13 on 2026-07-27 01:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0269_blueprint_pdf_takeoff_d3_3a'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMeasurementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_image', models.FileField(upload_to='capture/measurement/photo-previews/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=32)),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('original_width', models.PositiveIntegerField()),
                ('original_height', models.PositiveIntegerField()),
                ('normalized_width', models.PositiveIntegerField()),
                ('normalized_height', models.PositiveIntegerField()),
                ('original_orientation', models.PositiveSmallIntegerField(default=1)),
                ('orientation_transform', models.CharField(default='identity', max_length=40)),
                ('source', models.CharField(default='capture_artifact', max_length=32)),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='photo_measurement_document', to='projects.captureartifact')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_measurement_documents', to='projects.contractor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_documents_created', to=settings.AUTH_USER_MODEL)),
                ('measurement_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_documents', to='projects.measurementsession')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_measurement_documents', to='projects.project')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_measurement_documents', to='projects.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMeasurementCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_geometry', models.JSONField()),
                ('known_length', models.DecimalField(decimal_places=10, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))])),
                ('unit', models.CharField(max_length=24)),
                ('canonical_pixel_distance', models.DecimalField(decimal_places=10, max_digits=24)),
                ('scale_per_pixel', models.DecimalField(decimal_places=10, max_digits=24)),
                ('working_region', models.JSONField(blank=True, default=dict)),
                ('same_plane_attested', models.BooleanField(default=False)),
                ('same_plane_attested_at', models.DateTimeField()),
                ('marker_version', models.CharField(blank=True, default='', max_length=32)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high_estimate', 'High estimate'), ('verified', 'Verified')], default='medium', max_length=24)),
                ('evidence', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('image_checksum', models.CharField(max_length=64)),
                ('algorithm_version', models.CharField(default='photo_geometry.v1', max_length=32)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_calibrations_created', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supersedes', to='projects.photomeasurementcalibration')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='projects.photomeasurementdocument')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMeasurementAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry_type', models.CharField(choices=[('line', 'Line'), ('polyline', 'Polyline'), ('polygon', 'Polygon')], max_length=16)),
                ('geometry', models.JSONField()),
                ('label', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('repeat_group', models.CharField(blank=True, default='', max_length=80)),
                ('preferred_attempt', models.BooleanField(default=False)),
                ('normalized_value', models.DecimalField(decimal_places=10, max_digits=24)),
                ('normalized_unit', models.CharField(max_length=32)),
                ('perimeter_value', models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True)),
                ('confidence', models.CharField(default='medium', max_length=24)),
                ('evidence', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('calculation_version', models.CharField(default='photo_geometry.v1', max_length=32)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_annotations_created', to=settings.AUTH_USER_MODEL)),
                ('measurement_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_annotations', to='projects.measuremententry')),
                ('measurement_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_annotations', to='projects.measurementcalculatedresult')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='projects.photomeasurementannotation')),
                ('calibration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='projects.photomeasurementcalibration')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='projects.photomeasurementdocument')),
            ],
        ),
    ]
