# Generated by Django 5.2.13 on 2026-07-27 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0270_photo_assisted_measurement_d3_3b'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcaptureissue',
            name='child_key',
            field=models.CharField(db_index=True, default='legacy', max_length=80),
        ),
        migrations.AlterField(
            model_name='projectcaptureissue',
            name='classification',
            field=models.CharField(choices=[('project_issue', 'Project issue'), ('punch_item', 'Punch item'), ('customer_concern', 'Customer concern'), ('potential_warranty', 'Potential warranty'), ('potential_change_request', 'Potential change request'), ('internal_note', 'Internal note'), ('site_condition', 'Site condition')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='projectcaptureissue',
            name='origin_capture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_issues', to='projects.capture'),
        ),
        migrations.AddConstraint(
            model_name='projectcaptureissue',
            constraint=models.UniqueConstraint(fields=('origin_capture', 'child_key'), name='uniq_capture_issue_child_key'),
        ),
    ]
