# Generated by Django 5.2.1 on 2026-07-29 16:46

import django.db.models.deletion
import projects.models_diy_planner
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0274_agreement_pdf_generation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='project_mode',
            field=models.CharField(blank=True, choices=[('full_service', 'Full Service'), ('diy_assist', 'DIY Assist'), ('consultation', 'Consultation / Guidance'), ('inspection_only', 'Inspection Only'), ('not_sure', 'Not Sure Yet')], default='', max_length=32),
        ),
        migrations.CreateModel(
            name='DIYProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('desired_outcome', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('area', models.CharField(blank=True, default='', max_length=120)),
                ('existing_conditions', models.TextField(blank=True, default='')),
                ('work_completed', models.TextField(blank=True, default='')),
                ('target_budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('confidence_notes', models.TextField(blank=True, default='')),
                ('design_notes', models.TextField(blank=True, default='')),
                ('additional_context', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('ready', 'Ready to Start'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='planning', max_length=24)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diy_projects', to='projects.propertyprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DIYProjectAIProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='proposed', max_length=16)),
                ('applied_keys', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_proposals', to='projects.diyproject')),
            ],
        ),
        migrations.CreateModel(
            name='DIYProjectMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(max_length=40)),
                ('notes', models.TextField(blank=True, default='')),
                ('verification_status', models.CharField(choices=[('homeowner_provided', 'Homeowner Provided'), ('professionally_verified', 'Professionally Verified')], default='homeowner_provided', max_length=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='projects.diyproject')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DIYProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.diyproject')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DIYProjectRequestLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diy_project_links', to='projects.customerrequest')),
                ('diy_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_links', to='projects.diyproject')),
            ],
        ),
        migrations.CreateModel(
            name='DIYProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('participation_type', models.CharField(choices=[('DO_IT_MYSELF', 'Doing Myself'), ('NEED_GUIDANCE', 'Need Expert Guidance'), ('NEED_HELP', 'Need Hands-On Help'), ('NEED_PROFESSIONAL', 'Need a Professional'), ('UNDECIDED', 'Undecided')], default='UNDECIDED', max_length=32)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=24)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('estimated_duration', models.CharField(blank=True, default='', max_length=120)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prerequisite_notes', models.TextField(blank=True, default='')),
                ('professional_review_recommended', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('homeowner', 'Homeowner-created'), ('ai', 'AI-suggested')], default='homeowner', max_length=16)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.diyprojectphase')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DIYProjectProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('from_status', models.CharField(blank=True, default='', max_length=24)),
                ('to_status', models.CharField(blank=True, default='', max_length=24)),
                ('created_by_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='projects.diyproject')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_entries', to='projects.diyprojecttask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DIYProjectAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('project_photo', 'Project Photo'), ('inspiration', 'Inspiration / Reference'), ('progress', 'Progress / Completion'), ('file', 'File')], default='project_photo', max_length=24)),
                ('file', models.FileField(upload_to=projects.models_diy_planner.diy_asset_upload_path)),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_by_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.diyproject')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='projects.diyprojecttask')),
            ],
        ),
        migrations.AddIndex(
            model_name='diyproject',
            index=models.Index(fields=['owner_email', 'status'], name='projects_di_owner_e_6f22ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='diyprojectrequestlink',
            constraint=models.UniqueConstraint(fields=('diy_project', 'idempotency_key'), name='uniq_diy_request_link_key'),
        ),
    ]
