# Generated by Django 5.2.13 on 2026-08-09 07:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0278_proposal_selected_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='converted_agreement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposal', to='projects.agreement'),
        ),
        migrations.AlterField(
            model_name='proposalactivity',
            name='event_type',
            field=models.CharField(choices=[('created', 'Proposal Created'), ('appointment_linked', 'Appointment Linked'), ('status_updated', 'Status Updated'), ('site_visit_updated', 'Site Visit Updated'), ('measurement_added', 'Measurement Added'), ('measurement_updated', 'Measurement Updated'), ('measurement_removed', 'Measurement Removed'), ('attachment_uploaded', 'Attachment Uploaded'), ('attachment_updated', 'Attachment Updated'), ('attachment_removed', 'Attachment Removed'), ('scope_edited', 'Scope Edited'), ('notes_edited', 'Notes Edited'), ('line_item_added', 'Line Item Added'), ('line_item_updated', 'Line Item Updated'), ('line_item_removed', 'Line Item Removed'), ('estimate_sent', 'Estimate Sent'), ('estimate_viewed', 'Estimate Viewed'), ('estimate_accepted', 'Estimate Accepted'), ('estimate_declined', 'Estimate Declined'), ('estimate_revision_requested', 'Estimate Revision Requested'), ('agreement_override', 'Agreement Review Override')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ProposalReviewVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('access_nonce', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('snapshot', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revision_requested', 'Revision requested')], default='pending', max_length=24)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.CharField(blank=True, default='', max_length=255)),
                ('acceptance_acknowledgement', models.TextField(blank=True, default='')),
                ('decline_reason', models.CharField(blank=True, default='', max_length=80)),
                ('revision_request_message', models.TextField(blank=True, default='')),
                ('delivery_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_versions', to='projects.proposal')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(fields=('proposal', 'version'), name='uniq_proposal_review_version')],
            },
        ),
    ]
