# Generated by Django 5.2.13 on 2026-08-09 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0279_proposal_converted_agreement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalPortalActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('nonce', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_activation', to='projects.proposalreviewversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
