# Generated by Django 5.2.13 on 2026-08-10 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0280_proposalportalactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='conversion_method',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='proposal',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='converted_review_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_proposals', to='projects.proposalreviewversion'),
        ),
        migrations.AlterField(
            model_name='proposalactivity',
            name='event_type',
            field=models.CharField(choices=[('created', 'Proposal Created'), ('appointment_linked', 'Appointment Linked'), ('status_updated', 'Status Updated'), ('site_visit_updated', 'Site Visit Updated'), ('measurement_added', 'Measurement Added'), ('measurement_updated', 'Measurement Updated'), ('measurement_removed', 'Measurement Removed'), ('attachment_uploaded', 'Attachment Uploaded'), ('attachment_updated', 'Attachment Updated'), ('attachment_removed', 'Attachment Removed'), ('scope_edited', 'Scope Edited'), ('notes_edited', 'Notes Edited'), ('line_item_added', 'Line Item Added'), ('line_item_updated', 'Line Item Updated'), ('line_item_removed', 'Line Item Removed'), ('estimate_sent', 'Estimate Sent'), ('estimate_viewed', 'Estimate Viewed'), ('estimate_accepted', 'Estimate Accepted'), ('estimate_declined', 'Estimate Declined'), ('estimate_revision_requested', 'Estimate Revision Requested'), ('agreement_override', 'Agreement Review Override'), ('agreement_created', 'Agreement Created')], db_index=True, max_length=40),
        ),
    ]
