# Generated by Django 5.2.13 on 2026-08-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0281_proposal_conversion_method_proposal_converted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsconsent',
            name='opted_in_source',
            field=models.CharField(blank=True, choices=[('signup', 'Signup'), ('agreement', 'Agreement'), ('inbound_start', 'Inbound START'), ('admin', 'Admin'), ('estimate_delivery_opt_in', 'Estimate delivery opt-in')], default='', max_length=32),
        ),
    ]
