# Generated by Django 5.2.1 on 2026-08-11 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0282_alter_smsconsent_opted_in_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('subcontractor_comment', 'Subcontractor Comment'), ('subcontractor_file', 'Subcontractor File'), ('subcontractor_review', 'Subcontractor Review Request'), ('draw_approved', 'Draw Approved'), ('draw_changes_requested', 'Draw Changes Requested'), ('draw_paid', 'Draw Paid'), ('draw_released', 'Draw Released'), ('bid_awarded', 'Bid Awarded'), ('bid_not_selected', 'Bid Not Selected'), ('contractor_opportunity_received', 'Contractor Opportunity Received'), ('marketplace_verification_approved', 'Marketplace Verification Approved'), ('marketplace_verification_rejected', 'Marketplace Verification Rejected'), ('marketplace_verification_suspended', 'Marketplace Verification Suspended'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('quote_request_received', 'Quote Request Received'), ('agreement_signed', 'Agreement Signed'), ('escrow_funded', 'Escrow Funded'), ('invoice_approved', 'Invoice Approved'), ('milestone_pending_approval', 'Milestone Pending Approval'), ('payment_released', 'Payment Released'), ('estimate_viewed', 'Estimate Viewed'), ('estimate_revision_requested', 'Estimate Revision Requested'), ('estimate_accepted', 'Estimate Accepted'), ('estimate_declined', 'Estimate Declined')], db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('contractor', 'dedupe_key'), name='uniq_notification_contractor_dedupe'),
        ),
    ]
