# Generated by Django 5.2.1 on 2026-08-11 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0283_estimate_review_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('subcontractor_comment', 'Subcontractor Comment'), ('subcontractor_file', 'Subcontractor File'), ('subcontractor_review', 'Subcontractor Review Request'), ('draw_approved', 'Draw Approved'), ('draw_changes_requested', 'Draw Changes Requested'), ('draw_paid', 'Draw Paid'), ('draw_released', 'Draw Released'), ('bid_awarded', 'Bid Awarded'), ('bid_not_selected', 'Bid Not Selected'), ('contractor_opportunity_received', 'Contractor Opportunity Received'), ('marketplace_verification_approved', 'Marketplace Verification Approved'), ('marketplace_verification_rejected', 'Marketplace Verification Rejected'), ('marketplace_verification_suspended', 'Marketplace Verification Suspended'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('quote_request_received', 'Quote Request Received'), ('agreement_signed', 'Agreement Signed'), ('escrow_funded', 'Escrow Funded'), ('invoice_approved', 'Invoice Approved'), ('milestone_pending_approval', 'Milestone Pending Approval'), ('payment_released', 'Payment Released'), ('estimate_viewed', 'Estimate Viewed'), ('estimate_customer_message', 'Estimate Customer Message'), ('agreement_customer_message', 'Agreement Customer Message'), ('project_customer_message', 'Project Customer Message'), ('estimate_revision_requested', 'Estimate Revision Requested'), ('estimate_accepted', 'Estimate Accepted'), ('estimate_declined', 'Estimate Declined')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='CustomerConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('agreement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_conversation', to='projects.agreement')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_conversations', to='projects.contractor')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='projects.homeowner')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_conversation', to='projects.project')),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_conversation', to='projects.proposal')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('contractor', 'Contractor'), ('team_member', 'Team member')], max_length=20)),
                ('sender_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('message_text', models.TextField()),
                ('lifecycle_context', models.CharField(choices=[('estimate', 'Estimate'), ('agreement', 'Agreement'), ('project', 'Project')], max_length=20)),
                ('contractor_read_at', models.DateTimeField(blank=True, null=True)),
                ('customer_read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('proposal_review_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_messages', to='projects.proposalreviewversion')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_conversation_messages', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.customerconversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='conversation_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('conversation', 'dedupe_key'), name='uniq_conversation_message_dedupe')],
            },
        ),
    ]
