# Generated by Django 5.2.13 on 2026-08-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0284_customer_conversations'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='accepted_estimate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='accepted_estimate_line_item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='accepted_estimate_review_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='accepted_estimate_source_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='source_allocation_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='source_milestone_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='source_milestone_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='source_milestone_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_line_items', to='projects.projecttemplate'),
        ),
        migrations.AddField(
            model_name='proposallineitem',
            name='source_template_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal_line_items', to='projects.projecttemplatemilestone'),
        ),
    ]
