# Generated by Django 5.2.13 on 2026-08-18 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0286_proposal_cancellation_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityestimateappointment',
            name='direct_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_estimate_appointments', to='projects.proposal'),
        ),
        migrations.AddField(
            model_name='opportunityestimateappointment',
            name='original_scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='appointment_disposition',
            field=models.CharField(choices=[('undecided', 'Undecided'), ('appointment_planned', 'Appointment planned'), ('no_visit_needed', 'No visit needed')], db_index=True, default='undecided', max_length=24),
        ),
        migrations.AlterField(
            model_name='opportunityestimateappointment',
            name='source_type',
            field=models.CharField(choices=[('lead', 'Public Lead'), ('intake', 'Project Intake'), ('opportunity', 'Contractor Opportunity'), ('proposal', 'Direct Estimate')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='opportunityestimateappointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('proposed', 'Proposed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No-show')], db_index=True, default='scheduled', max_length=24),
        ),
        migrations.CreateModel(
            name='OpportunityEstimateAppointmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('from_status', models.CharField(blank=True, default='', max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('reason', models.TextField(blank=True, default='')),
                ('before_values', models.JSONField(blank=True, default=dict)),
                ('after_values', models.JSONField(blank=True, default=dict)),
                ('actor_kind', models.CharField(default='contractor', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_appointment_events', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.opportunityestimateappointment')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
