# Generated by Django 5.2.13 on 2026-08-18 06:12

import django.db.models.deletion
from datetime import timedelta
from django.conf import settings
from django.db import IntegrityError, migrations, models, transaction
from django.utils import timezone


def backfill_active_reservations(apps, schema_editor):
    Appointment = apps.get_model('projects', 'OpportunityEstimateAppointment')
    Reservation = apps.get_model('projects', 'EstimateAppointmentReservation')
    now = timezone.now()
    Appointment.objects.filter(status__in=['requested', 'proposed'], hold_expires_at__isnull=True).update(
        hold_expires_at=now + timedelta(hours=24)
    )
    for appointment in Appointment.objects.filter(status__in=['requested', 'proposed', 'scheduled', 'confirmed']).iterator():
        if appointment.scheduled_start.minute % 15 or appointment.scheduled_start.second or appointment.duration_minutes % 15:
            continue  # Legacy overlap queries continue protecting unaligned records.
        rows = [
            Reservation(contractor_id=appointment.contractor_id, appointment_id=appointment.id,
                        segment_start=appointment.scheduled_start + timedelta(minutes=offset))
            for offset in range(0, appointment.duration_minutes, 15)
        ]
        try:
            with transaction.atomic():
                Reservation.objects.bulk_create(rows)
        except IntegrityError:
            continue  # Preserve conflicting legacy history; runtime overlap checks remain active.


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0287_opportunityestimateappointment_direct_proposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateAppointmentReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_start', models.DateTimeField()),
            ],
            options={
                'ordering': ['segment_start', 'id'],
            },
        ),
        migrations.AddField(
            model_name='opportunityestimateappointment',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='opportunityestimateappointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contractor_opportunity__isnull', True), ('direct_proposal__isnull', True), ('project_intake__isnull', True), ('public_lead__isnull', False), ('source_type', 'public_lead')), models.Q(('contractor_opportunity__isnull', True), ('direct_proposal__isnull', True), ('project_intake__isnull', False), ('public_lead__isnull', True), ('source_type', 'intake')), models.Q(('contractor_opportunity__isnull', False), ('direct_proposal__isnull', True), ('project_intake__isnull', True), ('public_lead__isnull', True), ('source_type', 'opportunity')), models.Q(('contractor_opportunity__isnull', True), ('direct_proposal__isnull', False), ('project_intake__isnull', True), ('public_lead__isnull', True), ('source_type', 'proposal')), _connector='OR'), name='estimate_appointment_exact_source'),
        ),
        migrations.AddField(
            model_name='estimateappointmentreservation',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='projects.opportunityestimateappointment'),
        ),
        migrations.AddField(
            model_name='estimateappointmentreservation',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_appointment_reservations', to='projects.contractor'),
        ),
        migrations.AddIndex(
            model_name='estimateappointmentreservation',
            index=models.Index(fields=['contractor', 'segment_start'], name='estimate_reservation_lookup'),
        ),
        migrations.AddConstraint(
            model_name='estimateappointmentreservation',
            constraint=models.UniqueConstraint(fields=('contractor', 'segment_start'), name='uniq_estimate_appointment_segment'),
        ),
        migrations.AddConstraint(
            model_name='estimateappointmentreservation',
            constraint=models.UniqueConstraint(fields=('appointment', 'segment_start'), name='uniq_estimate_appt_own_segment'),
        ),
        migrations.RunPython(backfill_active_reservations, migrations.RunPython.noop),
    ]
