# Generated by Django 5.2.13 on 2026-08-20 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0288_estimate_appointment_release_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateAppointmentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_version', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('confirmation', 'Confirmation'), ('reminder', 'Reminder')], db_index=True, max_length=24)),
                ('offset_minutes', models.PositiveIntegerField(default=0)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=16)),
                ('recipient', models.CharField(max_length=320)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], db_index=True, default='pending', max_length=24)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('suppressed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('error_detail', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='projects.opportunityestimateappointment')),
            ],
            options={
                'ordering': ['scheduled_for', 'id'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='estimate_delivery_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'schedule_version', 'kind', 'offset_minutes', 'channel', 'recipient'), name='uniq_est_appt_delivery_version_channel')],
            },
        ),
    ]
