# Generated by Django 5.2.13 on 2026-08-21 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0289_estimate_appointment_confirmation_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateAppointmentShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_version', models.CharField(db_index=True, max_length=64)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_links', to='projects.opportunityestimateappointment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('appointment', 'schedule_version'), name='uniq_est_appt_short_link_version')],
            },
        ),
    ]
