# Generated by Django 5.2.13 on 2026-08-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0290_estimate_appointment_short_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='warranty_type',
            field=models.CharField(choices=[('default', 'Standard 12-month workmanship warranty'), ('custom', 'Custom warranty'), ('none', 'No contractor warranty')], default='default', max_length=16),
        ),
    ]
