# Generated by Django 5.2.13 on 2026-09-16 17:15

import django.db.models.deletion
import django.utils.timezone
import projects.models_referrals
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0292_milestone_collaborator_assignment'),
        ('receipts', '0003_receipt_fee_snapshot_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributed_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('verified', 'Verified'), ('activated', 'Activated'), ('earning', 'Earning'), ('completed', 'Completed'), ('expired', 'Expired'), ('disqualified', 'Disqualified')], db_index=True, default='registered', max_length=20)),
                ('program_code', models.CharField(blank=True, default='', max_length=24)),
                ('reward_rate_bps', models.PositiveSmallIntegerField(default=0)),
                ('earning_months', models.PositiveSmallIntegerField(default=0)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activation_deadline', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('earning_starts_at', models.DateTimeField(blank=True, null=True)),
                ('earning_ends_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('disqualified_at', models.DateTimeField(blank=True, null=True)),
                ('disqualification_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_contractor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral_attribution', to='projects.contractor')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor_referrals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoundingContractorAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('awarded', 'Awarded'), ('expired', 'Expired'), ('disqualified', 'Disqualified')], db_index=True, default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qualification_deadline', models.DateTimeField()),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('promotion_ends_at', models.DateTimeField(blank=True, null=True)),
                ('disqualification_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founding_award', to='projects.contractor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'awarded'])), fields=('slot_number',), name='unique_active_founding_slot')],
            },
        ),
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifying_platform_fee_cents', models.PositiveIntegerField()),
                ('reward_rate_bps', models.PositiveSmallIntegerField()),
                ('reward_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('paid', 'Paid'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('available_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='referral_earning', to='receipts.receipt')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='projects.contractorreferral')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=projects.models_referrals.referral_code_default, max_length=20, unique=True)),
                ('is_eligible', models.BooleanField(db_index=True, default=True)),
                ('disqualified_at', models.DateTimeField(blank=True, null=True)),
                ('disqualification_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contractorreferral',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='projects.referralparticipant'),
        ),
        migrations.CreateModel(
            name='ReferralPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('payout_method', models.CharField(choices=[('contractor_stripe', 'Contractor Stripe Connect'), ('customer_credit', 'Customer project credit'), ('customer_direct_deposit', 'Customer direct deposit')], default='contractor_stripe', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earnings', models.ManyToManyField(blank=True, related_name='payouts', to='projects.referralearning')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='projects.referralparticipant')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_referral_payouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('copy', 'Copied link'), ('text', 'Text'), ('email', 'Email'), ('qr', 'QR download'), ('print', 'Print')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.referralparticipant')),
            ],
        ),
    ]
