# Generated by Django 5.2.13 on 2026-09-12 05:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0298_fix_estimate_appointment_lead_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='contractor_notified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='evidence_unavailable_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='expected_result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='missing_information',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dispute',
            name='prior_notice_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='qualification_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='qualification_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='qualification_explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='qualification_extension_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispute',
            name='qualification_extension_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='qualification_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispute',
            name='qualification_status',
            field=models.CharField(choices=[('pending', 'Pending qualification'), ('information_needed', 'Customer information needed'), ('qualified', 'Qualified'), ('not_qualified', 'Not qualified'), ('urgent_review', 'Urgent review')], db_index=True, default='qualified', max_length=32),
        ),
        migrations.AddField(
            model_name='dispute',
            name='requested_resolution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='urgent_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dispute',
            name='urgent_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='dispute',
            name='workflow_stage',
            field=models.CharField(choices=[('intake', 'Intake'), ('customer_information', 'Customer information'), ('contractor_response', 'Contractor response'), ('cure', 'Cure in progress'), ('resolution', 'Resolution'), ('external_resolution', 'External resolution'), ('closed', 'Closed')], db_index=True, default='intake', max_length=32),
        ),
        migrations.AlterField(
            model_name='resolutioncasetimelineevent',
            name='event_type',
            field=models.CharField(choices=[('case_created', 'Case Created'), ('evidence_uploaded', 'Evidence Uploaded'), ('statement_submitted', 'Statement Submitted'), ('resolution_proposed', 'Resolution Proposed'), ('evidence_requested', 'Evidence Requested'), ('payment_hold_applied', 'Payment Hold Applied'), ('payment_hold_released', 'Payment Hold Released'), ('human_decision_recorded', 'Human Decision Recorded'), ('agreement_signed', 'Agreement Signed'), ('pdf_generated', 'PDF Generated'), ('case_closed', 'Case Closed'), ('case_reopened', 'Case Reopened'), ('ai_analysis_updated', 'AI Analysis Updated'), ('qualification_updated', 'Qualification Updated'), ('hold_expiration_pending', 'Hold Expiration Pending'), ('work_pause_updated', 'Work Pause Updated'), ('escrow_allocation_updated', 'Escrow Allocation Updated'), ('manual', 'Manual Entry')], db_index=True, max_length=48),
        ),
        migrations.CreateModel(
            name='DisputeClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField()),
                ('expected_result', models.TextField(blank=True, default='')),
                ('requested_remedy', models.TextField(blank=True, default='')),
                ('milestone_connection', models.CharField(choices=[('direct', 'Direct'), ('partial', 'Partial'), ('unrelated', 'Unrelated')], default='direct', max_length=16)),
                ('evidence_status', models.CharField(blank=True, default='', max_length=32)),
                ('missing_information', models.JSONField(blank=True, default=list)),
                ('contractor_response', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('information_needed', 'Information needed'), ('qualified', 'Qualified'), ('not_qualified', 'Not qualified'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='projects.dispute')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('dispute', 'sequence'), name='uniq_dispute_claim_sequence')],
            },
        ),
        migrations.CreateModel(
            name='DisputePaymentHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('temporary', 'Temporary administrative hold'), ('continued', 'Qualified hold'), ('expiration_pending', 'Expiration pending'), ('released', 'Released'), ('no_hold', 'No platform-held funds')], db_index=True, default='temporary', max_length=24)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_pending_at', models.DateTimeField(blank=True, null=True)),
                ('release_due_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True, default='')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_hold', to='projects.dispute')),
                ('draw_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_payment_holds', to='projects.drawrequest')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_payment_holds', to='projects.expense')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_payment_holds', to='projects.invoice')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_payment_holds', to='projects.milestone')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'release_due_at'], name='projects_di_status_baceba_idx'), models.Index(fields=['milestone', 'status'], name='projects_di_milesto_62df50_idx'), models.Index(fields=['invoice', 'status'], name='projects_di_invoice_cd6e3b_idx')],
            },
        ),
    ]
