# Generated by Django 5.2.13 on 2026-09-12 06:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0299_dispute_contractor_notified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeEscrowAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_amount_cents', models.PositiveBigIntegerField()),
                ('contractor_amount_cents', models.PositiveBigIntegerField(default=0)),
                ('homeowner_amount_cents', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('explanation', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_authorization', 'Awaiting authorization'), ('authorized', 'Authorized by both parties'), ('ready_for_execution', 'Validated for execution'), ('executed', 'Executed'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=32)),
                ('homeowner_authorized_at', models.DateTimeField(blank=True, null=True)),
                ('contractor_authorized_at', models.DateTimeField(blank=True, null=True)),
                ('staff_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_reference', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contractor_authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_authorized_dispute_allocations', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_allocations', to='projects.dispute')),
                ('external_authority_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_allocations', to='projects.resolutiondocument')),
                ('homeowner_authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeowner_authorized_dispute_allocations', to=settings.AUTH_USER_MODEL)),
                ('payment_hold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='projects.disputepaymenthold')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_dispute_allocations', to=settings.AUTH_USER_MODEL)),
                ('staff_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_dispute_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DisputeWorkPauseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_type', models.CharField(choices=[('voluntary', 'Voluntary pause'), ('safety', 'Safety or hostile site conditions'), ('site_access', 'Site access unavailable'), ('external_process', 'External resolution process'), ('termination_review', 'Termination under review')], max_length=32)),
                ('explanation', models.TextField()),
                ('scope', models.TextField(blank=True, default='', help_text='Work or areas proposed for pausing.')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('ended', 'Ended')], db_index=True, default='requested', max_length=20)),
                ('response_reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_pause_requests', to='projects.dispute')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_dispute_work_pauses', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_dispute_work_pauses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
    ]
