# Generated by Django 5.2.13 on 2026-09-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0300_disputeescrowallocation_disputeworkpauserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputereminderlog',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
