# Generated by Django 5.2.13 on 2026-09-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0301_disputereminderlog_dedupe_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputeclaim',
            name='access_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disputeclaim',
            name='contractor_position',
            field=models.CharField(blank=True, choices=[('accept_responsibility', 'Accept responsibility'), ('dispute_allegation', 'Dispute allegation'), ('request_inspection', 'Request inspection'), ('propose_cure', 'Propose cure')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='disputeclaim',
            name='cure_proposal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='disputeclaim',
            name='customer_access_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disputeclaim',
            name='customer_access_response',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resolutiondocument',
            name='document_type',
            field=models.CharField(choices=[('pdf_package', 'PDF Package'), ('external_decision', 'External decision or directive'), ('mutual_instructions', 'Mutual financial instructions'), ('inspection_report', 'Independent inspection report'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
