# Generated by Django 5.2.13 on 2026-09-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0302_disputeclaim_access_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputeescrowallocation',
            name='contractor_transfer_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='disputeescrowallocation',
            name='execution_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='disputeescrowallocation',
            name='homeowner_refund_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('sent', 'Sent (Awaiting Payment)'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('paid', 'Paid'), ('settled', 'Resolved Allocation')], db_index=True, default='incomplete', max_length=20),
        ),
    ]
