# Generated by Django 5.2.13 on 2026-09-12 23:17

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_refund'),
        ('projects', '0303_disputeescrowallocation_contractor_transfer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disputeescrowallocation',
            name='settlement_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispute_escrow_allocations', to='projects.invoice'),
        ),
        migrations.CreateModel(
            name='DisputeEscrowAllocationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_amount_cents', models.PositiveBigIntegerField()),
                ('homeowner_refund_cents', models.PositiveBigIntegerField(default=0)),
                ('contractor_gross_cents', models.PositiveBigIntegerField(default=0)),
                ('platform_fee_cents', models.PositiveBigIntegerField(default=0)),
                ('contractor_payout_cents', models.PositiveBigIntegerField(default=0)),
                ('stripe_refund_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_transfer_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('partial', 'Partially executed'), ('executed', 'Executed'), ('failed', 'Failed')], db_index=True, default='reserved', max_length=20)),
                ('execution_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_sources', to='projects.disputeescrowallocation')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_escrow_sources', to='payments.payment')),
            ],
            options={
                'ordering': ['payment__created_at', 'payment_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEscrowAllocationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('source', 'Funding source reservation'), ('refund', 'Customer refund'), ('transfer', 'Contractor transfer'), ('fee', 'Platform fee')], db_index=True, max_length=16)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('amount_cents', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='started', max_length=16)),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_escrow_execution_attempts', to=settings.AUTH_USER_MODEL)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_attempts', to='projects.disputeescrowallocation')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='projects.disputeescrowallocationsource')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='disputeescrowallocationsource',
            constraint=models.UniqueConstraint(fields=('allocation', 'payment'), name='uniq_dispute_allocation_payment_source'),
        ),
        migrations.AddConstraint(
            model_name='disputeescrowallocationsource',
            constraint=models.CheckConstraint(condition=models.Q(('source_amount_cents', django.db.models.expressions.CombinedExpression(models.F('homeowner_refund_cents'), '+', models.F('contractor_gross_cents')))), name='dispute_source_split_balances'),
        ),
        migrations.AddConstraint(
            model_name='disputeescrowallocationsource',
            constraint=models.CheckConstraint(condition=models.Q(('contractor_gross_cents', django.db.models.expressions.CombinedExpression(models.F('platform_fee_cents'), '+', models.F('contractor_payout_cents')))), name='dispute_source_contractor_balances'),
        ),
        migrations.AddConstraint(
            model_name='disputeescrowallocationattempt',
            constraint=models.UniqueConstraint(fields=('allocation', 'source', 'action', 'attempt_number'), name='uniq_dispute_source_action_attempt'),
        ),
    ]
