# Generated by Django 5.2.13 on 2026-09-13 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0305_dispute_response_grace_deadlines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='qualification_extension_reason_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='disputeattachment',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='disputeattachment',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disputeattachment',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='disputeattachment',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='disputereminderlog',
            name='delivery_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='disputereminderlog',
            name='email_status',
            field=models.CharField(blank=True, default='not_attempted', max_length=32),
        ),
        migrations.AddField(
            model_name='disputereminderlog',
            name='in_app_status',
            field=models.CharField(blank=True, default='not_attempted', max_length=32),
        ),
        migrations.AddField(
            model_name='disputereminderlog',
            name='sms_status',
            field=models.CharField(blank=True, default='not_attempted', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('milestone__isnull', False)), fields=('milestone',), name='uniq_dispute_milestone_source'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_request__isnull', False)), fields=('payment_request',), name='uniq_dispute_invoice_source'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('draw_request__isnull', False)), fields=('draw_request',), name='uniq_dispute_draw_source'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('expense__isnull', False)), fields=('expense',), name='uniq_dispute_expense_source'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('amendment__isnull', False)), fields=('amendment',), name='uniq_dispute_amendment_source'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('warranty_request__isnull', False)), fields=('warranty_request',), name='uniq_dispute_warranty_source'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('warranty_service_request__isnull', False)), fields=('warranty_service_request',), name='uniq_dispute_warranty_service_source'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('source_type__in', ['agreement', 'general_project_issue']), ('status__in', ['initiated', 'open', 'under_review'])), fields=('agreement',), name='uniq_active_general_dispute_agreement'),
        ),
    ]
