# Generated by Django 5.2.13 on 2026-09-14 04:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_refund'),
        ('projects', '0307_platformfeepromotiongrant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrefundrequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='draw_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='projects.drawrequest'),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='external_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='projects.externalpaymentrecord'),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='failure_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='initiated_by_role',
            field=models.CharField(choices=[('homeowner', 'Homeowner'), ('contractor', 'Contractor')], db_index=True, default='homeowner', max_length=20),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='projects.invoice'),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='notification_delivery',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='payment_mode',
            field=models.CharField(choices=[('escrow', 'Escrow'), ('direct', 'Direct Pay'), ('external', 'External / record only')], db_index=True, default='escrow', max_length=20),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_refund_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='response_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='customerrefundrequest',
            name='source_type',
            field=models.CharField(choices=[('escrow', 'Escrow balance'), ('invoice', 'Invoice payment'), ('draw', 'Draw payment'), ('external', 'External payment')], db_index=True, default='escrow', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerrefundrequest',
            name='status',
            field=models.CharField(choices=[('refund_requested', 'Refund Requested'), ('contractor_response_needed', 'Contractor Response Needed'), ('under_review', 'Under Review'), ('countered', 'Different Amount Proposed'), ('approved', 'Approved'), ('denied', 'Denied'), ('processing', 'Processing'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='refund_requested', max_length=40),
        ),
        migrations.AlterField(
            model_name='drawrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('awaiting_release', 'Awaiting Release'), ('released', 'Released'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('paid', 'Paid'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='externalpaymentrecord',
            name='status',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('voided', 'Voided'), ('refunded', 'Refunded')], db_index=True, default='recorded', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('sent', 'Sent (Awaiting Payment)'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('paid', 'Paid'), ('settled', 'Resolved Allocation'), ('refunded', 'Refunded')], db_index=True, default='incomplete', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('subcontractor_comment', 'Subcontractor Comment'), ('subcontractor_file', 'Subcontractor File'), ('subcontractor_review', 'Subcontractor Review Request'), ('draw_approved', 'Draw Approved'), ('draw_changes_requested', 'Draw Changes Requested'), ('draw_paid', 'Draw Paid'), ('draw_released', 'Draw Released'), ('bid_awarded', 'Bid Awarded'), ('bid_not_selected', 'Bid Not Selected'), ('contractor_opportunity_received', 'Contractor Opportunity Received'), ('marketplace_verification_approved', 'Marketplace Verification Approved'), ('marketplace_verification_rejected', 'Marketplace Verification Rejected'), ('marketplace_verification_suspended', 'Marketplace Verification Suspended'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('quote_request_received', 'Quote Request Received'), ('agreement_signed', 'Agreement Signed'), ('escrow_funded', 'Escrow Funded'), ('invoice_approved', 'Invoice Approved'), ('milestone_pending_approval', 'Milestone Pending Approval'), ('payment_released', 'Payment Released'), ('estimate_viewed', 'Estimate Viewed'), ('estimate_customer_message', 'Estimate Customer Message'), ('agreement_customer_message', 'Agreement Customer Message'), ('project_customer_message', 'Project Customer Message'), ('refund_requested', 'Refund Requested'), ('refund_updated', 'Refund Updated'), ('estimate_revision_requested', 'Estimate Revision Requested'), ('estimate_accepted', 'Estimate Accepted'), ('estimate_declined', 'Estimate Declined')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='CustomerRefundRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('from_status', models.CharField(blank=True, default='', max_length=40)),
                ('to_status', models.CharField(blank=True, default='', max_length=40)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_request_events', to=settings.AUTH_USER_MODEL)),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.customerrefundrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRefundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('refund', 'Customer refund'), ('transfer_reversal', 'Contractor transfer reversal'), ('external_record', 'External refund record')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('amount_cents', models.PositiveBigIntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('source_payment_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('source_charge_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('source_transfer_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_refund_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_transfer_reversal_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_refund_transactions', to='payments.payment')),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='projects.customerrefundrequest')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
