# Generated by Django 5.2.13 on 2026-09-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0312_merge_0294_exclude_prelaunch_and_0311_hide_qa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsconsent',
            name='opted_in_source',
            field=models.CharField(blank=True, choices=[('signup', 'Signup'), ('agreement', 'Agreement'), ('inbound_start', 'Inbound START'), ('admin', 'Admin'), ('estimate_delivery_opt_in', 'Estimate delivery opt-in'), ('contractor_opportunity_opt_in', 'Contractor opportunity opt-in')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='contractoropportunity',
            name='outreach_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractoropportunity',
            name='outreach_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractoropportunity',
            name='outreach_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('awaiting_contractor_sms_consent', 'Awaiting Contractor SMS Consent'), ('delivered', 'Delivered'), ('sms_opted_out', 'SMS Opted Out'), ('failed', 'Failed')], db_index=True, default='not_started', max_length=48),
        ),
    ]
