# Generated by Django 5.2.13 on 2026-09-21 18:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_role_neutral_referrals(apps, schema_editor):
    Contractor = apps.get_model('projects', 'Contractor')
    ContractorReferral = apps.get_model('projects', 'ContractorReferral')
    FoundingAward = apps.get_model('projects', 'FoundingContractorAward')
    ReferralEarning = apps.get_model('projects', 'ReferralEarning')
    ReferralParticipant = apps.get_model('projects', 'ReferralParticipant')

    contractor_user_ids = set(Contractor.objects.values_list('user_id', flat=True))
    for participant in ReferralParticipant.objects.select_related('user').all().iterator():
        participant.primary_role = 'contractor' if participant.user_id in contractor_user_ids else 'homeowner'
        contractor = Contractor.objects.filter(user_id=participant.user_id).first()
        if contractor:
            participant.payout_stripe_account_id = contractor.stripe_account_id or ''
            participant.payout_details_submitted = bool(contractor.details_submitted)
            participant.payout_enabled = bool(contractor.payouts_enabled)
            participant.payout_onboarding_status = 'ready' if participant.payout_enabled else 'not_started'
        participant.save(update_fields=[
            'primary_role',
            'payout_stripe_account_id',
            'payout_details_submitted',
            'payout_enabled',
            'payout_onboarding_status',
        ])

    for award in FoundingAward.objects.select_related('contractor').all().iterator():
        award.pool = 'contractor'
        if award.contractor_id:
            award.participant = ReferralParticipant.objects.filter(user_id=award.contractor.user_id).first()
        award.save(update_fields=['pool', 'participant'])

    for referral in ContractorReferral.objects.select_related('referred_contractor').all().iterator():
        referral.referred_role = 'contractor'
        referral.referrer_role = 'contractor' if referral.referrer_id in contractor_user_ids else 'homeowner'
        if referral.referred_contractor_id:
            referral.referred_user_id = referral.referred_contractor.user_id
        referral.first_touch_at = referral.registered_at
        referral.attribution_locked_at = referral.registered_at
        referral.save(update_fields=[
            'referred_role',
            'referrer_role',
            'referred_user',
            'first_touch_at',
            'attribution_locked_at',
        ])

    for earning in ReferralEarning.objects.all().iterator():
        earning.allocation_side = 'contractor'
        earning.maximum_reward_pool_cents = int(earning.qualifying_platform_fee_cents or 0) * 5000 // 10000
        earning.save(update_fields=['allocation_side', 'maximum_reward_pool_cents'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0313_contractor_opportunity_outreach_state'),
        ('receipts', '0004_receipt_platform_fee_before_promotion_cents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProjectCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending_integration', 'Pending Integration'), ('applied', 'Applied'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending_integration', max_length=32)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, default='', max_length=255)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, max_length=20)),
                ('medium', models.CharField(blank=True, default='link', max_length=24)),
                ('landing_page', models.CharField(blank=True, default='', max_length=255)),
                ('session_key', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('first_touch_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('registration_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='foundingcontractoraward',
            name='unique_active_founding_slot',
        ),
        migrations.AddField(
            model_name='contractorreferral',
            name='acquisition_channel',
            field=models.CharField(default='referral', max_length=24),
        ),
        migrations.AddField(
            model_name='contractorreferral',
            name='attribution_locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorreferral',
            name='first_touch_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorreferral',
            name='landing_page',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contractorreferral',
            name='medium',
            field=models.CharField(blank=True, default='link', max_length=24),
        ),
        migrations.AddField(
            model_name='contractorreferral',
            name='referred_homeowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_attributions', to='projects.homeowner'),
        ),
        migrations.AddField(
            model_name='contractorreferral',
            name='referred_role',
            field=models.CharField(choices=[('contractor', 'Contractor'), ('homeowner', 'Homeowner / Customer'), ('property_manager', 'Property Manager')], db_index=True, default='contractor', max_length=24),
        ),
        migrations.AddField(
            model_name='contractorreferral',
            name='referred_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_attribution', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorreferral',
            name='referrer_role',
            field=models.CharField(blank=True, choices=[('contractor', 'Contractor'), ('homeowner', 'Homeowner / Customer'), ('property_manager', 'Property Manager')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='foundingcontractoraward',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founding_awards', to='projects.referralparticipant'),
        ),
        migrations.AddField(
            model_name='foundingcontractoraward',
            name='pool',
            field=models.CharField(choices=[('contractor', 'Contractors'), ('consumer', 'Homeowners and Property Managers')], db_index=True, default='contractor', max_length=20),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='allocation_side',
            field=models.CharField(choices=[('contractor', 'Contractor'), ('homeowner', 'Homeowner / Customer'), ('property_manager', 'Property Manager')], db_index=True, default='contractor', max_length=24),
        ),
        migrations.AddField(
            model_name='referralearning',
            name='maximum_reward_pool_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referralparticipant',
            name='payout_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralparticipant',
            name='payout_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralparticipant',
            name='payout_onboarding_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending'), ('ready', 'Ready'), ('restricted', 'Restricted')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='referralparticipant',
            name='payout_stripe_account_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='referralparticipant',
            name='primary_role',
            field=models.CharField(blank=True, choices=[('contractor', 'Contractor'), ('homeowner', 'Homeowner / Customer'), ('property_manager', 'Property Manager')], db_index=True, default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='contractorreferral',
            name='referred_contractor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_attribution', to='projects.contractor'),
        ),
        migrations.AlterField(
            model_name='foundingcontractoraward',
            name='contractor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='founding_award', to='projects.contractor'),
        ),
        migrations.AlterField(
            model_name='referralearning',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_earnings', to='receipts.receipt'),
        ),
        migrations.AlterField(
            model_name='referralearning',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('reserved', 'Reserved'), ('paid', 'Paid'), ('redeemed', 'Redeemed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='referralpayout',
            name='payout_method',
            field=models.CharField(choices=[('contractor_stripe', 'Contractor Stripe Connect'), ('participant_stripe', 'Participant Stripe Connect'), ('customer_credit', 'Customer project credit'), ('customer_direct_deposit', 'Customer direct deposit')], default='contractor_stripe', max_length=32),
        ),
        migrations.AlterField(
            model_name='referralpayout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_onboarding', 'Needs_Onboarding'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_role_neutral_referrals, noop_reverse),
        migrations.AddConstraint(
            model_name='foundingcontractoraward',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['reserved', 'awarded'])), fields=('pool', 'slot_number'), name='unique_active_founding_slot_per_pool'),
        ),
        migrations.AddConstraint(
            model_name='foundingcontractoraward',
            constraint=models.UniqueConstraint(condition=models.Q(('participant__isnull', False)), fields=('participant', 'pool'), name='unique_founding_award_participant_pool'),
        ),
        migrations.AddConstraint(
            model_name='referralearning',
            constraint=models.UniqueConstraint(fields=('referral', 'receipt'), name='unique_referral_earning_per_receipt'),
        ),
        migrations.AddConstraint(
            model_name='referralearning',
            constraint=models.CheckConstraint(condition=models.Q(('reward_cents__lte', models.F('maximum_reward_pool_cents'))), name='referral_earning_within_fee_pool'),
        ),
        migrations.AddField(
            model_name='referralprojectcredit',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_credits', to='projects.agreement'),
        ),
        migrations.AddField(
            model_name='referralprojectcredit',
            name='earnings',
            field=models.ManyToManyField(related_name='project_credits', to='projects.referralearning'),
        ),
        migrations.AddField(
            model_name='referralprojectcredit',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_credits', to='projects.invoice'),
        ),
        migrations.AddField(
            model_name='referralprojectcredit',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_credits', to='projects.referralparticipant'),
        ),
        migrations.AddField(
            model_name='referralprojectcredit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_credits', to='projects.project'),
        ),
        migrations.AddField(
            model_name='referralprojectcredit',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_referral_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='projects.referralparticipant'),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='registered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
