# Generated by Django 5.2.13 on 2026-09-21 19:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def populate_visitor_tokens(apps, schema_editor):
    ReferralVisit = apps.get_model('projects', 'ReferralVisit')
    for visit in ReferralVisit.objects.filter(visitor_token__isnull=True).iterator():
        visit.visitor_token = uuid.uuid4()
        visit.save(update_fields=['visitor_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0314_referralprojectcredit_referralvisit_and_more'),
        ('receipts', '0004_receipt_platform_fee_before_promotion_cents_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('public_code', models.SlugField(max_length=80, unique=True)),
                ('source', models.CharField(max_length=64)),
                ('medium', models.CharField(max_length=64)),
                ('campaign_name', models.CharField(max_length=100)),
                ('content', models.CharField(blank=True, default='', max_length=100)),
                ('destination', models.CharField(default='/', max_length=500)),
                ('partner_type', models.CharField(blank=True, default='', max_length=40)),
                ('partner_code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('public_code',),
            },
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='excluded_from_reporting',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='exclusion_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='first_campaign',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='first_content',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='first_medium',
            field=models.CharField(blank=True, db_index=True, default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='first_source',
            field=models.CharField(blank=True, db_index=True, default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='first_term',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='known_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='last_campaign',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='last_content',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='last_medium',
            field=models.CharField(blank=True, db_index=True, default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='last_source',
            field=models.CharField(blank=True, db_index=True, default='unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='last_term',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='last_landing_page',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='last_referrer_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='last_referrer_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='last_touch_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='referrer_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='referrer_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='visitor_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_visitor_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='referralvisit',
            name='visitor_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='referralvisit',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='projects.referralparticipant'),
        ),
        migrations.AlterField(
            model_name='referralvisit',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='AccountAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.JSONField(blank=True, default=list)),
                ('first_touch', models.JSONField(blank=True, default=dict)),
                ('last_touch', models.JSONField(blank=True, default=dict)),
                ('first_touch_at', models.DateTimeField(blank=True, null=True)),
                ('last_touch_at', models.DateTimeField(blank=True, null=True)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('profile_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_touch_accounts', to='projects.referralvisit')),
                ('last_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_touch_accounts', to='projects.referralvisit')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_acquisitions', to='projects.contractorreferral')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='referralvisit',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='projects.marketingcampaign'),
        ),
        migrations.CreateModel(
            name='ProjectAttributionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_attribution', models.JSONField(blank=True, default=dict)),
                ('contractor_attribution', models.JSONField(blank=True, default=dict)),
                ('snapshotted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contractor_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_project_snapshots', to='projects.contractorreferral')),
                ('contractor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_project_attribution_snapshots', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_attribution_snapshots', to=settings.AUTH_USER_MODEL)),
                ('customer_referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_project_snapshots', to='projects.contractorreferral')),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_project_attribution_snapshots', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attribution_snapshot', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueAttributionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_attribution', models.JSONField(blank=True, default=dict)),
                ('contractor_attribution', models.JSONField(blank=True, default=dict)),
                ('eligible_platform_fee_cents', models.PositiveIntegerField(default=0)),
                ('maximum_reward_pool_cents', models.PositiveIntegerField(default=0)),
                ('customer_reward_cents', models.PositiveIntegerField(default=0)),
                ('contractor_reward_cents', models.PositiveIntegerField(default=0)),
                ('total_referral_reward_cents', models.PositiveIntegerField(default=0)),
                ('retained_platform_fee_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_revenue_attribution_snapshots', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_revenue_attribution_snapshots', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_attribution_snapshots', to='projects.project')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attribution_snapshot', to='receipts.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='AttributionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('landing_view', 'Landing View'), ('improvement_template_view', 'Improvement Template View'), ('guide_view', 'Guide View'), ('signup_started', 'Signup Started'), ('role_selected', 'Role Selected'), ('diy_project_started', 'Diy Project Started'), ('hire_pro_clicked', 'Hire Pro Clicked'), ('contractor_profile_viewed', 'Contractor Profile Viewed'), ('contractor_invite_started', 'Contractor Invite Started'), ('account_created', 'Account Created'), ('profile_completed', 'Profile Completed'), ('project_created', 'Project Created'), ('contractor_invited', 'Contractor Invited'), ('estimate_created', 'Estimate Created'), ('estimate_accepted', 'Estimate Accepted'), ('agreement_created', 'Agreement Created'), ('agreement_signed', 'Agreement Signed'), ('project_funded', 'Project Funded'), ('platform_fee_generated', 'Platform Fee Generated'), ('milestone_approved', 'Milestone Approved'), ('project_completed', 'Project Completed'), ('referral_reward_generated', 'Referral Reward Generated'), ('referral_reward_redeemed', 'Referral Reward Redeemed')], db_index=True, max_length=64)),
                ('role', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('source', models.CharField(blank=True, db_index=True, default='unknown', max_length=64)),
                ('medium', models.CharField(blank=True, db_index=True, default='unknown', max_length=64)),
                ('campaign_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('content', models.CharField(blank=True, default='', max_length=100)),
                ('landing_page', models.CharField(blank=True, default='', max_length=255)),
                ('object_type', models.CharField(blank=True, default='', max_length=64)),
                ('object_id', models.CharField(blank=True, default='', max_length=80)),
                ('idempotency_key', models.CharField(blank=True, max_length=190, null=True, unique=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_events', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_events', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribution_events', to='projects.referralvisit')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='projects.marketingcampaign')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='attrib_event_time_idx'), models.Index(fields=['source', 'medium'], name='attrib_source_medium_idx')],
            },
        ),
    ]
