# Generated by Django 5.2.1 on 2026-09-21 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0316_seed_marketing_campaigns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplatePublicSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_slug', models.SlugField(max_length=100)),
                ('slug', models.SlugField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='common_mistakes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='cost_guidance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional recommended')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='diy_guidance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='estimated_duration_max_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='estimated_duration_min_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='is_featured_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='preparation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='pro_guidance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_category_slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_faqs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_intro',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_publication_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=24),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_public_project_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_summary',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='related_public_templates',
            field=models.ManyToManyField(blank=True, to='projects.projecttemplate'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='safety_guidance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=170),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=70),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='social_image',
            field=models.CharField(blank=True, default='', help_text='Approved root-relative static image path; user uploads are not accepted here.', max_length=255),
        ),
        migrations.AddIndex(
            model_name='projecttemplate',
            index=models.Index(fields=['public_publication_status', 'public_category_slug'], name='tpl_public_category_idx'),
        ),
        migrations.AddField(
            model_name='projecttemplatepublicslug',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_slug_history', to='projects.projecttemplate'),
        ),
        migrations.AddConstraint(
            model_name='projecttemplatepublicslug',
            constraint=models.UniqueConstraint(fields=('category_slug', 'slug'), name='uniq_public_template_slug_history'),
        ),
    ]
