# Generated by Django 5.2.1 on 2026-09-21 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0317_public_improvement_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyproject',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Canonical Improvement Library template used to start this DIY project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diy_projects', to='projects.projecttemplate'),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Canonical Improvement Library template that initiated this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_intakes', to='projects.projecttemplate'),
        ),
    ]
