# Generated by Django 5.2.13 on 2026-09-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0319_prepare_bathroom_public_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='public_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='tools_guidance',
            field=models.TextField(blank=True, default=''),
        ),
    ]
