# Generated by Django 5.2.13 on 2026-09-22 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0321_prepare_bathroom_launch_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectintake',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='classified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classified_project_intakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='traffic_classification',
            field=models.CharField(choices=[('real', 'Real'), ('test', 'Test'), ('spam_fraud', 'Spam / fraud'), ('archived', 'Archived')], db_index=True, default='real', max_length=20),
        ),
    ]
