# Generated by Django 5.2.13 on 2026-09-22 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0322_account_verification_anti_abuse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectintake',
            name='classification_before_archive',
            field=models.CharField(blank=True, choices=[('real', 'Real'), ('test', 'Test'), ('suspicious', 'Suspicious'), ('spam_fraud', 'Spam / fraud'), ('archived', 'Archived')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectintake',
            name='traffic_classification',
            field=models.CharField(choices=[('real', 'Real'), ('test', 'Test'), ('suspicious', 'Suspicious'), ('spam_fraud', 'Spam / fraud'), ('archived', 'Archived')], db_index=True, default='real', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectIntakeClassificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_classification', models.CharField(blank=True, default='', max_length=20)),
                ('new_classification', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_intake_classification_events', to=settings.AUTH_USER_MODEL)),
                ('project_intake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classification_events', to='projects.projectintake')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
