# Generated by Django 5.2.13 on 2026-09-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0324_contractorinvite_contact_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectintake',
            name='final_marketplace_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='first_marketplace_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='marketplace_archive_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='marketplace_archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='marketplace_hold_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='marketplace_last_archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='marketplace_last_archive_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='marketplace_restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectintake',
            name='marketplace_retention_protection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('subcontractor_comment', 'Subcontractor Comment'), ('subcontractor_file', 'Subcontractor File'), ('subcontractor_review', 'Subcontractor Review Request'), ('draw_approved', 'Draw Approved'), ('draw_changes_requested', 'Draw Changes Requested'), ('draw_paid', 'Draw Paid'), ('draw_released', 'Draw Released'), ('bid_awarded', 'Bid Awarded'), ('bid_not_selected', 'Bid Not Selected'), ('contractor_opportunity_received', 'Contractor Opportunity Received'), ('marketplace_first_reminder', 'Marketplace First Reminder'), ('marketplace_final_reminder', 'Marketplace Final Reminder'), ('marketplace_verification_approved', 'Marketplace Verification Approved'), ('marketplace_verification_rejected', 'Marketplace Verification Rejected'), ('marketplace_verification_suspended', 'Marketplace Verification Suspended'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('quote_request_received', 'Quote Request Received'), ('agreement_signed', 'Agreement Signed'), ('escrow_funded', 'Escrow Funded'), ('invoice_approved', 'Invoice Approved'), ('milestone_pending_approval', 'Milestone Pending Approval'), ('payment_released', 'Payment Released'), ('estimate_viewed', 'Estimate Viewed'), ('estimate_customer_message', 'Estimate Customer Message'), ('agreement_customer_message', 'Agreement Customer Message'), ('project_customer_message', 'Project Customer Message'), ('refund_requested', 'Refund Requested'), ('refund_updated', 'Refund Updated'), ('estimate_revision_requested', 'Estimate Revision Requested'), ('estimate_accepted', 'Estimate Accepted'), ('estimate_declined', 'Estimate Declined')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('marketplace_request_archived', 'Marketplace Request Archived'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('warranty_request_received', 'Warranty Request Received'), ('warranty_information_requested', 'Warranty Information Requested'), ('warranty_inspection_scheduled', 'Warranty Inspection Scheduled'), ('warranty_coverage_decision', 'Warranty Coverage Decision'), ('warranty_repair_scheduled', 'Warranty Repair Scheduled'), ('warranty_repair_completed', 'Warranty Repair Completed'), ('warranty_acknowledgment_requested', 'Warranty Acknowledgment Requested'), ('warranty_closed', 'Warranty Closed'), ('warranty_escalated', 'Warranty Escalated'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready'), ('tenant_maintenance_request_submitted', 'Tenant Maintenance Request Submitted')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('marketplace_request_archived', 'Marketplace Request Archived'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('warranty_request_received', 'Warranty Request Received'), ('warranty_information_requested', 'Warranty Information Requested'), ('warranty_inspection_scheduled', 'Warranty Inspection Scheduled'), ('warranty_coverage_decision', 'Warranty Coverage Decision'), ('warranty_repair_scheduled', 'Warranty Repair Scheduled'), ('warranty_repair_completed', 'Warranty Repair Completed'), ('warranty_acknowledgment_requested', 'Warranty Acknowledgment Requested'), ('warranty_closed', 'Warranty Closed'), ('warranty_escalated', 'Warranty Escalated'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready'), ('tenant_maintenance_request_submitted', 'Tenant Maintenance Request Submitted')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='smartnotification',
            name='event_type',
            field=models.CharField(choices=[('customer_request_submitted', 'Customer Request Submitted'), ('property_profile_updated', 'Property Profile Updated'), ('marketplace_request_routed', 'Marketplace Request Routed'), ('marketplace_request_archived', 'Marketplace Request Archived'), ('customer_bid_received', 'Customer Bid Received'), ('bid_awarded', 'Bid Awarded'), ('agreement_needs_signature', 'Agreement Needs Signature'), ('agreement_signed', 'Agreement Signed'), ('escrow_needs_funding', 'Escrow Needs Funding'), ('escrow_funded', 'Escrow Funded'), ('milestone_needs_approval', 'Milestone Needs Approval'), ('payment_received', 'Payment Received'), ('reimbursement_submitted', 'Reimbursement Submitted'), ('reimbursement_approved', 'Reimbursement Approved'), ('reimbursement_denied', 'Reimbursement Denied'), ('reimbursement_released', 'Reimbursement Released'), ('reimbursement_held', 'Reimbursement Held'), ('dispute_opened', 'Dispute Opened'), ('dispute_updated', 'Dispute Updated'), ('dispute_resolved', 'Dispute Resolved'), ('maintenance_work_order_scheduled', 'Maintenance Work Order Scheduled'), ('maintenance_work_order_completed', 'Maintenance Work Order Completed'), ('maintenance_contract_cancelled', 'Maintenance Contract Cancelled'), ('warranty_request_received', 'Warranty Request Received'), ('warranty_information_requested', 'Warranty Information Requested'), ('warranty_inspection_scheduled', 'Warranty Inspection Scheduled'), ('warranty_coverage_decision', 'Warranty Coverage Decision'), ('warranty_repair_scheduled', 'Warranty Repair Scheduled'), ('warranty_repair_completed', 'Warranty Repair Completed'), ('warranty_acknowledgment_requested', 'Warranty Acknowledgment Requested'), ('warranty_closed', 'Warranty Closed'), ('warranty_escalated', 'Warranty Escalated'), ('home_system_maintenance_reminder', 'Home System Maintenance Reminder'), ('request_marketplace_ready', 'Request Marketplace Ready'), ('tenant_maintenance_request_submitted', 'Tenant Maintenance Request Submitted')], db_index=True, max_length=64),
        ),
    ]
