# Generated by Django 5.2.13 on 2026-09-25 15:43

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0325_marketplace_request_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceAutomaticMatchingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_key', models.CharField(max_length=120)),
                ('state_key', models.CharField(max_length=60)),
                ('trade', models.CharField(choices=[('carpentry', 'Carpentry'), ('concrete', 'Concrete'), ('drywall', 'Drywall'), ('electrical', 'Electrical'), ('flooring', 'Flooring'), ('gutters', 'Gutters'), ('hvac', 'Hvac'), ('painting', 'Painting'), ('plumbing', 'Plumbing'), ('remodeling', 'Remodeling'), ('roofing', 'Roofing'), ('siding', 'Siding'), ('windows', 'Windows')], max_length=32)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_matching_approval_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['state_key', 'city_key'], name='market_match_location_idx')],
                'constraints': [
                    models.UniqueConstraint(fields=('city_key', 'state_key', 'trade'), name='uniq_marketplace_matching_city_state_trade'),
                    models.CheckConstraint(condition=~models.Q(city_key='') & ~models.Q(state_key='') & ~models.Q(trade=''), name='marketplace_matching_identity_nonblank'),
                    models.CheckConstraint(condition=models.Q(trade__in=('carpentry', 'concrete', 'drywall', 'electrical', 'flooring', 'gutters', 'hvac', 'painting', 'plumbing', 'remodeling', 'roofing', 'siding', 'windows')), name='marketplace_matching_known_trade'),
                ],
            },
        ),
    ]
