# Generated by Django 5.2.13 on 2026-09-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0325_marketplace_request_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelocation',
            name='approved_trades',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='marketplacelocation',
            name='paused_trades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
