# Generated by Django 5.2.13 on 2026-09-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0326_automatic_matching_trade_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='public_audience',
            field=models.CharField(choices=[('contractor', 'Contractors'), ('homeowner', 'Homeowners'), ('property_manager', 'Property managers')], db_index=True, default='homeowner', max_length=24),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_evidence',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_evidence_source',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_next_action',
            field=models.CharField(blank=True, choices=[('sign_up', 'Sign up'), ('create_project', 'Create a project'), ('request_help', 'Request help')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_practical_steps',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_problem',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_viewpoint',
            field=models.TextField(blank=True, default=''),
        ),
    ]
