# Generated by Django 5.2.13 on 2026-09-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0328_contractor_improvement_editorial_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='public_video_description',
            field=models.CharField(blank=True, default='', max_length=320),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_video_poster_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_video_text_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_video_title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_video_transcript_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='public_video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
