import { expect, test } from '@playwright/test';
import fs from 'node:fs/promises';

async function mockAdminDirectory(page) {
  await page.addInitScript(() => {
    window.localStorage.setItem('access', 'playwright-access-token');
  });

  await page.route('**/api/projects/whoami/', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        id: 1,
        type: 'admin',
        role: 'admin',
        email: 'owner@myhomebro.local',
      }),
    });
  });

  const directoryRequests = [];
  let searchRequested = false;
  let captureRequested = false;
  let capturePayload = null;
  let patchRequested = false;
  let importApplyRequested = false;
  let importApplyPayload = null;
  let directoryRows = [
    {
      id: 42,
      business_name: 'Austin Concrete Co',
      website: 'https://www.austinconcrete.example/contact',
      phone: '512-555-0101',
      address_line1: '12703 Spectrum Dr #103',
      public_email: null,
      has_public_email: false,
      has_phone: true,
      has_website: true,
      has_contact_form: false,
      contact_form_url: '',
      contact_status: 'phone_ready',
      preferred_outreach_method: 'sms',
      contact_confidence: 'high',
      outreach_notes: '',
      outreach_status: 'no_outreach',
      outreach_attempt_count: 0,
      latest_outreach_type: null,
      latest_outreach_status: null,
      latest_outreach_at: null,
      latest_outreach_notes: null,
      claim_readiness_status: 'ready',
      claim_readiness_notes: 'Ready for claim-link outreach.',
      city: 'San Antonio',
      state: 'TX',
      zip_code: '78249',
      rating: 4.8,
      review_count: 22,
      services: ['concrete_contractor'],
      primary_service: 'Concrete',
      normalized_services: ['Concrete'],
      raw_services: ['concrete contractor', 'point of interest'],
      source: 'google_places',
      claimed: false,
      profile_status: 'basic',
      enrichment_status: 'not_started',
      email_source_url: '',
      services_source_url: '',
      enrichment_notes: '',
      first_seen_at: '2026-05-01T12:00:00Z',
      last_seen_at: '2026-05-02T12:00:00Z',
      is_archived: false,
      archived_at: null,
    },
  ];

  await page.route('**/api/projects/admin/contractor-directory/**', async (route) => {
    directoryRequests.push(new URL(route.request().url()));
    const requestUrl = new URL(route.request().url());

    if (requestUrl.pathname.endsWith('/api/projects/admin/contractor-directory/42/claim-link/')) {
      directoryRows = directoryRows.map((row) => (
        row.id === 42
          ? {
              ...row,
              outreach_status: 'claim_link_generated',
              outreach_attempt_count: Number(row.outreach_attempt_count || 0) + 1,
              latest_outreach_type: 'claim_link_copied',
              latest_outreach_status: 'generated',
              latest_outreach_at: '2026-05-20T12:00:00Z',
              latest_outreach_notes: 'Claim link generated by admin.',
            }
          : row
      ));
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ claim_url: '/contractors/claim/directory-token', entry: directoryRows[0] }),
      });
      return;
    }

    if (requestUrl.pathname.endsWith('/api/projects/admin/contractor-directory/42/outreach-log/')) {
      const payload = JSON.parse(route.request().postData() || '{}');
      const statusByType = {
        phone: 'phone_outreach_logged',
        website_form: 'website_outreach_logged',
        manual_note: 'manual_review_needed',
      };
      directoryRows = directoryRows.map((row) => (
        row.id === 42
          ? {
              ...row,
              contact_status: payload.outreach_type === 'manual_note' ? 'manual_review_needed' : row.contact_status,
              outreach_notes: payload.outreach_type === 'manual_note' ? payload.notes : row.outreach_notes,
              outreach_status: statusByType[payload.outreach_type] || 'outreach_logged',
              outreach_attempt_count: Number(row.outreach_attempt_count || 0) + 1,
              latest_outreach_type: payload.outreach_type,
              latest_outreach_status: 'logged',
              latest_outreach_at: '2026-05-20T12:03:00Z',
              latest_outreach_notes: payload.notes,
            }
          : row
      ));
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ id: 5, outreach_type: payload.outreach_type, entry: directoryRows[0] }),
      });
      return;
    }

    if (requestUrl.pathname.endsWith('/api/projects/admin/contractor-directory/42/archive/')) {
      directoryRows = directoryRows.map((row) => (
        row.id === 42 ? { ...row, is_archived: true, archived_at: '2026-05-20T12:00:00Z' } : row
      ));
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(directoryRows[0]),
      });
      return;
    }

    if (requestUrl.pathname.endsWith('/api/projects/admin/contractor-directory/42/restore/')) {
      directoryRows = directoryRows.map((row) => (
        row.id === 42 ? { ...row, is_archived: false, archived_at: null } : row
      ));
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(directoryRows[0]),
      });
      return;
    }

    if (requestUrl.pathname.endsWith('/api/projects/admin/contractor-directory/import-preview/')) {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          count: 1,
          matched_count: 1,
          results: [
            {
              matched_entry_id: 42,
              matched_by: 'id',
              business_name: 'Austin Concrete Co',
              existing_public_email: null,
              proposed_public_email: 'hello@austinconcrete.example',
              existing_services: ['concrete_contractor'],
              proposed_services: ['concrete contractor', 'patio contractor'],
              existing_primary_service: 'Concrete',
              proposed_primary_service: 'Patio',
              existing_normalized_services: ['Concrete'],
              proposed_normalized_services: ['Concrete', 'Patio'],
              status: 'ready',
              warnings: [],
              email_source_url: 'https://www.austinconcrete.example/contact',
              services_source_url: 'https://www.austinconcrete.example/services',
              enrichment_notes: 'Reviewed website.',
            },
          ],
        }),
      });
      return;
    }

    if (requestUrl.pathname.endsWith('/api/projects/admin/contractor-directory/import-apply/')) {
      importApplyRequested = true;
      importApplyPayload = JSON.parse(route.request().postData() || '{}');
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ updated_count: 1, skipped_count: 0, warnings: [] }),
      });
      return;
    }

    if (route.request().method() === 'PATCH' && requestUrl.pathname.endsWith('/api/projects/admin/contractor-directory/42/')) {
      patchRequested = true;
      const payload = JSON.parse(route.request().postData() || '{}');
      directoryRows = [
        {
          ...directoryRows[0],
          ...payload,
          services: ['concrete contractor', 'patio contractor'],
          enrichment_status: 'reviewed',
          service_normalization_status: 'manual',
        },
      ];
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(directoryRows[0]),
      });
      return;
    }

    const archivedFilter = requestUrl.searchParams.get('archived') || 'active';
    const filteredRows = directoryRows.filter((row) => (
      archivedFilter === 'all'
        ? true
        : archivedFilter === 'archived'
          ? row.is_archived
          : !row.is_archived
    ));
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        count: filteredRows.length,
        results: filteredRows,
      }),
    });
  });

  await page.route('**/api/projects/admin/contractor-search/**', async (route) => {
    const requestUrl = new URL(route.request().url());
    if (requestUrl.pathname.endsWith('/api/projects/admin/contractor-search/capture/')) {
      captureRequested = true;
      capturePayload = JSON.parse(route.request().postData() || '{}');
      directoryRows = [
        ...directoryRows,
        {
          id: 77,
          business_name: 'Admin Concrete Search Result',
          website: 'https://searchresult.example',
          phone: '512-555-0202',
          address_line1: '',
          public_email: null,
          city: 'Austin',
          state: 'TX',
          zip_code: '78701',
          rating: 4.7,
          review_count: 12,
          services: ['concrete_contractor'],
          primary_service: 'Concrete',
          normalized_services: ['Concrete'],
          raw_services: ['concrete contractor'],
          source: 'google_places',
          claimed: false,
          profile_status: 'basic',
          enrichment_status: 'not_started',
          first_seen_at: '2026-05-03T12:00:00Z',
          last_seen_at: '2026-05-03T12:00:00Z',
          is_archived: false,
          archived_at: null,
        },
      ];
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          summary: { captured_count: 1, directory_entries_count: 1 },
          results: [{ ...capturePayload.selected_results[0], directory_entry_id: 77, captured: true }],
          directory_entries: [directoryRows[directoryRows.length - 1]],
        }),
      });
      return;
    }

    searchRequested = true;
    const payload = JSON.parse(route.request().postData() || '{}');
    expect(payload.city).toBe('Austin');
    expect(payload.state).toBe('TX');
    expect(payload.zip).toBe('78701');
    expect(payload.radius_miles).toBe('25');
    if (payload.query === 'no results') {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          summary: { results_count: 0, relevant_results_count: 0, directory_entries_count: 0, capture_required: true },
          results: [],
        }),
      });
      return;
    }
    expect(payload.query).toBe('concrete contractor');
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        summary: { results_count: 2, relevant_results_count: 1, directory_entries_count: 0, capture_required: true },
        results: [
          {
            id: 'places/admin-concrete',
            business_name: 'Admin Concrete Search Result',
            website_url: 'https://searchresult.example',
            phone_number: '512-555-0202',
            city: 'Austin',
            state: 'TX',
            rating: 4.7,
            review_count: 12,
            source: 'google_places',
            relevance_label: 'Strong Match',
            relevance_reason: 'Business name shares search words.',
            is_relevant: true,
          },
          {
            id: 'places/unrelated',
            business_name: 'Unrelated Electric Co',
            city: 'Austin',
            state: 'TX',
            rating: 4.1,
            review_count: 5,
            source: 'google_places',
            relevance_label: 'Weak Match',
            relevance_reason: 'Limited overlap with the search term.',
            is_relevant: false,
          },
        ],
      }),
    });
  });

  return {
    directoryRequests,
    wasSearchRequested: () => searchRequested,
    wasCaptureRequested: () => captureRequested,
    capturePayload: () => capturePayload,
    wasPatchRequested: () => patchRequested,
    wasImportApplyRequested: () => importApplyRequested,
    importApplyPayload: () => importApplyPayload,
  };
}

test('admin contractor directory supports search, filters, table, and export affordance', async ({ page }) => {
  const mocks = await mockAdminDirectory(page);

  await page.goto('/app/admin/contractor-directory', { waitUntil: 'domcontentloaded' });

  await expect(page.getByTestId('admin-contractor-directory-page')).toBeVisible();
  const pageClass = await page.getByTestId('admin-contractor-directory-page').getAttribute('class');
  expect(pageClass).toContain('min-h-screen');
  const importClass = await page.getByTestId('admin-contractor-import-section').getAttribute('class');
  expect(importClass).toContain('bg-[#061d42]/95');
  await expect(page.getByRole('heading', { name: 'Contractor Directory', exact: true })).toBeVisible();
  await expect(page.getByText('Search results are not saved until you capture them.')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-search-term')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-search-city')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-search-state')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-search-zip')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-search-radius')).toHaveValue('25');

  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Austin Concrete Co');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Concrete');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('12703 Spectrum Dr #103');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('San Antonio, TX 78249');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Phone Ready');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('No Outreach');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('0 outreach attempts');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Sms');
  await expect(page.getByText('Email not listed')).toBeVisible();
  await expect(page.getByRole('link', { name: 'austinconcrete.example' })).toHaveAttribute(
    'href',
    'https://www.austinconcrete.example/contact'
  );
  await expect(page.getByTestId('admin-contractor-directory-export')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-filter-missing-email')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-filter-has-email')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-filter-has-website')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-filter-city')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-filter-state')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-filter-primary-service')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-filter-contact-status')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-filter-outreach-method')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-filter-contact-form')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-filter-archived')).toHaveValue('active');

  await page.getByTestId('admin-contractor-filter-missing-email').check();
  await expect.poll(() =>
    mocks.directoryRequests.some((url) => url.searchParams.get('missing_email') === 'true')
  ).toBe(true);

  await page.getByTestId('admin-contractor-filter-has-website').check();
  await page.getByTestId('admin-contractor-filter-city').fill('Austin');
  await page.getByTestId('admin-contractor-filter-state').fill('TX');
  await expect.poll(() =>
    mocks.directoryRequests.some((url) => (
      url.searchParams.get('has_website') === 'true'
      && url.searchParams.get('city') === 'Austin'
      && url.searchParams.get('state') === 'TX'
    ))
  ).toBe(true);

  await page.getByTestId('admin-contractor-search-term').fill('concrete contractor');
  await page.getByTestId('admin-contractor-search-city').fill('Austin');
  await page.getByTestId('admin-contractor-search-state').fill('TX');
  await page.getByTestId('admin-contractor-search-zip').fill('78701');
  await page.getByTestId('admin-contractor-search-submit').click();

  await expect.poll(() => mocks.wasSearchRequested()).toBe(true);
  await expect(page.getByTestId('admin-contractor-search-results')).toContainText('Admin Concrete Search Result');
  await expect(page.getByTestId('admin-contractor-search-results')).toContainText('Strong Match');
  await expect(page.getByTestId('admin-contractor-search-results')).toContainText('Unrelated Electric Co');
  await expect(page.getByTestId('admin-contractor-search-results')).toContainText('Weak Match');
  await expect(page.getByTestId('admin-contractor-search-results')).toContainText('Preview only');
  await page.getByTestId('admin-contractor-search-select-1').uncheck();
  await page.getByTestId('admin-contractor-capture-selected').click();
  await expect.poll(() => mocks.wasCaptureRequested()).toBe(true);
  expect(mocks.capturePayload().selected_results).toHaveLength(1);
  expect(mocks.capturePayload().selected_results[0].business_name).toBe('Admin Concrete Search Result');
  await expect(page.getByTestId('admin-contractor-toast')).toContainText('1 contractor captured to the directory.');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Admin Concrete Search Result');
  await expect(page.getByText('Mark Claimed')).toHaveCount(0);
  await expect(page.getByTestId('admin-contractor-claim-link-42')).toBeVisible();
  await page.getByTestId('admin-contractor-claim-link-42').click();
  await expect(page.getByTestId('admin-contractor-toast')).toContainText('Claim link generated.');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Claim Link Generated');
  await expect(page.getByTestId('admin-contractor-copy-claim-link-42')).toBeVisible();
  await page.getByTestId('admin-contractor-copy-claim-link-42').click();
  await expect(page.getByTestId('admin-contractor-toast')).toContainText('Claim link copied.');
  await page.getByTestId('admin-contractor-log-phone-42').click();
  await expect(page.getByTestId('admin-contractor-toast')).toContainText('Phone outreach logged');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Phone Outreach Logged');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('2 outreach attempts');
  await page.getByTestId('admin-contractor-log-form-42').click();
  await expect(page.getByTestId('admin-contractor-toast')).toContainText('Website form outreach logged');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Website Outreach Logged');
  await page.getByTestId('admin-contractor-log-review-42').click();
  await expect(page.getByTestId('admin-contractor-toast')).toContainText('Manual review status updated');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Manual Review Needed');
});

test('admin contractor directory initializes filters from marketplace URL query params', async ({ page }) => {
  const mocks = await mockAdminDirectory(page);

  await page.goto('/app/admin/contractor-directory?missing_email=true&has_email=true&has_website=true&claimed=false&primary_service=Concrete&city=San%20Antonio&state=TX&archived=all', { waitUntil: 'domcontentloaded' });

  await expect(page.getByTestId('admin-contractor-filter-missing-email')).toBeChecked();
  await expect(page.getByTestId('admin-contractor-filter-has-email')).toBeChecked();
  await expect(page.getByTestId('admin-contractor-filter-has-website')).toBeChecked();
  await expect(page.getByTestId('admin-contractor-filter-primary-service')).toHaveValue('Concrete');
  await expect(page.getByTestId('admin-contractor-filter-city')).toHaveValue('San Antonio');
  await expect(page.getByTestId('admin-contractor-filter-state')).toHaveValue('TX');
  await expect(page.getByTestId('admin-contractor-filter-archived')).toHaveValue('all');
  await expect.poll(() =>
    mocks.directoryRequests.some((url) => (
      url.searchParams.get('missing_email') === 'true'
      && url.searchParams.get('has_email') === 'true'
      && url.searchParams.get('has_website') === 'true'
      && url.searchParams.get('claimed') === 'false'
      && url.searchParams.get('primary_service') === 'Concrete'
      && url.searchParams.get('city') === 'San Antonio'
      && url.searchParams.get('state') === 'TX'
      && url.searchParams.get('archived') === 'all'
    ))
  ).toBe(true);
});

test('admin contractor directory archives and restores entries with archived filter', async ({ page }) => {
  await mockAdminDirectory(page);

  await page.goto('/app/admin/contractor-directory', { waitUntil: 'domcontentloaded' });
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Austin Concrete Co');
  await page.getByTestId('admin-contractor-archive-42').click();
  await expect(page.getByTestId('admin-contractor-toast')).toContainText('Directory entry archived.');
  await expect(page.getByTestId('admin-contractor-directory-table')).not.toContainText('Austin Concrete Co');

  await page.getByTestId('admin-contractor-filter-archived').selectOption('archived');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Austin Concrete Co');
  await expect(page.getByTestId('admin-contractor-restore-42')).toBeVisible();
  await page.getByTestId('admin-contractor-restore-42').click();
  await expect(page.getByTestId('admin-contractor-toast')).toContainText('Directory entry restored.');
  await expect(page.getByTestId('admin-contractor-directory-table')).not.toContainText('Austin Concrete Co');

  await page.getByTestId('admin-contractor-filter-archived').selectOption('active');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Austin Concrete Co');
});

test('admin contractor directory shows no results only for true empty preview responses', async ({ page }) => {
  await mockAdminDirectory(page);

  await page.goto('/app/admin/contractor-directory', { waitUntil: 'domcontentloaded' });
  await expect(page.getByText('Search results will appear here.')).toBeVisible();

  await page.getByTestId('admin-contractor-search-term').fill('no results');
  await page.getByTestId('admin-contractor-search-city').fill('Austin');
  await page.getByTestId('admin-contractor-search-state').fill('TX');
  await page.getByTestId('admin-contractor-search-zip').fill('78701');
  await page.getByTestId('admin-contractor-search-submit').click();

  await expect(page.getByText('No results found. Try a broader trade term, nearby city, or larger radius.')).toBeVisible();
  await expect(page.getByText('Search results will appear here.')).toHaveCount(0);
});

test('admin contractor directory supports manual edit, import preview/apply, and enriched CSV export', async ({ page }) => {
  const mocks = await mockAdminDirectory(page);

  await page.goto('/app/admin/contractor-directory', { waitUntil: 'domcontentloaded' });

  await page.getByTestId('admin-contractor-edit-42').click();
  await expect(page.getByTestId('admin-contractor-edit-modal')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-edit-address_line1')).toHaveValue('12703 Spectrum Dr #103');
  await expect(page.getByTestId('admin-contractor-edit-city')).toHaveValue('San Antonio');
  await expect(page.getByTestId('admin-contractor-edit-state')).toHaveValue('TX');
  await expect(page.getByTestId('admin-contractor-edit-zip_code')).toHaveValue('78249');
  await expect(page.getByTestId('admin-contractor-edit-has_contact_form')).toHaveValue('false');
  await expect(page.getByTestId('admin-contractor-edit-primary_service')).toHaveValue('Concrete');
  await expect(page.getByTestId('admin-contractor-edit-normalized_services')).toHaveValue('Concrete');
  await page.getByTestId('admin-contractor-edit-public_email').fill('hello@austinconcrete.example');
  await page.getByTestId('admin-contractor-edit-has_contact_form').selectOption('true');
  await page.getByTestId('admin-contractor-edit-contact_form_url').fill('https://www.austinconcrete.example/contact');
  await page.getByTestId('admin-contractor-edit-contact_status').fill('website_form_ready');
  await page.getByTestId('admin-contractor-edit-preferred_outreach_method').fill('website_form');
  await page.getByTestId('admin-contractor-edit-contact_confidence').fill('medium');
  await page.getByTestId('admin-contractor-edit-outreach_notes').fill('Contact form reviewed.');
  await page.getByTestId('admin-contractor-edit-primary_service').fill('Patio');
  await page.getByTestId('admin-contractor-edit-normalized_services').fill('Concrete, Patio');
  await page.getByTestId('admin-contractor-edit-address_line1').fill('900 Builder Way');
  await page.getByTestId('admin-contractor-edit-city').fill('Austin');
  await page.getByTestId('admin-contractor-edit-state').fill('TX');
  await page.getByTestId('admin-contractor-edit-zip_code').fill('78701');
  await page.getByTestId('admin-contractor-edit-services').fill('concrete contractor, patio contractor');
  await page.getByTestId('admin-contractor-edit-email_source_url').fill('https://www.austinconcrete.example/contact');
  await page.getByTestId('admin-contractor-edit-save').click();

  await expect.poll(() => mocks.wasPatchRequested()).toBe(true);
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('hello@austinconcrete.example');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('900 Builder Way');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('Austin, TX 78701');
  await expect(page.getByTestId('admin-contractor-directory-table')).toContainText('reviewed');

  await page.getByTestId('admin-contractor-import-csv').fill(
    'id,business_name,website,phone,address_line1,city,state,zip_code,public_email,services,primary_service,normalized_services,raw_services,email_source_url,services_source_url,enrichment_notes\n' +
      '42,Austin Concrete Co,https://www.austinconcrete.example,512-555-0101,900 Builder Way,Austin,TX,78701,hello@austinconcrete.example,"concrete contractor, patio contractor",Patio,"Concrete, Patio","concrete contractor",https://www.austinconcrete.example/contact,https://www.austinconcrete.example/services,Reviewed website.'
  );
  await page.getByTestId('admin-contractor-import-preview').click();
  await expect(page.getByTestId('admin-contractor-import-preview-table')).toContainText('ready');
  await expect(page.getByTestId('admin-contractor-import-preview-table')).toContainText('id');
  await expect(page.getByTestId('admin-contractor-import-preview-table')).toContainText('hello@austinconcrete.example');
  await page.getByLabel('Approve import row 1').check();
  await page.getByTestId('admin-contractor-import-apply').click();
  await expect.poll(() => mocks.wasImportApplyRequested()).toBe(true);
  expect(mocks.importApplyPayload().rows).toHaveLength(1);
  expect(mocks.importApplyPayload().rows[0].admin_approved).toBe(true);
  await expect(page.getByText('Updated 1 entries. Skipped 0.')).toBeVisible();
});

test('admin contractor directory upload CSV fills textarea and previews matched rows', async ({ page }) => {
  await mockAdminDirectory(page);

  await page.goto('/app/admin/contractor-directory', { waitUntil: 'domcontentloaded' });
  const csv = [
    'entry_id,business_name,website,public_email,services,enrichment_notes',
    '42,Austin Concrete Co,https://www.austinconcrete.example/contact,hello@austinconcrete.example,"concrete contractor, patio contractor","Reviewed, with comma"',
  ].join('\n');

  await page.getByTestId('admin-contractor-import-file').setInputFiles({
    name: 'enriched-contractors.csv',
    mimeType: 'text/csv',
    buffer: Buffer.from(csv),
  });

  await expect(page.getByTestId('admin-contractor-import-filename')).toContainText('enriched-contractors.csv');
  await expect(page.getByText('CSV loaded. Review the rows below, then preview the import.')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-import-csv')).toHaveValue(csv);
  await page.getByTestId('admin-contractor-import-preview').click();
  await expect(page.getByText('Preview found 1 matching row out of 1.')).toBeVisible();
  await expect(page.getByTestId('admin-contractor-import-preview-table')).toContainText('id');
  await expect(page.getByTestId('admin-contractor-import-preview-table')).not.toContainText('no_match');
});

test('admin contractor directory export includes enrichment columns and blank missing emails', async ({ page }) => {
  await mockAdminDirectory(page);

  await page.goto('/app/admin/contractor-directory', { waitUntil: 'domcontentloaded' });
  const downloadPromise = page.waitForEvent('download');
  await page.getByTestId('admin-contractor-directory-export').click();
  const download = await downloadPromise;
  const path = await download.path();
  const text = await fs.readFile(path, 'utf8');

  expect(download.suggestedFilename()).toBe('contractor-directory-missing-emails.csv');
  expect(text).toContain('email_source_url');
  expect(text).toContain('services_source_url');
  expect(text).toContain('enrichment_notes');
  expect(text).toContain('address_line1');
  expect(text).toContain('zip_code');
  expect(text).toContain('primary_service');
  expect(text).toContain('normalized_services');
  expect(text).toContain('raw_services');
  expect(text).toContain('"12703 Spectrum Dr #103"');
  expect(text).toContain('"Concrete"');
  expect(text).toContain('"78249"');
  expect(text).toContain('"Austin Concrete Co"');
  expect(text).not.toContain('Email not listed');
});
