# Generated by Django 5.2.8 on 2025-12-26 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0028_alter_invoice_public_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=64, unique=True)),
                ("stripe_payment_intent_id", models.CharField(max_length=255)),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("amount_paid_cents", models.PositiveIntegerField()),
                ("platform_fee_cents", models.PositiveIntegerField(default=0)),
                ("card_brand", models.CharField(blank=True, max_length=32, null=True)),
                ("card_last4", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="projects.invoice",
                    ),
                ),
            ],
        ),
    ]
