# Generated by Django 5.2.8 on 2025-12-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="email_last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
