# Generated by ChatGPT for MyHomeBro
# receipts/migrations/0003_receipt_fee_snapshot_fields.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("receipts", "0002_receipt_email_last_error_receipt_emailed_at"),
        # If your projects app initial migration is not 0001_initial,
        # change this to whatever your latest/required projects migration is.
        ("projects", "0001_initial"),
    ]

    operations = [
        # Optional but strongly recommended for fee auditing + agreement cap calculations
        migrations.AddField(
            model_name="receipt",
            name="agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipts",
                to="projects.agreement",
            ),
        ),

        # ─────────────────────────────────────────────
        # Fee audit snapshot fields (all nullable for safe rollout)
        # ─────────────────────────────────────────────

        migrations.AddField(
            model_name="receipt",
            name="fee_engine_version",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="fee_plan_code",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="fee_rate",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="flat_fee",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="monthly_volume_used",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="platform_fee_uncapped_cents",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="cap_total_cents",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="cap_already_collected_cents",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="cap_remaining_cents",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="is_intro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receipt",
            name="high_risk_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receipt",
            name="tier_name",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
