# Generated by Django 5.2.13 on 2026-09-13 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0307_platformfeepromotiongrant_and_more'),
        ('receipts', '0003_receipt_fee_snapshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='platform_fee_before_promotion_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='promotion_grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='projects.platformfeepromotiongrant'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='waived_fee_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='waiver_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
