import React, { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, Minus, MousePointer2, Move, Pentagon, Redo2, Ruler, Save, Trash2, Undo2 } from "lucide-react";
import { Link, useParams } from "react-router-dom";

import { actOnPhotoMeasurementAnnotation, createPhotoMeasurementAnnotation, createPhotoMeasurementCalibration, getPhotoMeasurementDocument, getPhotoMeasurementImage } from "../api/captures.js";
import { Button, InlineAlert, LoadingSkeleton } from "../components/ui";
import { imageCoordinateToSvg, pointerToImageCoordinate } from "../lib/imageCoordinates.js";

const TOOLS=[["select","Select",MousePointer2],["pan","Pan",Move],["reference","Set reference",Ruler],["line","Line",Minus],["polyline","Polyline",Redo2],["polygon","Polygon",Pentagon]];
const message=(error,fallback)=>error?.response?.data?.detail||Object.values(error?.response?.data||{})?.[0]||error?.message||fallback;

export default function PhotoMeasurementWorkspacePage(){
  const {sessionId,documentId}=useParams(); const overlayRef=useRef(null);
  const [document,setDocument]=useState(null),[imageUrl,setImageUrl]=useState(""),[tool,setTool]=useState("select"),[points,setPoints]=useState([]),[label,setLabel]=useState(""),[category,setCategory]=useState(""),[repeatGroup,setRepeatGroup]=useState(""),[knownLength,setKnownLength]=useState(""),[unit,setUnit]=useState("feet"),[attested,setAttested]=useState(false),[calibrationId,setCalibrationId]=useState(""),[selected,setSelected]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[statusText,setStatusText]=useState("Loading photo.");
  async function reload(){const next=await getPhotoMeasurementDocument(documentId);setDocument(next);const active=next.calibrations.find(row=>!row.invalidated_at);setCalibrationId(current=>current||String(active?.id||""));return next}
  useEffect(()=>{let url="";Promise.all([reload(),getPhotoMeasurementImage(documentId)]).then(([,blob])=>{url=URL.createObjectURL(blob);setImageUrl(url);setStatusText("Orientation-normalized photo loaded.")}).catch(reason=>setError(message(reason,"Photo could not be opened.")));return()=>{if(url)URL.revokeObjectURL(url)}},[documentId]);
  const annotations=useMemo(()=>document?.annotations||[],[document]);
  function addPoint(event){if(!["reference","line","polyline","polygon"].includes(tool)||event.pointerType==="touch"&&!event.isPrimary)return;event.preventDefault();try{const point=pointerToImageCoordinate(event,overlayRef.current);const next=[...points,point];setPoints(next);if((tool==="reference"||tool==="line")&&next.length===2)setStatusText("Geometry ready to review and save.")}catch{setError("Place points inside the image.")}}
  async function save(){setBusy(true);setError("");try{if(tool==="reference"){if(points.length!==2||!knownLength||!attested)throw new Error("Draw two reference points, enter the known length, and confirm the same physical plane.");await createPhotoMeasurementCalibration(documentId,{reference_geometry:{points},known_length:knownLength,unit,label,same_plane_attested:attested,expected_document_version:document.version});setStatusText("Reference saved. Results remain estimates until independently verified.")}else{const minimum=tool==="polygon"?3:2;if(points.length<minimum||!label.trim()||!calibrationId)throw new Error("Select a reference, add the required points, and enter a label.");await createPhotoMeasurementAnnotation(documentId,{calibration_id:Number(calibrationId),geometry_type:tool,geometry:{points},label:label.trim(),category:category.trim(),repeat_group:repeatGroup,expected_document_version:document.version});setStatusText("Photo estimate saved for review.")}setPoints([]);setLabel("");setRepeatGroup("");await reload()}catch(reason){setError(message(reason,"Save failed."))}finally{setBusy(false)}}
  async function action(row,kind,payload={}){setBusy(true);setError("");try{await actOnPhotoMeasurementAnnotation(row.id,kind,payload);setSelected(null);await reload();setStatusText(kind==="repeat"?"Repeat attempt saved. Adjust its points through a new measurement if needed.":kind==="archive"?"Attempt archived.":"Proposal added to Measurement Session.")}catch(reason){setError(message(reason,"Action failed."))}finally{setBusy(false)}}
  function beginRepeat(row){setTool(row.geometry_type);setPoints([]);setLabel(`${row.label} repeat`);setCategory(row.category||"");setCalibrationId(String(row.calibration_id));setRepeatGroup(row.repeat_group||`photo-${row.id}`);setSelected(null);setStatusText("Place new endpoints for the repeated measurement. The prior attempt remains preserved.")}
  function mapped(geometry){return geometry.points.map(imageCoordinateToSvg)}
  if(!document&&!error)return <div className="p-4"><LoadingSkeleton theme="operational" preset="workspace" label="Loading photo measurement workspace"/></div>;
  return <main className="min-w-0 p-3 sm:p-5" data-testid="photo-measurement-workspace">
    <header className="mb-3"><Link to={`/app/measurements/${sessionId}`} className="inline-flex min-h-11 items-center gap-2 text-sm font-bold text-blue-400"><ArrowLeft size={17}/>Measurement Session</Link><h1 className="text-xl font-bold sm:text-2xl">{document?.original_filename||"Photo measurement"}</h1><p className="text-sm text-[var(--mhb-text-secondary)]">Calibrated photo estimate · normalized {document?.normalized_width}×{document?.normalized_height}</p></header>
    <div className="sr-only" role="status" aria-live="polite">{statusText}</div>{error?<InlineAlert theme="operational" tone="danger">{String(error)}</InlineAlert>:null}
    <div className="mb-3"><InlineAlert theme="operational" tone="warning">Reference and target must be on the same physical plane. Perspective and curved surfaces can produce incorrect results. Verify tolerance-sensitive work in the field.</InlineAlert></div>
    <div className="grid min-w-0 gap-3 xl:grid-cols-[auto_minmax(0,1fr)_20rem]">
      <nav aria-label="Photo measurement tools" className="order-2 flex gap-1 overflow-x-auto rounded-xl border border-[var(--mhb-border-default)] bg-[var(--mhb-surface-card)] p-2 xl:order-1 xl:flex-col">{TOOLS.map(([key,text,Icon])=><button key={key} type="button" aria-pressed={tool===key} onClick={()=>{setTool(key);setPoints([])}} className={`flex min-h-11 items-center gap-2 rounded-lg px-3 font-bold ${tool===key?"bg-[var(--mhb-interaction-primary)] text-white":""}`}><Icon size={18}/><span className="whitespace-nowrap xl:sr-only">{text}</span></button>)}</nav>
      <section className="order-1 min-w-0 overflow-auto rounded-xl border border-[var(--mhb-border-default)] bg-slate-950 p-2 xl:order-2" style={{maxHeight:"72vh"}}><div ref={overlayRef} onPointerDown={addPoint} className={`relative mx-auto w-fit ${tool==="pan"?"touch-pan-x touch-pan-y":"touch-none"}`}><img src={imageUrl} alt="Orientation-normalized measurement source" className="block max-h-[68vh] max-w-full select-none object-contain" draggable="false"/>{imageUrl?<svg viewBox="0 0 1000 1000" preserveAspectRatio="none" className="absolute inset-0 h-full w-full" aria-hidden="true">{annotations.map(row=>{const coordinates=mapped(row.geometry).map(point=>`${point.x},${point.y}`).join(" ");return row.geometry_type==="polygon"?<polygon key={row.id} points={coordinates} className="fill-blue-500/20 stroke-blue-400" strokeWidth="3" vectorEffect="non-scaling-stroke" onClick={()=>setSelected(row)}/>:<polyline key={row.id} points={coordinates} className="fill-none stroke-blue-400" strokeWidth="3" vectorEffect="non-scaling-stroke" onClick={()=>setSelected(row)}/>})}{points.length?<polyline points={mapped({points}).map(point=>`${point.x},${point.y}`).join(" ")} className="fill-none stroke-amber-400" strokeWidth="3" vectorEffect="non-scaling-stroke"/>:null}</svg>:null}</div></section>
      <aside className="order-3 rounded-xl border border-[var(--mhb-border-default)] bg-[var(--mhb-surface-card)] p-3"><h2 className="font-bold">Review measurement</h2><label className="mt-3 block text-sm font-bold">Active reference<select value={calibrationId} onChange={event=>setCalibrationId(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[var(--mhb-border-default)] bg-[var(--mhb-surface-inset)] px-3"><option value="">No reference</option>{document?.calibrations.filter(row=>!row.invalidated_at).map(row=><option key={row.id} value={row.id}>{row.known_length} {row.unit} · {row.confidence.replaceAll("_"," ")}</option>)}</select></label>
      {["reference","line","polyline","polygon"].includes(tool)?<div className="mt-3 grid gap-3"><label className="text-sm font-bold">Label<input value={label} onChange={event=>setLabel(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[var(--mhb-border-default)] bg-[var(--mhb-surface-inset)] px-3"/></label>{tool==="reference"?<><label className="text-sm font-bold">Known length<input value={knownLength} inputMode="decimal" onChange={event=>setKnownLength(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[var(--mhb-border-default)] bg-[var(--mhb-surface-inset)] px-3"/></label><select value={unit} onChange={event=>setUnit(event.target.value)} className="min-h-11 rounded-lg bg-[var(--mhb-surface-inset)] px-3">{["feet","inches","millimeters","centimeters","meters"].map(value=><option key={value}>{value}</option>)}</select><label className="flex gap-2 text-sm"><input type="checkbox" checked={attested} onChange={event=>setAttested(event.target.checked)}/>I confirm the reference and intended target are on the same physical plane.</label></>:<label className="text-sm font-bold">Category<input value={category} onChange={event=>setCategory(event.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-[var(--mhb-border-default)] bg-[var(--mhb-surface-inset)] px-3"/></label>}<div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm" disabled={!points.length} onClick={()=>setPoints(current=>current.slice(0,-1))}><Undo2 size={16}/>Undo</Button><Button variant="secondary" size="sm" onClick={()=>setPoints([])}>Cancel</Button><Button variant="primary" size="sm" loading={busy} onClick={save}><Save size={16}/>Save</Button></div></div>:null}
      <h3 className="mt-5 font-bold">Attempts</h3><div className="mt-2 grid gap-2">{annotations.map(row=><button key={row.id} type="button" onClick={()=>setSelected(row)} className="min-h-11 rounded-lg border border-[var(--mhb-border-default)] p-2 text-left"><strong className="block">{row.label}</strong><span className="text-xs">{row.normalized_value} {row.normalized_unit} · {row.confidence.replaceAll("_"," ")}</span></button>)}</div>
      {selected?<div className="mt-3 rounded-lg bg-[var(--mhb-surface-inset)] p-3"><strong>{selected.label}</strong><p className="text-sm">{selected.normalized_value} {selected.normalized_unit}</p>{selected.repeat_statistics?<p className="text-xs">Repeat range {selected.repeat_statistics.minimum}–{selected.repeat_statistics.maximum}; spread {selected.repeat_statistics.relative_spread}</p>:null}{selected.warnings.map(warning=><p key={warning} className="mt-1 text-xs text-amber-400">{warning}</p>)}<div className="mt-3 flex flex-wrap gap-2">{!selected.measurement_result_id?<><Button size="sm" onClick={()=>action(selected,"create-proposal")}><Check size={16}/>Create proposal</Button><Button variant="secondary" size="sm" onClick={()=>beginRepeat(selected)}><Redo2 size={16}/>Repeat</Button><Button variant="danger" size="sm" onClick={()=>action(selected,"archive")}><Trash2 size={16}/>Archive</Button></>:<span className="text-xs font-bold text-emerald-400">Added for Measurement review</span>}</div></div>:null}</aside>
    </div>
  </main>
}
