#!/usr/bin/env bash
# ~/backend/scripts/rebuild_all.sh
# v2025-11-09 — end-to-end rebuild for PythonAnywhere

set -euo pipefail

# ── Paths (adjust if your layout differs)
REPO_ROOT="$HOME/backend"
BACKEND_DIR="$REPO_ROOT/backend"
FRONTEND_DIR="$REPO_ROOT/frontend"
STATIC_ROOT="${STATIC_ROOT_OVERRIDE:-$REPO_ROOT/staticfiles}"
ASSETS_DIR="$STATIC_ROOT/assets"

# ── Helpers
log() { printf "\n\033[1;34m[%s]\033[0m %s\n" "$(date +%H:%M:%S)" "$*"; }

# ── 0) Ensure dirs exist
mkdir -p "$ASSETS_DIR"

# ── 1) Activate venv
log "Activating virtualenv…"
source "$REPO_ROOT/venv/bin/activate"

# ── 2) Pull latest code (optional; comment if you deploy another way)
log "Pulling latest from Git…"
git -C "$REPO_ROOT" fetch --all --tags
git -C "$REPO_ROOT" pull --ff-only || true

# ── 3) Backend deps & migrations
log "Installing backend requirements (if any)…"
if [[ -f "$REPO_ROOT/requirements.txt" ]]; then
  pip install --upgrade -r "$REPO_ROOT/requirements.txt"
fi

log "Applying Django migrations…"
python "$BACKEND_DIR/manage.py" migrate --noinput

# ── 4) Frontend build (Vite)
log "Building frontend…"
cd "$FRONTEND_DIR"

# Normalize potential CRLF in scripts/node files (harmless if not present)
if command -v dos2unix >/dev/null 2>&1; then
  find . -type f -name "*.sh" -exec dos2unix {} + || true
fi

# Use npm ci when package-lock exists; fall back to npm i
if [[ -f package-lock.json ]]; then
  npm ci
else
  npm i
fi

# Vite build
npx vite build

# ── 5) Publish assets to STATIC_ROOT/assets
log "Publishing built assets to $ASSETS_DIR …"
mkdir -p "$ASSETS_DIR"
rsync -av --delete "$FRONTEND_DIR/dist/assets/" "$ASSETS_DIR/"

# ── 6) Create stable symlinks for index.js / index.css
log "Creating stable symlinks (index.js, index.css)…"
cd "$ASSETS_DIR"

# Find newest hashed bundles generated by Vite
JS_HASHED="$(ls -1t index-*.js 2>/dev/null | head -n1 || true)"
CSS_HASHED="$(ls -1t index-*.css 2>/dev/null | head -n1 || true)"

if [[ -n "${JS_HASHED}" ]]; then
  ln -sf "${JS_HASHED}" index.js
  log "index.js -> ${JS_HASHED}"
else
  log "WARN: no index-*.js found in $ASSETS_DIR"
fi

if [[ -n "${CSS_HASHED}" ]]; then
  ln -sf "${CSS_HASHED}" index.css
  log "index.css -> ${CSS_HASHED}"
else
  log "WARN: no index-*.css found in $ASSETS_DIR"
fi

# ── 7) Collectstatic (optional if you serve directly from staticfiles/)
# Enable if your Django settings expect collectstatic to populate STATIC_ROOT.
# log "Collecting static files…"
# python "$BACKEND_DIR/manage.py" collectstatic --noinput

# ── 8) Reload web app (PythonAnywhere)
log "Reloading web app via WSGI touch…"
# Touch wsgi to force reload; adjust path to your WSGI file if different:
WSGI_FILE="$BACKEND_DIR/wsgi.py"
# If you use PA’s 'Reload' button, you can skip this; otherwise:
touch "$WSGI_FILE" || true

log "Done ✅"
