from decimal import Decimal

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models


class PhotoMeasurementDocument(models.Model):
    contractor = models.ForeignKey("projects.Contractor", on_delete=models.CASCADE, related_name="photo_measurement_documents")
    measurement_session = models.ForeignKey("projects.MeasurementSession", on_delete=models.CASCADE, related_name="photo_documents")
    artifact = models.OneToOneField("projects.CaptureArtifact", on_delete=models.PROTECT, related_name="photo_measurement_document")
    project = models.ForeignKey("projects.Project", on_delete=models.CASCADE, related_name="photo_measurement_documents")
    proposal = models.ForeignKey("projects.Proposal", on_delete=models.SET_NULL, null=True, blank=True, related_name="photo_measurement_documents")
    normalized_image = models.FileField(upload_to="capture/measurement/photo-previews/%Y/%m/")
    original_filename = models.CharField(max_length=255)
    mime_type = models.CharField(max_length=32)
    checksum = models.CharField(max_length=64, db_index=True)
    original_width = models.PositiveIntegerField()
    original_height = models.PositiveIntegerField()
    normalized_width = models.PositiveIntegerField()
    normalized_height = models.PositiveIntegerField()
    original_orientation = models.PositiveSmallIntegerField(default=1)
    orientation_transform = models.CharField(max_length=40, default="identity")
    source = models.CharField(max_length=32, default="capture_artifact")
    status = models.CharField(max_length=16, default="active", db_index=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="photo_documents_created")
    archived_at = models.DateTimeField(null=True, blank=True)
    version = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class PhotoMeasurementCalibration(models.Model):
    CONFIDENCE_CHOICES = (("low", "Low"), ("medium", "Medium"), ("high_estimate", "High estimate"), ("verified", "Verified"))
    document = models.ForeignKey(PhotoMeasurementDocument, on_delete=models.CASCADE, related_name="calibrations")
    reference_geometry = models.JSONField()
    known_length = models.DecimalField(max_digits=24, decimal_places=10, validators=[MinValueValidator(Decimal("0.0000000001"))])
    unit = models.CharField(max_length=24)
    canonical_pixel_distance = models.DecimalField(max_digits=24, decimal_places=10)
    scale_per_pixel = models.DecimalField(max_digits=24, decimal_places=10)
    working_region = models.JSONField(default=dict, blank=True)
    same_plane_attested = models.BooleanField(default=False)
    same_plane_attested_at = models.DateTimeField()
    marker_version = models.CharField(max_length=32, blank=True, default="")
    confidence = models.CharField(max_length=24, choices=CONFIDENCE_CHOICES, default="medium")
    evidence = models.JSONField(default=list)
    warnings = models.JSONField(default=list)
    image_checksum = models.CharField(max_length=64)
    algorithm_version = models.CharField(max_length=32, default="photo_geometry.v1")
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="photo_calibrations_created")
    invalidated_at = models.DateTimeField(null=True, blank=True)
    superseded_by = models.ForeignKey("self", on_delete=models.PROTECT, null=True, blank=True, related_name="supersedes")
    version = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)


class PhotoMeasurementAnnotation(models.Model):
    TYPE_CHOICES = (("line", "Line"), ("polyline", "Polyline"), ("polygon", "Polygon"))
    document = models.ForeignKey(PhotoMeasurementDocument, on_delete=models.CASCADE, related_name="annotations")
    calibration = models.ForeignKey(PhotoMeasurementCalibration, on_delete=models.PROTECT, related_name="annotations")
    previous_revision = models.ForeignKey("self", on_delete=models.PROTECT, null=True, blank=True, related_name="revisions")
    measurement_entry = models.ForeignKey("projects.MeasurementEntry", on_delete=models.PROTECT, null=True, blank=True, related_name="photo_annotations")
    measurement_result = models.ForeignKey("projects.MeasurementCalculatedResult", on_delete=models.PROTECT, null=True, blank=True, related_name="photo_annotations")
    geometry_type = models.CharField(max_length=16, choices=TYPE_CHOICES)
    geometry = models.JSONField()
    label = models.CharField(max_length=160)
    category = models.CharField(max_length=80, blank=True, default="")
    repeat_group = models.CharField(max_length=80, blank=True, default="")
    preferred_attempt = models.BooleanField(default=False)
    normalized_value = models.DecimalField(max_digits=24, decimal_places=10)
    normalized_unit = models.CharField(max_length=32)
    perimeter_value = models.DecimalField(max_digits=24, decimal_places=10, null=True, blank=True)
    confidence = models.CharField(max_length=24, default="medium")
    evidence = models.JSONField(default=list)
    warnings = models.JSONField(default=list)
    calculation_version = models.CharField(max_length=32, default="photo_geometry.v1")
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="photo_annotations_created")
    archived_at = models.DateTimeField(null=True, blank=True)
    version = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
